### ISSUE TITLE
Remove a client certificate/configuration

### ISSUE THREAD

**Issue by phlegx** [kylemanna/docker-openvpn#103]
Hi,

wondering if there is a way to remove a generated client certificate and configuration? If yes, how to do that?

thanks in advance!

**Comment by ypid** [comment]
@phlegx https://github.com/kylemanna/docker-openvpn/blob/master/docs/clients.md#revoking-client-certificates

**Comment by kylemanna** [comment]
@ypid nailed it :+1:

**Comment by phlegx** [comment]
Awesome! Thanks guys! :+1:

**Comment by phlegx** [comment]
On the page @ypid linked us too, there can be also generated a client list with:

```docker run --rm -it --volumes-from $OVPN_DATA kylemanna/openvpn ovpn_listclients```

However, I get the following error:

```
exec: "ovpn_listclients": executable file not found in $PATH
docker: Error response from daemon: Container command not found or does not exist..
```
Is this happening only for me?
