### ISSUE TITLE
Parameters for building CA

### ISSUE THREAD

**Issue by peterlavelle** [kylemanna/docker-openvpn#108]
Hi,

Is there a way to define the parameters for the Certificate request (City, County, etc) via environment variables when bringing up the docker image?

When using docker-compose, it fails at this point when trying to build the CA:

eneratepki_1 | writing new private key to '/etc/openvpn/pki/private/ca.key.XXXXlalebf'
generatepki_1 | -----
generatepki_1 | You are about to be asked to enter information that will be incorporated
generatepki_1 | into your certificate request.
generatepki_1 | What you are about to enter is what is called a Distinguished Name or a DN.
generatepki_1 | There are quite a few fields but you can leave some blank
generatepki_1 | For some fields there will be a default value,
generatepki_1 | If you enter '.', the field will be left blank.
generatepki_1 | -----
generatepki_1 | Common Name (eg: your user, host, or server name) [Easy-RSA CA]:problems making Certificate Request
generatepki_1 |
generatepki_1 | Easy-RSA error:
generatepki_1 |
generatepki_1 | Failed to build the CA

In my docker-compose file, I have the following environment variables defined for the CSR information, but they aren't being used by the ovpn_initpki script

KEY_COUNTRY
KEY_PROVINCE
KEY_CITY
KEY_ORG
KEY_EMAIL

**Comment by DeviaVir** [comment]
@peterlavelle I automated this by passing the following environment variables:
```
EASYRSA_BATCH=true
EASYRSA_REQ_CN=$HOSTNAME
```

where `$HOSTNAME` is a hostname, i.e. `mydomain.com`

**Comment by peterlavelle** [comment]
That did it :+1: 

Thanks, much appreciated @DeviaVir

**Comment by DeviaVir** [comment]
No problem! Had to figure the same thing out not so long ago.

Relevant code, for learning purposes:
https://github.com/OpenVPN/easy-rsa/blob/master/easyrsa3/easyrsa#L454
