### ISSUE TITLE
How used from iphone/ipad?

### ISSUE THREAD

**Issue by gebv** [kylemanna/docker-openvpn#111]
Have error via my iphone (openvpn client 1.0.5 build 177)
```
2016-03-04 12:00:43 VERIFY FAIL -- bad ns-cert-type in leaf certificate
2016-03-04 12:00:43 Transport Error: PolarSSL: SSL read error : X509 - Certificate verification failed, e.g. CRL, CA or signature check failed
2016-03-04 12:00:43 EVENT: CERT_VERIFY_FAIL PolarSSL: SSL read error : X509 - Certificate verification failed, e.g. CRL, CA or signature check failed [ERR]
2016-03-04 12:00:43 EVENT: DISCONNECTED
2016-03-04 12:00:43 Raw stats on disconnect:
 BYTES_IN : 2672
 BYTES_OUT : 1062
 PACKETS_IN : 20
 PACKETS_OUT : 20
 SSL_ERROR : 1
 CERT_VERIFY_FAIL : 1
2016-03-04 12:00:43 Performance stats on disconnect:
 CPU usage (microseconds): 75739
 Network bytes per CPU second: 49300
 Tunnel bytes per CPU second: 0
2016-03-04 12:00:43 EVENT: DISCONNECT_PENDING
2016-03-04 12:00:43 ----- OpenVPN Stop -----
```

Include CA in <cert> section not solve the problem

```
<cert>
$(openssl x509 -in $EASYRSA_PKI/issued/${cn}.crt -text)
</cert>
```

PS I tried to analyze openvpnas, they all work because the ```ns-cert-type server```?

**Comment by smalltimecharlie** [comment]
Hi, 

Have you included the ca, the cert and the key inline in the .ovpn file? I've found that references to files doesn’t work on ios devices (whereas it will on android).

**Comment by gebv** [comment]
@smalltimecharlie yes, all in one file

**Comment by smalltimecharlie** [comment]
@gebv 
It might be helpful if you posted the config you've got up with details obfuscated where appropriate. Can compare and contrast to a working setup then.

**Comment by gebv** [comment]
I have started this docker-container as is
MacOS tunnelblick - OK
ios 7 iphone - https://s3.amazonaws.com/idheap/ss/foto.PNG_2016-05-01_10-40-44.png
ios 9 ipad - connection timeout

**Comment by gebv** [comment]
what I'm doing wrong

**Comment by kylemanna** [comment]
Really looks like the client doesn't use the inline CA or it's not included.  A obfuscated config might help.

**Comment by gebv** [comment]
I don't know what changed, but it's a lot better.
Now works on all ios devices without errors
Thank you for the job @kylemanna

**Comment by gebv** [comment]
I think the problem is solved

**Comment by kylemanna** [comment]
Thanks for the update!
