### ISSUE TITLE
/etc/openvpn: No Directory & difference between OpenVPN .conf files

### ISSUE THREAD

**Issue by XPOTiFY** [kylemanna/docker-openvpn#113]
Hello, 

in the OpenVPN README file is, "The configuration is located in /etc/openvpn" but when I change my dicretory to `cd /etc/openvpn` there is no such directory `-bash: cd: /etc/openvpn: No such file or directory`
And when I open the .conf file there are much less lines compared to Normal OpenVPN config file.
The first on is the .conf generated from Docker OpenVPN

```
client
nobind
dev tun
remote-cert-tls server
remote X.X.X.X 1194 udp
```

and this one is generated from normal OpenVPN script
```
client
dev tun
cipher AES-256-CBC
auth SHA256
proto udp
remote X.X.X.X 1194
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
comp-lzo
verb 3
```

The difference is interesting somehow :D

**Comment by kylemanna** [comment]
The files are under `/etc/openvpn` in the docker container.

Review the [login shell debugging section](https://github.com/kylemanna/docker-openvpn/blob/master/docs/debug.md#login-shells) to review the files.

**Comment by williclarkam** [comment]
wow, then I had to first `"docker exec -it CONTAINER_NAME /bin/bash"` execute this command to enter? interesting.
Thanks Sir, but there is something else I don't understand too.
As you see in my config file, there is no Cipher and no Hashing, does this mean, that your default config doesn't use these parameters? (Like AES/Blow-Fish ...)

Best regards,

**Comment by ragaar** [comment]
@williclarkam you'd want to review the documentation provided by OpenVPN.
The default cipher is BF-CBC (Blowfish - Cipher Block Chain)

REF: https://openvpn.net/index.php/open-source/documentation/security-overview.html

**Comment by ragaar** [comment]
I'd also like to add that I think this is getting off-topic from the original question.
