### ISSUE TITLE
[Question] Networking on Host

### ISSUE THREAD

**Issue by thebenwaters** [kylemanna/docker-openvpn#114]
I'm working on modifying the current docker implementation to allow specific access control policies within openvpn.

[https://openvpn.net/index.php/open-source/documentation/howto.html#policy](https://openvpn.net/index.php/open-source/documentation/howto.html#policy)

They suggest the following in iptables
```
# Employee rule
iptables -A FORWARD -i tun0 -s 10.8.0.0/24 -d 10.66.4.4 -j ACCEPT

# Sysadmin rule
iptables -A FORWARD -i tun0 -s 10.8.1.0/24 -d 10.66.4.0/24 -j ACCEPT

# Contractor rule
iptables -A FORWARD -i tun0 -s 10.8.2.0/24 -d 10.66.4.12 -j ACCEPT
```

```
# "dev tun" will create a routed IP tunnel,
# "dev tap" will create an ethernet tunnel.
# Use "dev tap0" if you are ethernet bridging
# and have precreated a tap0 virtual interface
# and bridged it with your ethernet interface.
# If you want to control access policies
# over the VPN, you must create firewall
# rules for the the TUN/TAP interface.
# On non-Windows systems, you can give
# an explicit unit number, such as tun0.
# On Windows, use "dev-node" for this.
# On most systems, the VPN will not function
# unless you partially or fully disable
# the firewall for the TUN/TAP interface.
;dev tap
dev tun0
```
I've been looking at #40
 
I'm assuming that tun0 should become docker0 as the network interface (but if it is does the dev directive in the server config need to become docker0)?. But to be able to implement it needs to be routed instead of bridged. Is the current docker implementation bridged? I'll have more follow up questions.

**Comment by kylemanna** [comment]
The tun0 is a special interface between the kernel's networking stack and the openvpn daemon.  Docker0 is typically a bridge of all the docker containers that are running with the default network config.

If you want to implement a policy within the container, you can safely ignore docker0 as from the container's perspective it doesn't exist.  You may need to do a more elaborate setup to avoid the NAT that docker does by default on the docker0 bridge.
