### ISSUE TITLE
SSL tunnel

### ISSUE THREAD

**Issue by kaihendry** [kylemanna/docker-openvpn#115]
Is there some option to establish a OpenVPN like a browser SSL connection as I think https://greycoder.com/openvpn-china/ describes? I hear nowadays China's Firewall can detect OpenVPN connections.

**Comment by kylemanna** [comment]
I can confirm firsthand that China's firewall shutsdown OpenVPN UDP connections.  The ExpressVPN folks appear to have a modified OpenVPN client+server that works around reasonably well with TCP connections.

On a side note, an OpenSSH tunnel works "ok" but suffers from the TCP in TCP tunnel problem.

**Comment by kaihendry** [comment]
Ok, I hope we can work towards easily deployable (docker run) VPN over SSL solution for dealing with the very real "Great Firewall of China" case. Was wondering if LetsEncrypt can help get the certs sorted quickly.

**Comment by kaihendry** [comment]
Was the issue addressed somehow or you just closed it since it's something you don't want to work on?

**Comment by kylemanna** [comment]
There was no update in over a month and I can't fix China.  You're welcome to contribute pull request.

**Comment by KevinColemanInc** [comment]
@kaihendry you make any headway on this or have any advice?

**Comment by kaihendry** [comment]
@KevinColemanInc Nope sorry.
