### ISSUE TITLE
Can't connect from linux command line client

### ISSUE THREAD

**Issue by mhornbech** [kylemanna/docker-openvpn#116]
I have tried connecting from the linux command line client using three different distributions (DigitalOcean droplets). In all cases the result is the same:

~]# openvpn --config client.ovpn 
Wed Mar 30 04:41:52 2016 OpenVPN 2.3.10 x86_64-redhat-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Jan  4 2016
Wed Mar 30 04:41:52 2016 library versions: OpenSSL 1.0.1e-fips 11 Feb 2013, LZO 2.06
Enter Private Key Password: ************
Wed Mar 30 04:42:02 2016 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Wed Mar 30 04:42:03 2016 Control Channel Authentication: tls-auth using INLINE static key file
Wed Mar 30 04:42:03 2016 UDPv4 link local: [undef]
Wed Mar 30 04:42:03 2016 UDPv4 link remote: [AF_INET]188.166.194.129:1194
Wed Mar 30 04:42:03 2016 [vpn.datasolvr.com] Peer Connection Initiated with [AF_INET]188.166.194.129:1194
Wed Mar 30 04:42:05 2016 TUN/TAP device tun0 opened
Wed Mar 30 04:42:05 2016 do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0
Wed Mar 30 04:42:05 2016 /usr/sbin/ip link set dev tun0 up mtu 1500
Wed Mar 30 04:42:05 2016 /usr/sbin/ip addr add dev tun0 local 192.168.255.6 peer 192.168.255.5

After this point the process hangs and the droplet becomes unresponsive and must be rebooted. I have checked the OpenVPN logs as in your documentation and they show no error. I can connect from Mac and Windows with Viscosity with no issues - the output to the server log is the same here as in the command line case.

**Comment by kylemanna** [comment]
The droplet could become unresponsive if you update the default route to use the VPN and your ssh session is then not routed over the VPN.  How are you testing exactly?

**Comment by mhornbech** [comment]
I was testing on a clean droplet with the openvpn client installed through apt-get/yum. I have now switched to an openvpn access server install instead - I found that I don't really have the skills to configure this stuff without proper UI and documentation.
