### ISSUE TITLE
openvpn.conf fragment 1400

### ISSUE THREAD

**Issue by rudijs** [kylemanna/docker-openvpn#117]
Hi,

I'm not sure why exactly but for my openvpn setups, both with and without docker, I always require `fragment 1400` in my openvpn.conf

While I've been figuring out how to get this all going I've been updating openvpn.conf manually and restarting the container.

For my use case I'd like ovpn_genconfig to support adding this openvpn.conf config.

I can go ahead and create a pull request for this no problem (use the -f flag option?).

Cheers.

**Comment by kylemanna** [comment]
Sounds like the MTU somewhere along your network connection requires the fragment option.

I'd definitely like a fragment option.  Can you add the option and a really unit test (see the `tests` directory)?  For the test it is simple as running the script and then checking the config file for the expected fragment option.  Goal is to prevent it from breaking as `ovpn_genconfig` gets fatter.

**Comment by rudijs** [comment]
Ok sure, I'd love to contribute and add this fragment option w/ test(s).

I'll go ahead and close this issue, then open a pull request later today or tomorrow.

Cheers.
