### ISSUE TITLE
Container Setup Iptables

### ISSUE THREAD

**Issue by rudijs** [kylemanna/docker-openvpn#118]
Hi,

I've found that after I've got everything going OK with the quickstart I also additionally need some iptables rules.

I want my VPN to NAT and Masquerade for the lan behind it.

It's an AWS instance that is already terminated, here's the openvpn.conf

```
server 10.8.0.0 255.255.0.0                                                                                                                                                   
verb 3                                                                                                                                                                        
key /etc/openvpn/pki/private/52.77.212.221.key                                                                                                                                
ca /etc/openvpn/pki/ca.crt                                                                                                                                                    
cert /etc/openvpn/pki/issued/52.77.212.221.crt                                                                                                                                
dh /etc/openvpn/pki/dh.pem                                                                                                                                                    
tls-auth /etc/openvpn/pki/ta.key                                                                                                                                              
key-direction 0                                                                                                                                                               
keepalive 10 60                                                                                                                                                               
persist-key                                                                                                                                                                   
persist-tun                                                                                                                                                                   

proto udp                                                                                                                                                                     
# Rely on Docker to do port mapping, internally always 1194                                                                                                                   
port 1194                                                                                                                                                                     
dev tun0                                                                                                                                                                      
status /tmp/openvpn-status.log                                                                                                                                                

user nobody                                                                                                                                                                   
group nogroup                                                                                                                                                                 
client-to-client                                                                                                                                                              
comp-lzo                                                                                                                                                                      
push dhcp-option DNS 8.8.8.8                                                                                                                                                  
push dhcp-option DNS 8.8.4.4                                                                                                                                                  
route 192.168.254.0 255.255.255.0                                                                                                                                             
push "route 10.0.1.0 255.255.255.0"                                                                                                                                           
push "route 10.0.2.0 255.255.255.0"                                                                                                                                           
fragment 1400  
```

So once it's all setup and working I need these rules added:

```
iptables -A FORWARD -i tun0 -o eth0 -s 10.8.0.0/16 -d 10.0.0.0/16 -m conntrack --ctstate NEW -j ACCEPT
iptables -t nat -A POSTROUTING -o eth0 -s 10.8.0.0/16 -j MASQUERADE
```

That's what works for me - I'd like to ask - does that make sense or am I off on the wrong track?

Thanks!

**Comment by kylemanna** [comment]
This is a new use case I hadn't considered.  It may make sense to have a list of additional iptables directives to try to load when the server starts-up.  Perhaps a file easily consumable by `iptables-restore` and preserved under `/etc/openvpn/iptables.rules` would suffice?

Thoughts?  Others?

**Comment by rudijs** [comment]
I'll add some more context to my use case senario.

This is for the very typical two-tier amazon VPC setup.

So there's a pubic subnet with a bastion server => 10.0.1.0/24 + 52.77.212.221 (public IP)

Then within the same AWS VPN is a private subnet with various servers (typical is database) => 10.0.2.0/24

The private subnet uses the bastion as it's NAT server for internet access.

OpenVPN, either docker or non-docker, runs on the bastion in the public subnet.

So for me as the developer/admin with OpenVPN running I can access public and private subnet directly:

Examples from my developer workstation

- ssh ubuntu@10.0.1.150
- ssh ubuntu@10.0.2.200

So in order for that to work with this docker-openvpn, the docker container needs iptables rules to enable the forward and masquerade to/from the container into the subnets.

**Comment by rudijs** [comment]
@kylemanna 

Using /etc/openvpn/iptables.rules make good sense and I think it's probably best practice as well.

ip_forward needs to be enabled also which the container inherits from the host machine.

So prior to launching docker-openvpn I enable this when the host if provisioned.

I'm using terraform from hashicorp, but any config management (chef, puppet etc) could do it as well.

    sudo sysctl -w net.ipv4.ip_forward=1

**Comment by firsttris** [comment]
Hello,

i also need to add iptables rules to make nat work.

i can add them manually inside the container using:

iptables -t nat -A POSTROUTING -o tun0 -j MASQUERADE
iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE

how can i make this rules persistent ?

regards
tristan

**Comment by rca** [comment]
Looks like this works out of the box with the latest image, is that correct?

```
kylemanna/openvpn   latest              4f029cd60b5b        3 days ago          12.86 MB
```

**Comment by kylemanna** [comment]
> Looks like this works out of the box with the latest image, is that correct?

I never got around to implementing it.

**Comment by rca** [comment]
Maybe I'm not understanding the issue ... let me explain what's working for me.

The VPN is setup at `192.168.255.0/24`.  The docker container is running on a machine on the `172.31.0.0/16` network.

I have setup openvpn to push the route `172.31.0.0 255.255.0.0` and once connected to the VPN I can SSH directly into any machine on that network.

Additionally, I push the route `172.20.0.0 255.255.0.0` and without any additional configuration it "just worked".

Please excuse if I mis-interpreted the issue.

Thanks for a great container!

**Comment by rca** [comment]
Maybe I'm not understanding the issue ... let me explain what's working for me.

The VPN is setup at `192.168.255.0/24`.  The docker container is running on a machine on the `172.31.0.0/16` network.

I have setup openvpn to push the route `172.31.0.0 255.255.0.0` and once connected to the VPN I can SSH directly into any machine on that network.

Additionally, I push the route `172.20.0.0 255.255.0.0` and without any additional configuration it "just worked".

Please excuse if I mis-interpreted the issue.

Thanks for a great container!

**Comment by arukaen** [comment]
I believe the issue that @rudijs is describing is the same one I am having. I have a VPC on AWS with two subnets (private and public). This container is running on an instance in the public space. I am attempting to use the vpn to be able to access my private subnet which I am unable to do at this time with the image. Additionally when I do connect the vpn server, I seem to loose all DNS routing.

``` sh

push "route 10.0.0.0 255.0.0.0"
push dhcp-option DNS 8.8.8.8
push dhcp-option DNS 10.99.0.1
push dhcp-option DOMAIN example.local

server 10.99.0.0 255.255.255.0

verb 3
key /etc/openvpn/pki/private/vpn.example.com.key
ca /etc/openvpn/pki/ca.crt
cert /etc/openvpn/pki/issued/vpn.example.com.crt
dh /etc/openvpn/pki/dh.pem
tls-auth /etc/openvpn/pki/ta.key
key-direction 0
keepalive 10 60
persist-key
persist-tun
push block-outside-dns

proto udp
# Rely on Docker to do port mapping, internally always 1194
port 1194
dev tun0
status /tmp/openvpn-status.log

user nobody
group nogroup
```
