### ISSUE TITLE
Can't connect to VPN with custom port

### ISSUE THREAD

**Issue by patrick-mota** [kylemanna/docker-openvpn#120]
When I run :
docker run --volumes-from $OVPN_DATA -d -p 443:1194/udp --cap-add=NET_ADMIN kylemanna/openvpn

I think my .ovpn file should have something like :
remote hostname 80 udp

Instead I got : 
remote hostname 1194 udp

I understand from the container perspective, you are internally mapped to 1194 so the .ovpn file is 1194 but this file will be used from another host so it should be 80 since we pass through docker ?

Maybe I'm missing something...
Can you help me?

**Comment by combatmonk** [comment]
The command for docker states that it will map the host 443 external to 1194/udp on the container.

**Comment by patrick-mota** [comment]
Yes that's ok but when you do :
docker run --volumes-from $OVPN_DATA --rm kylemanna/openvpn ovpn_getclient CLIENTNAME > CLIENTNAME.ovpn

the .ovpn use the port 1194 it should be fine if we used the standard port or -p 1194:1194 but if you use 80:1194 it will not work.

The goal is simply to use the VPN in a remote server using port 80 instead of 1194.

**Comment by kylemanna** [comment]
Pass port 80 (and the proto tcp vs udp) when you run genconfig.  The scripts store the port internally since there is no way to determine the external port mapping and if you change the `-p` option in a subsequent run it doesn't work.

**Comment by patrick-mota** [comment]
Big thanks kylemanna !
It was like you said I just did :  
docker run --volumes-from $OVPN_DATA --rm kylemanna/openvpn ovpn_genconfig -u tcp://VPN.SERVERNAME.COM

**Comment by kylemanna** [comment]
Glad to hear you got it working!

**Comment by vmsantos** [comment]
@patrick-mota so how did you pass the -p attribute? I'm having the same problem.

**Comment by saadismail** [comment]
@vmsantos It has been quite a lot of time since you asked, but just answering for future viewers.

It can be done by passing `-u tcp://VPN.SERVERNAME.COM:80` to `ovpn_genconfig` as documented here: https://github.com/kylemanna/docker-openvpn/blob/master/docs/tcp.md#using-tcp

**Comment by vmsantos** [comment]
Thanks!

Em sex, 25 de dez de 2020 08:36, Saad Ismail <notifications@github.com>
escreveu:
