### ISSUE TITLE
No mention of client connection in README

### ISSUE THREAD

**Issue by TheNotary** [kylemanna/docker-openvpn#121]
Thanks for sharing this!  I'm used to starting my openvpn sessions by creating a /etc/openvpn/name.conf file and doing `sudo service openvpn start`.  This failed horribly (emphasis on massive time sink) so I started googling and found an easier way for testing purposes:

```
# Below is the quickest way to test your VPN
$  sudo openvpn --config self.ovpn
```

Would you like a PR where I throw this tip into the readme somewhere elegantly or anything like that?

Also for debugging, would it be better to remove the `-d` switch in the command:

```
docker run --volumes-from $OVPN_DATA -d -p 1194:1194/udp --privileged -e DEBUG=1 kylemanna/openvpn
```

See #122 for general idea.

And thx again, you rock!

**Comment by kylemanna** [comment]
Merged your pull request, closing this issue.  If you have any more elaborate additions, be sure to consider adding them to the `docs` directory.
