### ISSUE TITLE
Websites using Https won't work on Azure

### ISSUE THREAD

**Issue by iboware** [kylemanna/docker-openvpn#124]
Hi,
I set up my VPN server on Azure(Ubuntu 16.04) as it is described in the guide. I can reach some websites like facebook. When I try to connect to google.com it will wait until the request timeout. I don't know why this happens. Can someone help me?

**Comment by ypid** [comment]
Can you check if you can reach google.com when you are connected to your VPN Server via SSH (with tools like `wget` and `lynx`). Maybe Azure is blocking something?

**Comment by iboware** [comment]
Actually I can connect but things like javascript files won't get loaded. I tried your suggestion, wget works.

**Comment by ypid** [comment]
@iboware Have you tried loading the JS files via `wget`?

**Comment by iboware** [comment]
@ypid yeah just tried. It works.

**Comment by iboware** [comment]
@ypid I think I have found the reason. I can't get connections over https. Is there any way to configure this?

**Comment by ypid** [comment]
Should work by default. But there can be many reasons why this does not work. You will need to debug this. Some keywords: Firewall, OCSP, remote server down, works via wget.

**Comment by iboware** [comment]
@ypid I actually tried this on digital ocean too. It works there on a Debian 8 VM. My Azure VM is also a Debian 8. It must be something specifically about Azure. I will try my best, but if someone has any idea please let me know.

**Comment by kylemanna** [comment]
Sounds like a problem with a firewall along the way blacklisting the subnet your running the server on.  This is unfortunately too common due to people running bots on DigitalOcean, EC2, Azure and others.
