### ISSUE TITLE
How to make OpenVPN failsave?

### ISSUE THREAD

**Issue by phlegx** [kylemanna/docker-openvpn#128]
Hi @kylemanna!

Thanks for this amazing image! It makes VPN really super super easy! :+1: 

I was wondering on how to make a (this docker) VPN failsafe? Is there some kind of openvpn cluster mechanism that one can use?

What I currently have in mind is to use 2 of your docker images vpn1.example.com and vpn2.example.com, which are exact copies of each other in terms of the IP configuration and the client certs, and make the clients aware of the two available vpn server alternatives.

The first connection of the clients will always go to vpn1.onlim.com (because of the order). In case vpn1.onlim.com machine goes down, in about 6 seconds (by setting keepalive to ```keepalive 1 2```) all client try to reconnect and see, that vpn1 has disappeared. Then they will all connect to vpn2 and all should be up and running again.

This is my current approach (not production tested of course). I'm open for any other better suggestions or solutions! 

thanks!

**Comment by meauses** [comment]
If you deploy 2 containers you can apply multiple servers into your client.conf and i believe you can even define loadbalancing. Or you can use AWS Route53 to do latency based routing for example and connect to the container closest/fastest.

**Comment by kylemanna** [comment]
@meauses has it.  Copy the configs and then use something to load balance or round-robin between them. I do believe that openvpn clients pick randomly from a list if the list of servers is given.
