### ISSUE TITLE
Best way to start on boot?

### ISSUE THREAD

**Issue by thesuperzapper** [kylemanna/docker-openvpn#129]
Hey, thanks for the awesome container! I was wondering what the best way to make it start on boot was.

**Comment by ypid** [comment]
Your issue is not directly related to this Docker image. Refer to https://stackoverflow.com/questions/30449313/how-do-i-make-a-docker-container-start-automatically-on-system-boot/30450350#30450350

**Comment by thesuperzapper** [comment]
Many thanks.
