### ISSUE TITLE
Can't setup static IP

### ISSUE THREAD

**Issue by phelpsiv** [kylemanna/docker-openvpn#133]
I'm attempting to setup a static IP following the instructions at: 
https://github.com/kylemanna/docker-openvpn/blob/master/docs/static-ips.md

I keep getting:
`tee: /etc/openvpn/ccd/CLIENT: No such file or directory`

I've gone as far as rebuilding the containers from the image.

Is there something I need to do to properly generate the ccd folder and client configurations? 
running `docker run  --volumes-from $OVPN_DATA --rm kylemanna/openvpn ovpn_genconfig` does not correct this issue.

**Comment by kylemanna** [comment]
`CLIENT` needs to be replaced with the name you gave to the client when adding the client.

**Comment by phelpsiv** [comment]
I'm using CLIENT here as a place holder, similar to your use of CLIENTNAME in your documentation. Sorry that wasn't clear about that.

**Comment by kylemanna** [comment]
Hmm, that's strange.  Does the ccd directory exist?

`docker run --volumes-from $OVPN_DATA --rm kylemanna/openvpn ls -ld /etc/openvpn/ccd`

May just need to do mkdir:

`docker run --volumes-from $OVPN_DATA --rm kylemanna/openvpn mkdir /etc/openvpn/ccd`

Sometime ago I think the `ccd` was automatically created, but now it only checks if it was created.

If the `mkdir` works, let me know and I'll update the docs!

**Comment by ghostbar** [comment]
Don't know if it has anything to do, but ovpn_copy_server_files does not copy ccd, in my case was giving issues. I manually copied ccd/* -> server/ccd/ and that fixed my issue. Of course, that should be added to the ovpn_copy_server_files script on L39 (https://github.com/kylemanna/docker-openvpn/blob/master/bin/ovpn_copy_server_files#L39)

**Comment by kylemanna** [comment]
@ghostbar the ccd directory wasn't copied correctly as you pointed out.  Commit https://github.com/kylemanna/docker-openvpn/commit/a17dfd7808ec232232265c9f394f090806e2e830 should have fixed that, can you confim that this fixes  your issue after the image finishes building and you do a `docker pull` ?

**Comment by ghostbar** [comment]
@kylemanna it did, thank you so much! :)
