### ISSUE TITLE
open tcp port

### ISSUE THREAD

**Issue by ram-argus** [kylemanna/docker-openvpn#134]
the remap with docker run -p doesn't work well with k8s.

can you please just add add an extra EXPOSE line in the Dockerfile?:
EXPOSE 1194/udp
_EXPOSE 1194/tcp_

also would be nice to be able to override the location of files, for use in kubernetes configmap & secrets...

**Comment by ram-argus** [comment]
I realized the tcp port was not open because of sever configuration, not because the missing expose. it might be nice to have both exported in any rate, but closing this issue as it does work as intended.

**Comment by kylemanna** [comment]
It's not exposed because it's not recommended to run OpenVPN or really any tunneling mechanism over TCP.  The goal is to encourage users to use UDP by default unless they have a real need.

**Comment by GetchaDEAGLE** [comment]
@kylemanna, would you be able to provide a source for that? The only thing I can gather is that using TCP will slow things down quite a bit but that's about it ([see this](http://vpnpick.com/using-openvpn-tcp-vs-udp-knowing-difference/)). Granted, using UDP means packets aren't guaranteed to be delivered. That might be a concern if working with important data.

**Comment by FernandoMiguel** [comment]
in our case use AWS Network Load Balancer, we can't use UDP.
so TCP would be a great option for us
