### ISSUE TITLE
This images does not seem to push the docker0 172.17.0.0/24 network to the client

### ISSUE THREAD

**Issue by 2devnull** [kylemanna/docker-openvpn#137]
As the title says, I expected to see the docker local network accessible to the client. The server I have this in does not have a private network so would like to reach all the other docker containers via the docker0 interface.

**Comment by kylemanna** [comment]
Did you enable `client-to-client` support?  By default OpenVPN itself only allows communication with the OpenVPN server by making small subnets for each connection.

Client to client support: https://github.com/kylemanna/docker-openvpn/blob/191cb45/bin/ovpn_genconfig#L44

**Comment by 2devnull** [comment]
I thought client-to-client is to enable the server side to reach the client connecting in vs. the default where the client can reach the server (your image) and not vice versa. 

In my case I am just trying to reach other networks on the server, don't want the server reaching the networks on the client side. I'm sure I'm missing something obvious here. Will try but really don't want the server side to access the client networks if that becomes a side affect.

**Comment by kylemanna** [comment]
Closing due to no updates in a few months.
