### ISSUE TITLE
Use data volume instead of data container?

### ISSUE THREAD

**Issue by lukas-schulze** [kylemanna/docker-openvpn#139]
Docker introduced data volume containers with version 1.9.
Is there any reason to use a data container instead of a volume?

Source: https://docs.docker.com/engine/userguide/containers/dockervolumes/#creating-and-mounting-a-data-volume-container

**Comment by kylemanna** [comment]
The data container is certainly a better approach.  The reason I haven't done it yet is that I haven't had the time to implement it and update the docs as well as I haven'ted figured out a smooth migration path for existing users.

**Comment by lukas-schulze** [comment]
Do you mean "data container" or "data volume"?
I currently use a data volume for the openvpn data and it seems to work like a charm.

Unfortunately I also do not know how to smoothly integrate it in (any) setup / update process

**Comment by kylemanna** [comment]
I mean "data volume container" as references by the link provided.  That feature didn't exist when I started this project.

**Comment by kylemanna** [comment]
Rolled this in to https://github.com/kylemanna/docker-openvpn/commit/379766fc5ecf3a1c8b6407163c437d0c77f218d4  

Let me know if there are any issues.
