### ISSUE TITLE
docker-openvpn/tests/openvpn_conf_options.test.sh has typo

### ISSUE THREAD

**Issue by hjnijlunsing** [kylemanna/docker-openvpn#144]
For file: docker-openvpn/tests/openvpn_conf_options.test.sh currently the OVPN_DATA is set in this line to:
- OVPN_DATA=opvn-data

My guess is that this is a typo and should be: ovpn-data
However to make it in sync with the other tests and not conflicting with the default ovpn-data of the readme my suggestion would be to change it to:

- OVPN_DATA=options-data

**Comment by kylemanna** [comment]
Good catch.  Good to see someone reading the tests. :sunglasses:

**Comment by hjnijlunsing** [comment]
Thanks!  I ported your project today to arm in order to run it on my pi and cubox, the test suite proved to be a good way of testing the end result!
