### ISSUE TITLE
crl.pem doesn't work

### ISSUE THREAD

**Issue by stefanfritsch** [kylemanna/docker-openvpn#145]
Hi,

I'm not sure whether this is a bug or a case of pebkac but I'm trying to revoke certificates with openvpn.

I do this with

    easyrsa revoke <name>
    easyrsa gen-crl

to create the crl.pem. This looks ok, i.e. it results in a success message. 

I then restart the container and it now launches

    'openvpn --config /etc/openvpn/openvpn.conf --crl-verify /etc/openvpn/crl.pem '

I.e. it has found the crl.pem and both crl.pem (in /etc/openvpn and pki) are 0644 and should be readable for `nobody`. If I check the file with

    openssl crl -in /etc/openvpn/crl.pem -text

it also lists the correct certificate as revoked. 

But a login attempt fails with the following error log:

    Mon Jul 11 09:04:19 2016 us=871661 <ip>:62292 Incoming Ciphertext -> TLS
    Mon Jul 11 09:04:19 2016 us=871901 <ip>:62292 CRL: cannot read: /etc/openvpn/crl.pem
    Mon Jul 11 09:04:19 2016 us=871920 <ip>:62292 SSL alert (write): fatal: certificate unknown
    Mon Jul 11 09:04:19 2016 us=871965 <ip>:62292 TLS_ERROR: BIO read tls_read_plaintext error: error:14089086:SSL routines:ssl3_get_client_certificate:certificate verify failed
    Mon Jul 11 09:04:19 2016 us=871977 <ip>:62292 TLS Error: TLS object -> incoming plaintext read error
    Mon Jul 11 09:04:19 2016 us=871988 <ip>:62292 TLS Error: TLS handshake failed

Unfortunately I don't know whether this means that crl.pem is not readable and *therefore* the certificate  unknown or whether crl.pem is unreadable *because* the certificate is unknown and what either of those errors would actually mean.

Based on a different issue the two revokation steps look correct. Is this a bug?

Thanks for any suggestions
Stefan

**Comment by kylemanna** [comment]
This is related to #101 that hasn't been resolved just yet.  Can you confirm that restarting the openvpn server works as expected?

**Comment by stefanfritsch** [comment]
Unfortunately not. It's the same error. The original error message in the log seems to be the above. Also, I can login (with the same certificate) if I delete crl.pem so it has to be related to crl.pem.

`DEBUG=1` doesn't show any errors (I can post the output nevertheless if it helps).

**Comment by stefanfritsch** [comment]
Nuking the config and re-creating everything from scratch worked. It might have been a problem with different versions of the image or more specifically with changes in the config(?)

Seems like I'll have to exchange all the certificates. :(

Thanks for a great image.
