### ISSUE TITLE
How can I set the timezone probably.

### ISSUE THREAD

**Issue by BauchBeinePoe** [kylemanna/docker-openvpn#150]
Hi,

I have a problem setting the timezone.

The /etc/TZ contains UTC but chaning this is not helping. When I export TZ=EST (for example) it works but it is not reflected in the docker logs. And the solutions is not permanent.

**Comment by kylemanna** [comment]
What's the end goal?  Our you trying to set the timezone on the host?

**Comment by bauson-com** [comment]
I just encountered this issue, and it will be good to have a way to pass the Timezone during run time, I tried adding:
`-e TZ=Europe/London` and it didn't work.

**Comment by ycllwl** [comment]
#Find the openvpn container ID
docker ps -a

#install tzdata
docker exec -it xxxxxxxx apk add tzdata

#Link to the timezone file. Note that here I have set it to China, so please do not copy it directly.
docker exec -it xxxxxxxx ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

#authentication settings
docker exec -it xxxxxxxx date
