### ISSUE TITLE
Ubuntu 16.04 with systemctl

### ISSUE THREAD

**Issue by KevinColemanInc** [kylemanna/docker-openvpn#151]
I can't figure out how to get this to run on ubuntu 16.04 with systemctl.

running: `/usr/bin/docker run --privileged=true --volumes-from ovpn-data --rm -p 1194:1194/udp kylemanna/openvpn`

works fine and I see it when I run `docker ps`, but if I wrap it in `/etc/systemd/system/docker-vpn.service`

    [Unit]
    Description="Docker container for OpenVPN server"
    After=docker.service
    Requires=docker.service

    [Service]
    User=root
    TimeoutStartSec=0
    ExecStart=/usr/bin/docker run --privileged=true --volumes-from ovpn-data --rm -p 1194:1194/udp kylemanna/openvpn

    [Install]
    WantedBy=multi-user.target

I nothing happens.

    Aug 07 19:46:12 docker-sf systemd[1]: Started "Docker container for OpenVPN server"

is all I see in the `journalctl` logs.

any advice?

**Comment by KevinColemanInc** [comment]
for future people:

Don't name your ctl service `docker.service` call it something else.  I think `docker.service` needs to be something else.

**Comment by kylemanna** [comment]
`docker.service` is often times the Docker engine itself.
