### ISSUE TITLE
How to turn off tunnelling?

### ISSUE THREAD

**Issue by bartoszhernas** [kylemanna/docker-openvpn#152]
Hi guys,

is there an easy way to turn off tunelling the traffic?

I would like to have VPN set up that it does not tunell my computer traffic but let me access other computer in the network (and also jenkins that is hosted on same machine and that is binded to VPN's IP address).

Thank a lot for help!

**Comment by kylemanna** [comment]
Look at disabling NAT routing:

https://github.com/kylemanna/docker-openvpn/blob/master/bin/ovpn_genconfig#L43

**Comment by jffz** [comment]
Hello, just wanted to ask the same question but the link point on a blank line :/
