### ISSUE TITLE
google-authenticator is no longer in alpine :(

### ISSUE THREAD

**Issue by jfrazelle** [kylemanna/docker-openvpn#153]
https://pkgs.alpinelinux.org/packages?name=google-authenticator&branch=&repo=&arch=&maintainer=

building the dockerfile fails 
```
Step 1 : FROM alpine:3.4
 ---> 4e38e38c8ce0
Step 2 : MAINTAINER Kyle Manna <kyle@kylemanna.com>
 ---> Using cache
 ---> 8e0b71c3be82
Step 3 : RUN echo "http://dl-4.alpinelinux.org/alpine/edge/community/" >> /etc/apk/repositories &&     echo "http://dl-4.alpinelinux.org/alpine/edge/testing/" >> /etc/apk/repositories &&     apk add --update openvpn iptables bash easy-rsa openvpn-auth-pam google-authenticator pamtester &&     ln -s /usr/share/easy-rsa/easyrsa /usr/local/bin &&     rm -rf /tmp/* /var/tmp/* /var/cache/apk/*
 ---> Running in 7fc1d7565bb5
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
fetch http://dl-4.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
fetch http://dl-4.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  google-authenticator (missing):
    required by: world[google-authenticator]
Removing intermediate container 7fc1d7565bb5
The command '/bin/sh -c echo "http://dl-4.alpinelinux.org/alpine/edge/community/" >> /etc/apk/repositories &&     echo "http://dl-4.alpinelinux.org/alpine/edge/testing/" >> /etc/apk/repositories &&     apk add --update openvpn iptables bash easy-rsa openvpn-auth-pam google-authenticator pamtester &&     ln -s /usr/share/easy-rsa/easyrsa /usr/local/bin &&     rm -rf /tmp/* /var/tmp/* /var/cache/apk/*' returned a non-zero code: 1
Build step 'Execute shell' marked build as failure
```

**Comment by kylemanna** [comment]
Looks like it was deleted on August 25th due to being unmaintained and not updated:

> testing/[multiple]: move unmaintained packages
> This moves all packages from testing to unmaintained which have not been
> updated for atleast 6 months. If you are affected by this commit please follow
> this proceddure:
> 
> * make sure your packages build on all architectures
> * move your pacakge(s) back to testing
> * if you want to keep this package and can maintain it (or find somebody to
>   maintain it for you) for a minimum of 6 months ask it to be moved to community


Github: https://github.com/alpinelinux/aports/commit/b6af1e02efe594039707cd882517663d5370f375
[AlpineLinux cgit](http://git.alpinelinux.org/cgit/aports/commit/?id=b6af1e02efe594039707cd882517663d5370f375)

@jfrazelle Are you actively using google-authententicator? I'm trying to determine the impact of removing google-authentiactor (as it breaks the build) until someone picks up and maintains the package.

**Comment by compressed** [comment]
I am using google-authenticator in my use case. I don't have any experience with maintaining alpine packages though...

**Comment by fabn** [comment]
I'll try to resubmit the package in alpine as soon as I can.

@kylemanna meanwhile if you want to fix the build you can make a branch from current master to work with and temporarily disable google authenticator in master branch.

**Comment by kylemanna** [comment]
@fabn I'll try to avoid rebuilding it hoping you can get it resubmitted before a rebuild is needed.  OpenVPN 2.3.11 is in the current image and 2.3.12 came out a few days ago.

Pushing a version of the image without google-authenticator will surely break some deployments (such as @compressed's install).

Alternatively we could build google-authenticator package in this image.

**Comment by kylemanna** [comment]
@fabn I've hijacked your APKBUILD for Alpine and build it manually for now.  If you want to maintain the upstream package, let me know and we can use that.

Please take a look @ the kylemanna/openvpn:dev  image and let me know if you see any problems.

**Comment by kylemanna** [comment]
The unit tests seems to have passed @ https://travis-ci.org/kylemanna/docker-openvpn/builds/156577940

**Comment by fabn** [comment]
> @fabn I've hijacked your APKBUILD for Alpine and build it manually for now on the dev branch. If you want to maintain the upstream package, let me know and we can use that.

Good approach, I tried to do that before submitting package in alpine linux and I failed the cleanup phase. I saw that with your approach the image size is still 5MB so it might be a good approach to not depend on package being present in the alpine linux repositories.
 
> Please take a look @ the kylemanna/openvpn:dev image and let me know if you see any problems. Otherwise I'll merge it sometime this week.

I don't see any immediate issue, so if you agree branch can be merged. In any case I'll resubmit package to alpine repositories and see what they will do.

**Comment by fabn** [comment]
Created a PR to reintroduce google-authenticator in alpine, see https://github.com/alpinelinux/aports/pull/256

**Comment by fabn** [comment]
PR has been merged so package should reappear in repository soon.

**Comment by jfrazelle** [comment]
It works now! OMG you all are the best :)

**Comment by kylemanna** [comment]
Thanks @fabn !
