### ISSUE TITLE
Add setting of custom key length

### ISSUE THREAD

**Issue by philipgrafat** [kylemanna/docker-openvpn#154]
There has to be an option when running ovpn_genconfig to set a custom RSA key length. The use of this project is very simple, but without the option of having 4096 bit keys, I had to do a lot of extra work.

**Comment by kylemanna** [comment]
Have you tried using the `EASYRSA_KEY_SIZE` environment variable?  It appears that the *easyrsa* code uses that.  Passing in the [command line argument just sets and environment variable](https://github.com/OpenVPN/easy-rsa/blob/fb4d8d8/easyrsa3/easyrsa#L1102-L1103).

Should be able to do `docker run ... -e EASYRSA_KEY_SIZE=4096 ... kylemanna/openvpn ...`

**Comment by philipgrafat** [comment]
Unfortunately, your solution didn't quite work. After some fiddling, I found out adding 
```declare -x EASYRSA_KEY_SIZE=4096``` to the ovpn_env.sh file did the work 😃

**Comment by kylemanna** [comment]
Glad to hear you got it working.

> Unfortunately, your solution didn't quite work.

Curious about this as I just gave it a shot myself and it worked:

    ~ ❯❯❯ docker run -e EASYRSA_KEY_SIZE=4096 -v $OVPN_DATA:/etc/openvpn --rm -it kylemanna/openvpn ovpn_initpki                                                                   ⏎

    init-pki complete; you may now create a CA or requests.
    Your newly created PKI dir is: /etc/openvpn/pki

    Generating a 4096 bit RSA private key
    ..............................................................................................................++
    .............................................................................................................................................................++
    writing new private key to '/etc/openvpn/pki/private/ca.key.XXXXDODGEE'
    Enter PEM pass phrase:
    Verifying - Enter PEM pass phrase:
    -----
    You are about to be asked to enter information that will be incorporated
    into your certificate request.
    What you are about to enter is what is called a Distinguished Name or a DN.
    There are quite a few fields but you can leave some blank
    For some fields there will be a default value,
    If you enter '.', the field will be left blank.
    -----
    Common Name (eg: your user, host, or server name) [Easy-RSA CA]:

    CA creation complete and you may now import and sign cert requests.
    Your new CA certificate file for publishing is at:
    /etc/openvpn/pki/ca.crt

    Generating DH parameters, 4096 bit long safe prime, generator 2
    This is going to take a long time
    ...
    DH parameters of size 4096 created at /etc/openvpn/pki/dh.pem

    Generating a 4096 bit RSA private key
    ........................++
    .................................................................................................................................................................................
    ...........................................................................++
    writing new private key to '/etc/openvpn/pki/private/localhost.key.XXXXLHaLLm'
    -----
    Using configuration from /usr/share/easy-rsa/openssl-1.0.cnf
    Enter pass phrase for /etc/openvpn/pki/private/ca.key:
    Check that the request matches the signature
    Signature ok
    The Subject's Distinguished Name is as follows
    commonName            :ASN.1 12:'localhost'
    Certificate is to be certified until Sep  1 22:29:10 2026 GMT (3650 days)

    Write out database with 1 new entries
    Data Base Updated

and then again for the client certificate generation:

    ~ ❯❯❯ docker run  -e EASYRSA_KEY_SIZE=4096 -v $OVPN_DATA:/etc/openvpn --rm -it kylemanna/openvpn easyrsa build-client-full CLIENTNAME nopass
    Generating a 4096 bit RSA private key
    ..............................................................................................++
    .........................................................................................................................................++
    writing new private key to '/etc/openvpn/pki/private/CLIENTNAME.key.XXXXeDPFGh'
    -----
    Using configuration from /usr/share/easy-rsa/openssl-1.0.cnf
    Enter pass phrase for /etc/openvpn/pki/private/ca.key:
    Check that the request matches the signature
    Signature ok
    The Subject's Distinguished Name is as follows
    commonName            :ASN.1 12:'CLIENTNAME'
    Certificate is to be certified until Sep  1 23:14:49 2026 GMT (3650 days)

    Write out database with 1 new entries
    Data Base Updated

**Comment by kylemanna** [comment]
Actually looking at it more, with your modification to `ovpn_env.sh` it's still generating the 2048 client keys, correct?  Passing the environment variable in should work in all cases, admittedly clumsy.

**Comment by kylemanna** [comment]
Assuming the `-e` magic works, the best way to make that sane might be to adopt `docker-compose` where the runtime environment variables can be defined in the `docker-compose.yml` file.

**Comment by philipgrafat** [comment]
No, I think you understood something wrong :)The addition to the ```ovpn_env.sh``` works very well. Mystically, adding the -e option didn't work for me before, but now does. I think the best way is this:

```bash
echo "declare -x EASYRSA_KEY_SIZE=4096" >> ovpn_env.sh
```
