### ISSUE TITLE
[QUESTION] slow connection

### ISSUE THREAD

**Issue by Lerentis** [kylemanna/docker-openvpn#158]
Hello there.
I just deployed this beautiful docker container on my server, and everything works fine, but i can't seem to get a fast connection. is there something i'm missing? I followed the description in the readme section.

if I download a file on my PC, that is connected over openvpn to my server the maximum i can get is this:
```
wget -O /dev/null http://cachefly.cachefly.net/100mb.test
--2016-09-14 17:50:33--  http://cachefly.cachefly.net/100mb.test
Resolving cachefly.cachefly.net (cachefly.cachefly.net)... 205.234.175.175
Connecting to cachefly.cachefly.net (cachefly.cachefly.net)|205.234.175.175|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 104857600 (100M) [application/octet-stream]
Saving to: ‘/dev/null’

/dev/null              100%[==========================>] 100,00M   608KB/s    in 2m 44s  

2016-09-14 17:53:17 (623 KB/s) - ‘/dev/null’ saved [104857600/104857600]
```

but i KNOW that my server has a better connection than that and the cpu usage is rather low as well

```
./speedtest-cli 
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Testing from Hetzner (213.133.111.170)...
Selecting best server based on latency...
Hosted by TempleServers (Nuremberg) [1.11 km]: 5.781 ms
Testing download speed........................................
Download: 609.81 Mbit/s
Testing upload speed..................................................
Upload: 256.94 Mbit/s
```

what am i missing or what can i do to tweak this?

**Comment by kylemanna** [comment]
Something seems very wrong.  I know that a single Digital Ocean droplet can get close to 100Mb/s without any tweaking on this container.  Perhaps there is something strange like a small MTU calling fragmentation?

**Comment by Lerentis** [comment]
I think it's my ISP... tried it on some different networks and got full speed there, so no server issue. 
Last guess: are there any known issues if i only have an ipv6 address and the server is ipv4?

**Comment by kylemanna** [comment]
> Last guess: are there any known issues if i only have an ipv6 address and the server is ipv4?

IPv4 networks and IPv6 networks are completely different, so they never connect directly.

**Comment by egalpin** [comment]
I'm having a similar issue actually.  My VPS has 2 CPU, 1024MB RAM, and "gigabit" internet connect.  Is my local upload speed (~30Mbps) the limiting factor?

Here are my various speed test results:

On VPS (with dockerized openvpn running)
```
$ ./speedtest-cli --simple
Ping: 4.092 ms
Download: 240.55 Mbit/s
Upload: 188.64 Mbit/s
```

On local machine, no VPN connection
```
$ ./speedtest-cli --simple
Ping: 12.559 ms
Download: 121.19 Mbit/s
Upload: 31.81 Mbit/s
```

On local machine, connected to VPN
```
$ ./speedtest-cli --simple
Ping: 19.882 ms
Download: 23.22 Mbit/s
Upload: 25.62 Mbit/s
```

**Comment by kylemanna** [comment]
> I'm having a similar issue actually. My VPS has 2 CPU, 1024MB RAM, and "gigabit" internet connect. Is my local upload speed (~30Mbps) the limiting factor?

No, something odd is going on there.  Typically you'll be limited by the CPU on the VPS (run top or similar and see if the openvpn daemon is maxing out a CPU) and the network connection.  Based on your speed tests, you should be able to get 150 Mb/s assuming the link is sufficiently low latency.

**Comment by egalpin** [comment]
From reading your docs and the like, I though CPU might be the bottleneck.  I've tried running htop on the VPS while connected to VPN and running a speedtest/long-running download locally.   The CPU usage tends to stay around 50% on one core only.

Any ideas? Anything further to test to help narrow down the issue?  Thanks for your great work by the way :-)

**Comment by Lerentis** [comment]
Done some testing on different machines in the pase few days. I can confirm that my slow connection is due to a bad ipv4 fallback by my ISP. Sadly they are not willing to fix this :<

@kylemanna should I close this issue or should I leave it open as @egalpin has a similar problem?

**Comment by kylemanna** [comment]
@egalpin it's basic OpenVPN performance troubleshooting at that point.  There are tweaks that can be done with ciphers block sizes, and mtus and what not to attempt to improve performance.  If you wanted to do some research and tests and find a better then default combination we can consider merging it.
