### ISSUE TITLE
Routing issues on the static IPs range

### ISSUE THREAD

**Issue by ghostbar** [kylemanna/docker-openvpn#159]
I generated my VPN like this:

```
docker-compose run --rm openvpn ovpn_genconfig -u udp://vpn.domain.tld -s 10.8.1.0/24 -r 10.8.2.0/24 -z -N -d -c
```

So: only local network, don't redirect to the internet. As you can see, I was expecting to use 10.8.2.0/24 as the static range and 10.8.1.0/24 for the dynamic IPs.

I put on `ccd/client0.domain.tld` the `ifconfig-push 10.8.2.10 10.8.2.1`, and on `ccd/client1.domain.tld` the `ifconfig-push 10.8.2.11 10.8.2.1`. When I tried to ping between them I got timeout. Tried changing `10.8.2.1` for `255.255.255.0` and didn't work neither.

I made it on ccd dir `ifconfig-push 10.8.1.10 255.255.255.0` and `ifconfig-push 10.8.1.11 255.255.255.0` and now they do communicate between them.

What am I doing wrong? What's missing? I would like to use `10.8.2.0/24` range instead of the same dynamic.

**Comment by kylemanna** [comment]
Why are you doing `ifconfig-push 10.8.2.11 10.8.2.1` and `ifconfig-push 10.8.2.10 10.8.2.1`?  The second IP address should be the VPN server's unique IP for that subnet.

For example I have:

     ccd/client1: ifconfig-push 192.168.254.1 192.168.254.2
     ccd/client2: ifconfig-push 192.168.254.5 192.168.254.6

Each subnet should be a /30 according to the [docs](https://openvpn.net/index.php/open-source/documentation/howto.html), the pairs are the following:

```
[  1,  2] [  5,  6] [  9, 10] [ 13, 14] [ 17, 18]
[ 21, 22] [ 25, 26] [ 29, 30] [ 33, 34] [ 37, 38]
[ 41, 42] [ 45, 46] [ 49, 50] [ 53, 54] [ 57, 58]
[ 61, 62] [ 65, 66] [ 69, 70] [ 73, 74] [ 77, 78]
[ 81, 82] [ 85, 86] [ 89, 90] [ 93, 94] [ 97, 98]
[101,102] [105,106] [109,110] [113,114] [117,118]
[121,122] [125,126] [129,130] [133,134] [137,138]
[141,142] [145,146] [149,150] [153,154] [157,158]
[161,162] [165,166] [169,170] [173,174] [177,178]
[181,182] [185,186] [189,190] [193,194] [197,198]
[201,202] [205,206] [209,210] [213,214] [217,218]
[221,222] [225,226] [229,230] [233,234] [237,238]
[241,242] [245,246] [249,250] [253,254]
```

**Comment by ghostbar** [comment]
Oops, my bad. Didn't read that part of the docs.

**Comment by kylemanna** [comment]
Cool, let me know if there is anything to add to the docs to enhance it.
