### ISSUE TITLE
Failed to build the CA

### ISSUE THREAD

**Issue by pykiss** [kylemanna/docker-openvpn#16]
Enter PEM pass phrase:
139885230831248:error:28069065:lib(40):UI_set_result:result too small:ui_lib.c:869:You must type in 4 to 1024 characters
139885230831248:error:0906406D:PEM routines:PEM_def_callback:problems getting password:pem_lib.c:111:
139885230831248:error:0907E06F:PEM routines:DO_PK8PKEY:read key:pem_pk8.c:130:

Easy-RSA error:

Failed to build the CA
-----------------------------

I had to do:

    docker run --volumes-from $OVPN_DATA --rm -it kylemanna/openvpn bash
    ovpn_initpki

And write a PEM pass phrase

**Comment by kylemanna** [comment]
No additional updates to go off, assuming issue is resolved.  I can't reproduce.

**Comment by Alives** [comment]
I'm seeing this now with Docker version 1.9.1, build a34a1d5 (Ubuntu Xenial).  Following the commands off the readme.md in this repo, using kylemanna/openvpn:latest ed1b60e06a95

**Comment by alexey-sh** [comment]
```
sudo   docker run -v $OVPN_DATA:/etc/openvpn --rm -it kylemanna/openvpn ovpn_initpki


WARNING!!!

You are about to remove the EASYRSA_PKI at: /etc/openvpn/pki
and initialize a fresh PKI here.

Type the word 'yes' to continue, or any other input to abort.
  Confirm removal: yes

init-pki complete; you may now create a CA or requests.
Your newly created PKI dir is: /etc/openvpn/pki

Generating a 2048 bit RSA private key
.......................................................+++
...........................................+++
writing new private key to '/etc/openvpn/pki/private/ca.key.XXXXeoMldp'
Enter PEM pass phrase:
139957450763148:error:28069065:lib(40):UI_set_result:result too small:ui_lib.c:831:You must type in 4 to 1023 characters
139957450763148:error:0906406D:PEM routines:PEM_def_callback:problems getting password:pem_lib.c:116:
139957450763148:error:0907E06F:PEM routines:DO_PK8PKEY:read key:pem_pk8.c:130:

Easy-RSA error:

Failed to build the CA
```

**Comment by MatthewVance** [comment]
It looks like the password didn't meet the requirements.

**Comment by alexey-sh** [comment]
@MatthewVance Yes, thanks for the note.
