### ISSUE TITLE
Nat access without ip forwarding

### ISSUE THREAD

**Issue by jffz** [kylemanna/docker-openvpn#164]
I'm looking to use openvpn to join a remote network without using ip forwarding.

I triied to launch my container with following commands:
````bash
docker run -v $OVPN_DATA:/etc/openvpn --rm kylemanna/openvpn ovpn_genconfig -u udp://my.server.com -N -d -c
````

The NAT works, i can access the remote network but the ip is still forwarded. I thought the -d flag would have deleted it. 
Any idea ?

**Comment by kylemanna** [comment]
It's very likely your openvpn client is doing this for you and you need to disable it.  What network client are you using?  Also, can you share your config with relevant IPs/keys removed?
