### ISSUE TITLE
How to delete a client?

### ISSUE THREAD

**Issue by alyuan** [kylemanna/docker-openvpn#165]
Hi Kylemanna
   Many sorry for disturbing. I have one question about this project. I created several ovpn files which contains key and certificate. If i want to make this client invalid, what operation can make this? I tried to delete the related crt , key files in volume container, but this client still can access the openvpn server.  

Many thanks for your kindly help.

**Comment by alyuan** [comment]
sorry for thi issue. easyrsa has revoke command to make ckient invakid. i first deleted all the client soecific ca and  key files , then use easyrsa revoke command ,so this faiked. now i got the answer.sorry again.

**Comment by andreydruz** [comment]
docker run -v $OVPN_DATA:/etc/openvpn --log-driver=none --rm -it kylemanna/openvpn easyrsa revoke CLIENTNAME
