### ISSUE TITLE
Disable internet traffic through OpenVPN server

### ISSUE THREAD

**Issue by ananthmv** [kylemanna/docker-openvpn#171]
Hi, 

We have deployed a openvpn docker in AWS and configured to reach intance inside VPC. However, all the client's connection is establishing internet routing through OpenVPN server. 

Is there a way to **disable** it?

**Comment by vielmetti** [comment]
Are you asking about a "split tunnel", where only a few routes are sent through the OpenVPN connection and the "default" route goes without a tunnel?

**Comment by ananthmv** [comment]
@vielmetti yes, almost! I want to sent all the aws ec2 instance traffic through VPN and avoid internet request going to VPN.

Will removing `redirect-gateway def1` from client config would work?

**Comment by vielmetti** [comment]
Take a look at #51 and #82 for some previous discussion.

**Comment by ananthmv** [comment]
@vielmetti [Split tunnels](https://github.com/kylemanna/docker-openvpn/blob/master/docs/faqs.md#how-do-i-set-up-a-split-tunnel) solves the issue. thanks!

**Comment by vielmetti** [comment]
Glad it worked!

**Comment by silju001** [comment]
> @vielmetti [Split tunnels](https://github.com/kylemanna/docker-openvpn/blob/master/docs/faqs.md#how-do-i-set-up-a-split-tunnel) solves the issue. thanks!

Hai Bro,

Could you provide the configuration file settings, i dont know the configuration for the split tunnel settings.
