### ISSUE TITLE
Allow multiple openvpn instances using same /etc/openvpn

### ISSUE THREAD

**Issue by mikn** [kylemanna/docker-openvpn#179]
Currently the blocker for this would be that ovpn_run has openvpn.conf hardcoded in the start call, as it seems? :)

**Comment by kylemanna** [comment]
Shouldn't be the case.  If you pass in `--config myother.conf` it should work fine.

Try:

    docker run --cap-add=NET_ADMIN kylemanna/openvpn ovpn_run --config myother.conf

**Comment by mikn** [comment]
Oh, wow. Proves how little I know! Thank you. :)
