### ISSUE TITLE
Enhancement: Make configuration scriptable

### ISSUE THREAD

**Issue by pschiffe** [kylemanna/docker-openvpn#181]
I'm using ansible to manage my docker containers, and I would like to have fully automated setup of this container. Currently, I have problem with `ovpn_initpki` step, which requires entering password. Now, I know I can use the `nopass` option, but I really don't want to do that. I checked easyrsa script and didn't find any workable solution, but that script is using openssl to generate keys and certs, and there is plenty of options how to automate openssl, for example: http://stackoverflow.com/a/4300425/6740530

Do you have any idea how to solve this directly in this image, or do we have to fix this in easyrsa script first?

**Comment by kylemanna** [comment]
You could execute the same steps as ovpn_initpki manually in your ansible script and then volume mount or transfer the PKI keys and certs into the container.

**Comment by pschiffe** [comment]
Well, the issue is with the `easyrsa build-ca $nopass` command, which I don't know how to automate, so I will have to execute the same steps as in `ovpn_initpki` and `easyrsa build-ca`, which is kind of inconvenient, even though `easyrsa build-ca` is only about one command (but there is additional logic):
```
"$EASYRSA_OPENSSL" req -utf8 -new -newkey $EASYRSA_ALGO:"$EASYRSA_ALGO_PARAMS" \
-config "$EASYRSA_SSL_CONF" -keyout "$out_key_tmp" -out "$out_file_tmp" $opts
```

I see issues about automation in easy-rsa repo:
https://github.com/OpenVPN/easy-rsa/issues/101
https://github.com/OpenVPN/easy-rsa/issues/103

However, that repo seems rather inactive nowadays :-(

**Comment by kylemanna** [comment]
EasyRSA may be the wrong tool for your job.  EasyRSA was designed to allow simple PKI certificate generation.  When you get in to special cases like yours, it almost certainly won't fit.  Adding features to PKI to support corner cases adds bloat and distracts from the original purpose.

That said, I'd encourage you to just run the openssl scripts directly for now.

**Comment by kylemanna** [comment]
EasyRSA is only for easy setups.  More advanced setups using Ansible or similar tools should use the `openssl` tools directly.

**Comment by pschiffe** [comment]
Thanks for your reply. Although I understand what you mean, I don't agree. It's significantly easier to update easyrsa to enable automation (and there are issues and PRs for that) than recreate all the easyrsa in some config management like ansible or others.

Anyway, I've created my image built on top of yours with simple [patch](https://github.com/pschiffe/docker-openvpn/blob/master/cakey.patch) which enables me to supply the ca key via env var, so it's possible to deploy your image without user interaction.

Thanks for your hard work on this image!
