### ISSUE TITLE
TLS soft reset causes connection to fail

### ISSUE THREAD

**Issue by lhopki01** [kylemanna/docker-openvpn#185]
When using 2 factor authentication every hour my connection stops because the TLS renegotiation.  According to this website:
https://forums.openvpn.net/viewtopic.php?t=8200
Openvpn requires the password to be resent when TLS is renegotiated which can't happen automatically with a one time password.

I've set the option reneg-sec <N> as an extra option in the server.conf but I think it needs to be set on both the client and the server config as the lower of the two is used.  I can't see how I can generate this automatically in the client config.

**Comment by kylemanna** [comment]
Have you tried manually adding it to the client configuration to see if that fixes it?

**Comment by lhopki01** [comment]
@kylemanna Adding reneg-sec to the client config manually works but if 2f is enabled it seems to make sense for this to automatically be added to the client config when it is generated otherwise everyone with 2f config will have their connection reset every hour.

**Comment by cmoad** [comment]
Agree with @lhopki01 based on my experience. I've had a Chef-based setup for a long time that has worked with `reneg-sec 0` for a long time. This prevents the 2FA connection from ever getting reset.
