### ISSUE TITLE
How to add security to my .conf file ? Or set password to it? 

### ISSUE THREAD

**Issue by kanlidy** [kylemanna/docker-openvpn#186]
Command to create a client config:

    docker run -v $OVPN_DATA:/etc/openvpn --rm -it kylemanna/openvpn easyrsa build-client-full UserName nopass

But, how to generate a password to the client conf? A key or pkcs12 file?

When I click on 'change password' on my client, I got this:

![image](https://cloud.githubusercontent.com/assets/5557262/21447650/ca770d74-c912-11e6-9912-3f8c4624e048.png)

**Comment by jasonkeithscott** [comment]
I haven't had time to go through all the wrapper scripts in this image. So the following will work, but there may be an easier way that's not clearly documented.

The [easyrsa docs](https://github.com/OpenVPN/easy-rsa/blob/master/README.quickstart.md) are somewhat helpful... somewhat. You can set a password for an existing private key generated with `build-client-full ...`. This password encrypts only the private key. Assuming your existing config file username was jscott, you can do the following.

```
sudo docker run -v $OVPN_DATA:/etc/openvpn --rm -it kylemanna/openvpn easyrsa set-rsa-pass jscott

If the key is currently encrypted you must supply the decryption passphrase.
You will then enter a new PEM passphrase for this key.

writing RSA key
Enter PEM pass phrase: **********
Verifying - Enter PEM pass phrase: **********

Key passphrase successfully changed
```

Do the `ovpn_getclient ....` part again and you will have an .ovpn config with a password. Yay.

Should you want to be able to change the password from the client side you need to pull the key out of the .ovpn config and store it in a separate file. I keep my key in the same directory as the config file. Be sure to remove the `<key>` and `</key>`  lines from the key file, it must be valid PEM format. Then update the .ovpn config with a line something like this to specify the path to the key.

`key jscott.key`

**Comment by jasonkeithscott** [comment]
The [easyrsa docs](https://github.com/OpenVPN/easy-rsa/blob/master/README.quickstart.md) are somewhat helpful... somewhat. You can set a password for an existing private key generated with `build-client-full ...`. This password encrypts only the private key. Assuming your existing config file username was jscott, you can do the following.

```
sudo docker run -v $OVPN_DATA:/etc/openvpn --rm -it kylemanna/openvpn easyrsa set-rsa-pass jscott

If the key is currently encrypted you must supply the decryption passphrase.
You will then enter a new PEM passphrase for this key.

writing RSA key
Enter PEM pass phrase: **********
Verifying - Enter PEM pass phrase: **********

Key passphrase successfully changed
```

Do the `ovpn_getclient ....` part again and you will have an .ovpn config with a password. Yay.

Should you want to be able to change the password from the client side you need to pull the key out of the .ovpn config and store it in a separate file. I keep my key in the same directory as the config file. Be sure to remove the `<key>` and `</key>`  lines from the key file, it must be valid PEM format. Then update the .ovpn config with a line something like this to specify the path to the key.

`key jscott.key`

To generate the config and cert/keys as [separate files](https://github.com/kylemanna/docker-openvpn/blob/master/docs/clients.md) under /etc/openvpn/clients/ you can do the following.

`docker run -v $OVPN_DATA:/etc/openvpn --rm kylemanna/openvpn ovpn_getclient jscott separated`
