### ISSUE TITLE
Incorrect use of `route` option

### ISSUE THREAD

**Issue by pschiffe** [kylemanna/docker-openvpn#188]
There are couple of issues in this repo about connecting to other services behind the vpn and I'm also trying to solve the similar problem. When reading the documentation and checking the `ovpn_genconfig` script it seems to be clear, that additional route with `-r` option should do it (while having networking stack exposed to the openvpn container with the `--net host`). But it doesn't. Using the `-r` option results in line like this in the server openvpn config file:
```
route 172.99.1.0 255.255.255.0
```

In [openvpn documentation](https://community.openvpn.net/openvpn/wiki/Openvpn23ManPage), we can read:
```
--route network/IP [netmask] [gateway] [metric]
    Add route to routing table after connection is established. Multiple routes can be specified. Routes will be automatically torn down in reverse order prior to TUN/TAP device close.
    This option is intended as a convenience proxy for the route(8) shell command, while at the same time providing portable semantics across OpenVPN's platform space. 
```

So.. when this is specified, opnvpn will try to setup route for `172.99.1.0` (in this example) on the server side, which is wrong, because on the server, this subnet is routed correctly. What we need, is to specify the route on the client side, so the traffic for `172.99.1.0` will be routed through the vpn. Therefore, the correct option for the server side config should be:
```
push route 172.99.1.0 255.255.255.0
```

I've tested this and it works for me the way it should.

**Comment by pschiffe** [comment]
@pieterlange awesome, thanks for pointing that out, I've missed that. Also, do you know about a use case for the server side `route` option? I still can't think of any.

**Comment by pieterlange** [comment]
This is getting more into openvpn specifics, but this would (for example) be used if you want your openvpn server to access networks routed by openvpn clients (to be used in combination with the `--iroute` parameter).

**Comment by pschiffe** [comment]
All right, thanks. I'm closing this issue as there's no problem with the code except maybe missing documentation and a slightly lacking UI/UX (it seems to me that pushing the `route` option to the client is more useful use case than using the `route` option on the server side, so I don't understand why it has it's own switch in the `ovpn_genconfig` script - it's just confusing).
