### ISSUE TITLE
Include the CRL on ovpn_copy_server_files

### ISSUE THREAD

**Issue by gustav-b** [kylemanna/docker-openvpn#198]
In order to revoke a client when using a setup where [the CA root is not stored on the server](https://github.com/kylemanna/docker-openvpn/blob/master/docs/paranoid.md#keep-the-ca-root-key-save), the CRL (`pki/crl.pem`) must be included in the configuration. As of now the CRL is not included when using `ovpn_copy_server_files` and therefor command isn't useful when trying to updating server config after a revocation.

**Comment by kylemanna** [comment]
Good catch, can you confirm I fixed this on the dev image `kylemanna/openvpn:dev` ? Thanks!

**Comment by gustav-b** [comment]
Thanks, I tested it and found some issues, see my comments.

**Comment by kylemanna** [comment]
Updated with changes as mentioned.  I rushed this going out the door and dropped the ball.  Give it another shot.

Thanks!

**Comment by gustav-b** [comment]
Thanks for the quick turnaround! I've tested the latest `:dev` image and it works fine now. 👍

**Comment by kylemanna** [comment]
Merged to master. Enjoy.
