### ISSUE TITLE
ovpn_genconfig includes default route even when override

### ISSUE THREAD

**Issue by deitch** [kylemanna/docker-openvpn#207]
To reproduce:

    ovpn_genconfig -r 10.10.0.0/16

will generate the following route entries in `openvpn.conf`:

```
### Route Configurations Below
route 10.10.0.0 255.255.0.0
route 192.168.254.0 255.255.255.0
```

It adds in the custom route _and_ the default route. The reason is the following. At https://github.com/kylemanna/docker-openvpn/blob/master/bin/ovpn_genconfig#L256 it checks for `USE_DEFAULT_ROUTE` and if set, adds the default route:

```bash
[ $USE_DEFAULT_ROUTE ] && process_route_config "192.168.254.0/24"
```

But at https://github.com/kylemanna/docker-openvpn/blob/master/bin/ovpn_genconfig#L178 when processing the `-r` option, it sets it to `false`, which actually is a valid string:

```bash
        r)
            USE_DEFAULT_ROUTE=false
            process_route_config "$OPTARG"
```

Thus `[ $USE_DEFAULT_ROUTE ]` always evaluates to `true` and the default route _always_ is added.

Instead, the above line should be:

```bash
        r)
            USE_DEFAULT_ROUTE=
            process_route_config "$OPTARG"
```

**Comment by kylemanna** [comment]
I think this was fixed by https://github.com/kylemanna/docker-openvpn/pull/209  -- can you confirm?

**Comment by deitch** [comment]
The code looks right to me. Is there a built image on the hub I can reference? Or should I just clone and build locally and test?

**Comment by kylemanna** [comment]
Yeah, it was pushed to Docker Hub a few days ago upon merge.  Make sure to run `docker pull` to get the latest version.

**Comment by deitch** [comment]
Yep, confirm it works. Thanks @kylemanna !
