### ISSUE TITLE
OTP reneg-sec option

### ISSUE THREAD

**Issue by ShahriarHD** [kylemanna/docker-openvpn#213]
Hi, first of all thanks for this, makes my life much easier 😃 
I got a question regarding the usage of OTP, which is the session will terminate after 1 hour.
the solution I have found is to add the option `reneg-sec <number_of_minutes>`  option to server configuration and client configurations manually. I wonder if there is a better way to do this or if there is an automatic solution already implemented?

**Comment by kylemanna** [comment]
Was resolved in #208 .  Grab the latest docker image with `docker pull kylemanna/openvpn` and give it a try again. You'll probably need to re-generate your server config.
