### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by phlegx** [kylemanna/docker-openvpn#225]
Hi @kylemanna.

I was wondering if it would be possible to add tags again to the releases, this would ease some local versioning stuff. I saw the last tag was set 9 months before. Not sure how up to date this is?

thanks so much!
M.

**Comment by kylemanna** [comment]
Sure, tags on GitHub or Docker Hub?

**Comment by phlegx** [comment]
Cool! Actually I'm using the Docker Hub tags to stick with a certain versin. That would help a lot!

thanks!

**Comment by kylemanna** [comment]
Just created `2.1.0` on Docker Hub (it's queued for building as I type) and `v2.1.0` on the git repo.
