### ISSUE TITLE
server generates container very several seconds

### ISSUE THREAD

**Issue by asm0dey** [kylemanna/docker-openvpn#232]
<img width="872" alt="2017-03-08 12 02 53" src="https://cloud.githubusercontent.com/assets/1297282/23697046/3e805ada-03f7-11e7-90a7-f8e8d4de1f29.png">
This is how my `docker ps -a` looks like

**Comment by kylemanna** [comment]
Something is definitely wrong.  Did you setup an init script?  Have you looked at your system logs?

**Comment by asm0dey** [comment]
No, I was shocked with this behaviour actually. It is possible that some old version caused that. I've restarted docker service, deleted all containers and image and then started compose, not `docker run` command and everything works fine.
