### ISSUE TITLE
docker-openvpn Compatible with Swarm

### ISSUE THREAD

**Issue by joaquin386** [kylemanna/docker-openvpn#239]
Hi

I have been trying to make the doker-openvpn work with swarm but it seems it is not possible.
Do you know if it has work before? (myabe it is just me)

BR

Jo

**Comment by joaquin386** [comment]
Seems as it is the -cap_add that is not being transfer to the swarm ... while on the docker run it works perfectly.

**Comment by joaquin386** [comment]
It is a current issue from docker https://github.com/docker/docker/issues/24862#issuecomment-287025708

**Comment by joaquin386** [comment]
Issue from docker itself, there seems to be wrappers for a Work Around
Issue: https://github.com/docker/docker/issues/24862

**Comment by joneisen** [comment]
It appears the ability to pass -cap_add has been added to Swarm via [this PR](https://github.com/moby/moby/pull/39173) that was just merged to master. Would this resolve the problem with running this package on Swarm?

**Comment by olljanat** [comment]
@joneisen yes it will when fully implemented. You can see roadmap and status on https://github.com/moby/moby/issues/25885#issuecomment-447657852
