### ISSUE TITLE
Must use "server 192.168.255.0/24" for VPN clients to be able to access other routed subnets

### ISSUE THREAD

**Issue by andgeno** [kylemanna/docker-openvpn#245]
Hi,

I've got a question about the default subnet 192.168.255.0/24 that comes with this docker image.

I want all connected VPN clients to be able to access other services that are running on the same docker engine host, but are connected to a different subnet, e.g. 10.10.20.0/24.
This is easy to achieve by pushing a route via "push route 10.10.20.0 255.255.255.0" to the clients.
So far so good. Everything is working like it should. VPN clients can ping any 10.10.20.x host.

Now, if I happen to change the VPN subnet from 192.168.255.0/24 to something else like 10.10.10.0/24, it kind of breaks the networking between VPN clients and the hosts in 10.10.20.0/24.
VPN clients can no longer communicate to 10.10.20.x hosts, but strangely enough, still can ping the OpenVPN server at 10.10.20.1.

Any ideas what I might be missing here?

Thanks!

**Comment by rivaros** [comment]
@andgeno it depends how you change the VPN subnet
Just modifying the line in /etc/openvpn/openvpn.conf
```
server 10.10.10.0 255.255.255.0
``` 
is not enough.

Better use the -s option for ovpn_genconfig
In your case
```
ovpn_genconfig .... -s 10.10.10.0/24
```

since it also influences some environment variables for OPENVPN

**Comment by andgeno** [comment]
Hi @rivaros,

awesome! That's what I seem to have missed all the time.
It's working now as expected. :-D

Thank you very much.

**Comment by DavidBerdik** [comment]
@rivaros Do you know how we could change this on existing deployments without needing to redo the configuration?
