### ISSUE TITLE
Tutorial: Set Up OpenVPN with docker-compose

### ISSUE THREAD

**Issue by sochix** [kylemanna/docker-openvpn#246]
Hello, I wrote a small [tutorial on installing openvpn with docker-compose](https://blog.ambar.cloud/tutorial-set-up-openvpn-with-docker-compose/). Maybe it'll be useful for someone

**Comment by breznak** [comment]
@sochix can you please provide a high-level explanation why/what is the advantage of running `docker-compose` instead of "just running the docker image provided here"? 
Sorry, a docker newbie :)

**Comment by buchdag** [comment]
The way I see/use them, `docker-compose` files store my containers run configuration, and for this purpose are easier to use, retrieve and edit than potentially long `docker run` commands typed on the terminal. When you change something in a `docker-compose` file, the container is automatically recreated with the new configuration on the next run / start.

Running containers this way is pretty handy.

**Comment by breznak** [comment]
> easier to use, retrieve and edit than potentially long docker run commands typed on the terminal.  

I realized that when reading the Readme/startup. Do you plan "only a tutorial"? 
Is there a reason why isn't the `docker-compose` + .yaml the default startup option here?

**Comment by buchdag** [comment]
I guess its because `docker-compose` is a separate component that you have to install manually (as in getting it with curl) and more considered like a development tool, so it's not default and most people will use/know `docker run`.

**Comment by sochix** [comment]
@breznak , I absolutely agree with @buchdag on all points!

**Comment by Guilty-King** [comment]
@sochix Hello sir, 
I already setup the deafult config openvpn as per tutorial and its running well
Both client and server support have native ipv4 ipv6 support but when i connect to vpn , i could only access ipv4 sites 
If possible could you help me setup ipv6 on openvpn

**Comment by sochix** [comment]
@Guilty-King sorry, can't help. I guess you should google for ipv6 with openvpn

**Comment by Guilty-King** [comment]
@sochix thank you for quick reply i will sure look into it

**Comment by Zonciu** [comment]
How to shared the vpn network with other container?
This is a situation:
DbServer A is in LAN，IP 192.168.1.100，it can access the B.
WebServer B is a docker app in the server host, but it can't access A.
Now I'm running a OpenVPN server in a docker container, which is in the same server with B.
I can connect the vpn from A, how to make B connect A without vpn client in B container?
In other words, how to allow all the other containers connect to the vpn client?
