### ISSUE TITLE
Systemd instruction is not very clear

### ISSUE THREAD

**Issue by abonec** [kylemanna/docker-openvpn#247]
I successfully followed original readme to setup OpenVPN with docker and it is working except it won't start on ubuntu startup.
Then followed systemd instruction but faced with not very clear description in which OpenVPN won't start. After all I clear my docker (delete all images, containers, and volumes) and start with following:

`export OVPN_DATA="ovpn-data"`
```
docker volume create --name $OVPN_DATA
docker run -v $OVPN_DATA:/etc/openvpn --rm kylemanna/openvpn ovpn_genconfig -u udp://MY-DIGITAL-OCEAN-IP
docker run -v $OVPN_DATA:/etc/openvpn --rm -it kylemanna/openvpn ovpn_initpki
```
```
curl -L https://raw.githubusercontent.com/kylemanna/docker-openvpn/master/init/docker-openvpn%40.service | sudo tee /etc/systemd/system/docker-openvpn@.service
systemctl enable --now docker-openvpn@data.service
```

but after all status show that:
![image](https://cloud.githubusercontent.com/assets/240587/24961077/5db89736-1fa0-11e7-9a84-9d72150be368.png)

journal says:
```
Apr 12 13:48:48 docker-512mb-ams3-01 systemd[1]: docker-openvpn@data.service: Service hold-off time over, scheduling restart.
Apr 12 13:48:48 docker-512mb-ams3-01 systemd[1]: Stopped OpenVPN Docker Container.
Apr 12 13:48:48 docker-512mb-ams3-01 systemd[1]: Starting OpenVPN Docker Container...
Apr 12 13:48:48 docker-512mb-ams3-01 docker[3055]: Error response from daemon: No such container: ovpn-data
Apr 12 13:48:49 docker-512mb-ams3-01 docker[3061]: latest: Pulling from kylemanna/openvpn
Apr 12 13:48:49 docker-512mb-ams3-01 docker[3061]: Digest: sha256:e1c16f6f2b7683430d617e52750d928ad25fd8a16e4f85d27a556f9883036e9a
Apr 12 13:48:49 docker-512mb-ams3-01 docker[3061]: Status: Image is up to date for kylemanna/openvpn:latest
Apr 12 13:48:49 docker-512mb-ams3-01 systemd[1]: Started OpenVPN Docker Container.
Apr 12 13:48:50 docker-512mb-ams3-01 docker[3080]: /usr/local/bin/ovpn_run: line 55: /etc/openvpn/ovpn_env.sh: No such file or directory
Apr 12 13:48:50 docker-512mb-ams3-01 systemd[1]: docker-openvpn@data.service: Main process exited, code=exited, status=1/FAILURE
Apr 12 13:48:50 docker-512mb-ams3-01 systemd[1]: docker-openvpn@data.service: Unit entered failed state.
```

I newbie in docker and don't understand some of the conceptions that this manual assumed user have.

**Comment by kylemanna** [comment]
The docker container can't find your `/etc/openvpn/ovpn_env.sh file which should be in your `OVPN_DATA` volume.  This file is generated by `ovpn_genconfig`.

Your scripts suggest that you ran `ovpn_genconfig` before the systemd script, but the log output says otherwise.

**Comment by abonec** [comment]
Now it says:
```
Apr 13 11:17:58 docker-512mb-ams3-01 systemd[1]: docker-openvpn@data.service: Service hold-off time over, scheduling restart.
Apr 13 11:17:58 docker-512mb-ams3-01 systemd[1]: Stopped OpenVPN Docker Container.
Apr 13 11:17:58 docker-512mb-ams3-01 systemd[1]: Starting OpenVPN Docker Container...
Apr 13 11:17:58 docker-512mb-ams3-01 docker[31742]: Error response from daemon: No such container: ovpn-data
Apr 13 11:17:59 docker-512mb-ams3-01 docker[31748]: latest: Pulling from kylemanna/openvpn
Apr 13 11:17:59 docker-512mb-ams3-01 docker[31748]: Digest: sha256:e1c16f6f2b7683430d617e52750d928ad25fd8a16e4f85d27a556f9883036e9a
```
Maybe I should give name to my container as said `systemd instruction`:
`Create a Docker volume container named ovpn-data-NAME where NAME is the user's choice to describe the use of the container. In the example configuration given in the README NAME=data.`
Here I have two questions:
1. how to name the container and which container i should name. In the README file name gives only to volume.
2. Should name be `ovpn-data` or `ovpn-data-data` according to `ovpn-data-NAME where NAME is the user's choice to describe`

**Comment by buchdag** [comment]
@abonec Let say you pick NAME = abonec

```
export OVPN_DATA="ovpn-data-abonec"

docker volume create --name $OVPN_DATA

docker run -v $OVPN_DATA:/etc/openvpn --rm -it kylemanna/openvpn ovpn_genconfig -u udp://SERVER-IP

docker run -v $OVPN_DATA:/etc/openvpn --rm -it kylemanna/openvpn ovpn_initpki

curl -L https://raw.githubusercontent.com/kylemanna/docker-openvpn/master/init/docker-openvpn%40.service | sudo tee /etc/systemd/system/docker-openvpn@.service

sudo systemctl daemon-reload

systemctl enable --now docker-openvpn@abonec.service
```
so : 

1. the container is automatically named by systemd 
2. in your example the **volume** name should be `ovpn-data-data`

I have to admit that `NAME=data` is a pretty confusing choice for the example because the volume already use the word data.

**Comment by kylemanna** [comment]
Resolved with #254, if anyone still has issues, let me know.

**Comment by abonec** [comment]
It will be very useful to mention that `systemd.md` instruction is standalone in terms of no need to setup container before it by main instruction.
I thought that systemd instruction is optional to main and should me performed only after main. It will be fine to add link to systemd variant in very top to prevent useless preparations.

**Comment by kylemanna** [comment]
> I thought that systemd instruction is optional to main and should me performed only after main. It will be fine to add link to systemd variant in very top to prevent useless preparations.

Systemd instructions are complete enough to be followed in a standalone manner.

As you said, the main `README` quick start led to a volume container name that wasn't later usable with the default systemd service.  I've updated the `README` to use a default name that works with the systemd example.  [See this commit](https://github.com/kylemanna/docker-openvpn/commit/f996bbaa8e8a8337424f6e5fb80df39c1925354a).

This would allow you to run the quick start, verify operation, then go to the systemd documentation and skip the volume container generation.
