### ISSUE TITLE
Unable to seed torrents

### ISSUE THREAD

**Issue by fuerbringer** [kylemanna/docker-openvpn#249]
I followed the images `docker-compose` instructions with everything working perfectly _except_ seeding torrents. On the client-side `Transmission` shows all ports as `closed`. I tried opening the ports in the hardware and software firewalls and even disabling them entirely but that didn't help.

I was not able to find an easy solution on the internet so I thought it's worth a shot asking here.

**Comment by pieterlange** [comment]
VPN clients are NAT'ed. If you want to route ports from your openvpn server to a specific client you have to setup appropriate routing. EG https://github.com/pieterlange/kube-openvpn/blob/master/watch-portmapping.sh#L20

**Comment by fuerbringer** [comment]
Thank you. But I'm having a bit of trouble understanding the parameters, mainly `$PODIPADDR` and `${dest_ip}`. Unsure of what PODIPADDR is, I tried the IP of `eth0` and `0.0.0.0/0`. I tried setting the dest IP to the local IP of the OpenVPN container `172.19.0.2` aswell as `192.168.255.6` (the clients IP, tun0).

I've tried multiple combinations but this is more or less the result of `iptables -t nat -vnL` so far:
```
Chain OPENVPNPORTFORWARD (1 references)
 pkts bytes target     prot opt in     out     source               destination         
  119  6100 DNAT       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:27335 to:172.19.0.2:27335
```

Am I missing something?

**Comment by pieterlange** [comment]
Replace `-d 0.0.0.0/0` with your server IP and bind the container to your public interface (with the server IP)

**Comment by fuerbringer** [comment]
Thanks, that worked. For anyone else wondering how it's done: Save the above mentioned entries and then shell into your OpenVPN container (`docker exec -it openvpn sh`) and create another entry like this:
```
iptables -t nat -A PREROUTING -p tcp -i eth0 --dport 51414 -j DNAT --to 192.168.255.6
```
`--dport 27335` being the port you wish to forward and `192.168.255.6` would be the the client IP OpenVPN has assigned.

**Comment by chepurko** [comment]
@fuerbringer sorry still can't figure out why my ports aren't being forwarded. Could you please clarify which commands to run? And which should I run on the Docker host versus ones that I should run inside the container?

**Comment by fuerbringer** [comment]
@chepurko Oh boy it's been a while. Let me see. The order would be as follows:

This is meant to be run on host:
```
iptables -t nat -N OPENVPNPORTFORWARD
iptables -t nat -A PREROUTING -j OPENVPNPORTFORWARD
iptables -t nat -A OPENVPNPORTFORWARD -p tcp -d <HOST_IP> --dport 27335 -j DNAT --to <CONTAINER_IP>:27335
```

Inside of the container (via `docker exec`):
```
iptables -t nat -A PREROUTING -p tcp -i eth0 --dport 51414 -j DNAT --to <VPN_CLIENT_IP>
```

**Comment by chepurko** [comment]
@fuerbringer appreciate the help. one other thing... in the host rules the port is 27335 and in the container rules the port is 51414. Is that a typo? Shoud they be the same? Or is the port we want to forward 27335 and the port OpenVPN is listening on 51414?

**Comment by fuerbringer** [comment]
@chepurko I believe in this context it meant the following:
27335 was the port the host seeded torrents on.
51414 was the internal port (the one you'd set in Transmission-Web for example), although I'm not sure myself anymore. Might've mixed this one up.
