### ISSUE TITLE
Client certificate revocation need a restart and won't work past the first one.

### ISSUE THREAD

**Issue by buchdag** [kylemanna/docker-openvpn#250]
Contrary to what is stated in [clients.md](https://github.com/kylemanna/docker-openvpn/blob/master/docs/clients.md), the OpenVPN server won't deny client access based on the CRL before the container is restarted : because ovpn_initpki does not generate a CRL, the "--crl-verify" "$OPENVPN/crl.pem" argument won't be passed to OpenVPN on first launch.

After a first revocation, CRL generation with easyrsa and container restart, OpenVPN will correctly deny client access, but subsequent revocations won't be picked up because of the hardlink hack used in ovpn_run : 

```
# Use a hacky hardlink as the CRL Needs to be readable by the user/group
# OpenVPN is running as.  Only pass arguments to OpenVPN if it's found.
if [ -r "$EASYRSA_PKI/crl.pem" ]; then
    if [ ! -r "$OPENVPN/crl.pem" ]; then
        ln "$EASYRSA_PKI/crl.pem" "$OPENVPN/crl.pem"
        chmod 644 "$OPENVPN/crl.pem"
    fi
    addArg "--crl-verify" "$OPENVPN/crl.pem"
fi
```

**easyrsa gen-crl** does not modify the **crl.pem** file in place but rather remove it and re-create a new one (verified by the new file's inode, different from the hardlinked one), so any **easyrsa gen-crl** issued after the hardlink has been created will break it, and ovpn_run won't pick up the change because it only check for file existence.

I'm working on a fix, I'll submit a pull request soon.

**Comment by kylemanna** [comment]
Related to #101 

Lets continue discussion in your PR or in the original issue.  Closing this issue.
