### ISSUE TITLE
ovpn_genconfig -m option does not work

### ISSUE THREAD

**Issue by niko886** [kylemanna/docker-openvpn#259]
Hello! I'm trying to set link-mtu option by passing -m option to ovpn_genconfig...

```
usage() {
    echo "usage: $0 [-d]"
...
    echo " -m    Set client MTU"
```

But, it seems not working, I'm getting:

```
docker run -v ovpn-data2:/etc/openvpn --rm kylemanna/openvpn ovpn_genconfig -m 1557 
/usr/local/bin/ovpn_genconfig: line 230: OPTARG: unbound variable
Cleaning up before Exit ...

```

**Comment by kylemanna** [comment]
Should be resolved now, thanks for reporting.  Enhanced tests to prevent it from happening in the future.

**Comment by niko886** [comment]
Thanks! Is source code of tests is also on a github?

**Comment by kylemanna** [comment]
Yes, in the `test` directory.
