### ISSUE TITLE
Creation of .ovpn file is incorrect from initial build

### ISSUE THREAD

**Issue by gegere** [kylemanna/docker-openvpn#26]
Greetings Kyle,

I was excited to start using your build but after hours of playing around I was able to understand where the problem was within the build.

The [client.ovpn](https://gist.github.com/gegere/7b0f84574a4f600f8796) file your system generates is not creating a usable file. There is routing information missing.

Here is a working correct [client.ovpn](https://gist.github.com/gegere/a9e63a1b1164d812853e#file-gistfile1-txt-L5)

**Comment by kylemanna** [comment]
Hi Jason,

Thanks for the file.  The client file you sent was generated by kylemanna/openvpn.  It's missing a lot of configuration directives as you've pointed out.

If you look @
https://github.com/kylemanna/docker-openvpn/blob/master/bin/ovpn_genconfig#L130  You'll see that they are present in the script.

The real question is what command did you issue to generate that file?  I'm betting you're using the wrong docker image.  Please share the command line used to generate that file.

**Comment by kylemanna** [comment]
Errr, the correct **client** file is @ https://github.com/kylemanna/docker-openvpn/blob/master/bin/ovpn_getclient#L17

One of the features added to my image is TLS auth, which isn't present in your config file.

What command did you run to get that?

**Comment by kylemanna** [comment]
Errr, the correct **client** file is @
https://github.com/kylemanna/docker-openvpn/blob/master/bin/ovpn_getclient#L17

One of the features added to my image is TLS auth, which isn't present
in your config file.

**Comment by kylemanna** [comment]
Closing due to no update.

**Comment by gegere** [comment]
I am sorry, I didn't see this past request. I have a filter setup in gmail so I don't miss @ messages. Sorry, about that. I still have this information and will get it over to you later today.
