### ISSUE TITLE
openvpn_genconfig EasyRSA fails to find private certificate during initialization

### ISSUE THREAD

**Issue by breznak** [kylemanna/docker-openvpn#260]
EasyRSA fails when following the `docs/paranoid.md` to "keep private cert out of the server" guide.

Command:
`docker run --log-driver=none --net=none --rm -t -i -v $PWD:/etc/openvpn kylemanna/openvpn ovpn_genconfig -T TLS-DHE-RSA-WITH-AES-256-GCM-SHA384 -z -C AES-256-CFB -a SHA384   -u udp://xxx`

Error:
```
DH parameters of size 4096 created at /etc/openvpn/pki/dh.pem

Generating a 4096 bit RSA private key
............................................................................++
..........................++
writing new private key to '/etc/openvpn/pki/private/vpn.vpsfree.cz.key.XXXXaJpHbO'
-----
Using configuration from /usr/share/easy-rsa/openssl-1.0.cnf
Enter pass phrase for /etc/openvpn/pki/private/ca.key:
unable to load CA private key
140636941052812:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:evp_enc.c:534:
140636941052812:error:23077074:PKCS12 routines:PKCS12_pbe_crypt:pkcs12 cipherfinal error:p12_decr.c:108:
140636941052812:error:2306A075:PKCS12 routines:PKCS12_item_decrypt_d2i:pkcs12 pbe crypt error:p12_decr.c:139:
140636941052812:error:0907B00D:PEM routines:PEM_READ_BIO_PRIVATEKEY:ASN1 lib:pem_pkey.c:141:

Easy-RSA error:

signing failed (openssl output above may have more detail)
```

**Comment by clobber88** [comment]
I'm getting the same error with just:

docker-compose run --rm openvpn ovpn_initpki

**Comment by clobber88** [comment]
Disregard for me please - matching passwords worked

**Comment by breznak** [comment]
> Disregard for me please - matching passwords worked 

Thank you, @clobber88 ! I confirm it was a mistake on my side. 

The err message is a bit confusing, I thought I was about to enter another password for an another private key, not that I'm asked for the password for the key generated above! 

Closing
