### ISSUE TITLE
Dockerfile uses Alpine Edge repositories

### ISSUE THREAD

**Issue by josmad** [kylemanna/docker-openvpn#262]
In https://raw.githubusercontent.com/kylemanna/docker-openvpn/2a9059aa361898ed31c06047b566fae72e0ff867/Dockerfile

On lines 10 & 11, why are *edge* repositories used when line 4 explicitly selects version 3.5 of Alpine?

**Comment by kylemanna** [comment]
Per the comment above the repository line:

```
# Community: google-authenticator
# Testing: pamtester
```

[`google-authenticator` was originally only available in edge/community](https://pkgs.alpinelinux.org/packages?name=google-authenticator&branch=&repo=&arch=x86_64&maintainer=), but that appears to have changed in late 2016.

[`pamtester `](https://pkgs.alpinelinux.org/packages?name=pamtester&branch=&repo=&arch=x86_64&maintainer=) is only available in edge/testing


It's probably worth dropping `edge/community` at this point.

Why do you have bring this up?

**Comment by josmad** [comment]
I was curious why the openvpn version was <2.4 as I noticed the edge repositories in the Dockerfile (I wanted 2.4.2)

**Comment by kylemanna** [comment]
Ahh, it's mostly a matter of waiting for Alpine v3.5 to update to it (seems unlikely at this point) or for v3.6 to be released.  The releases happen ~ every 6 months, but hasn't happened just yet.

**Comment by josmad** [comment]
Feel free to close the issue.

**Comment by kylemanna** [comment]
Tracking under #267
