### ISSUE TITLE
2 documentation improvements

### ISSUE THREAD

**Issue by bluepuma77** [kylemanna/docker-openvpn#266]
It would be nice to mention in the step-by-step instructions, that a password has to be entered.

For the docker process it would be nice to have a name and to be automatically restarted.

```
docker run --name openvpn --restart=always -v $OVPN_DATA:/etc/openvpn -d -p 1194:1194/udp --cap-add=NET_ADMIN kylemanna/openvpn
```

**Comment by kylemanna** [comment]
Added a comment about the PKI password prompt and directed users to review the systemd documentation about restarting the container.  Let me know what you think!
