### ISSUE TITLE
Re-running `ovpn_genconfig` drops options and breaks config

### ISSUE THREAD

**Issue by kylemanna** [kylemanna/docker-openvpn#273]
Running `ovpn_genconfig` should be repeatable and when run back to back should generate no changes if run the second time with no arguments.  This is important as `ovpn_genconfig` should be able to update server configs as the upstream server config evolves.

I just ran in to an issue on one of my VPNs where an route pushed to clients were lost after re-generating the configuration.  This was likely broken some time long ago when OVPN_PUSH was declared as an array in `ovpn_env.sh` and now it's just a string.  There was no test, so nobody noticed.

Anyone is welcome to jump in and fix it or I'll get to it at some point when I run in to it again.

Steps to resolve issue:
1. Build a `test` case that runs ovpn_genconfig with some options the first time including things like `ovpn_genconfig -p "route 192.168.25x.0 255.255.255.0"`  run `ovpn_genconfig.sh` again.  Files should be identical and test should fail if they aren't.
2. Fix the known `OVPN_PUSH` re-configuration bug
3. Find other bugs

**Comment by buchdag** [comment]
To be sure I understand the issue correctly: does this happen only for `-p` or for other arguments as well ?

**Comment by kylemanna** [comment]
> To be sure I understand the issue correctly: does this happen only for -p or for other arguments as well ?

I only observed it for `-p`, but possible other options as well.

**Comment by kylemanna** [comment]
Closing in favor of fix from #283
