### ISSUE TITLE
Generated *.ovpn file contains bash code

### ISSUE THREAD

**Issue by nazar-pc** [kylemanna/docker-openvpn#278]
When I do `` contents of generated *.ovpn file literally starts with:
```
+ set -e
+ '[' -z /etc/openvpn ']'
+ source /etc/openvpn/ovpn_env.sh
++ declare -x OVPN_ADDITIONAL_CLIENT_CONFIG
++ declare -x OVPN_AUTH
++ declare -x OVPN_CIPHER
++ declare -x OVPN_CLIENT_TO_CLIENT
```

And there is a lot more bash code afterwards. I didn't have this when generated files before and I've just upgraded my instance to latest image and the issue persists.

It looks like the code that generates output is prepended to the output itself.

How can this happen?

**Comment by kylemanna** [comment]
What is the exact command you ran?  [If you set environment variable `DEBUG=1` you will get the bash commands executed](https://github.com/kylemanna/docker-openvpn/blob/e00a72a3f69b27f91a3d1ac52e85ab17bcb61d32/bin/ovpn_genconfig#L142-L144).

Try running the command as described in the README:

    docker run --rm -it -v $OVPN_DATA:/etc/openvpn  kylemanna/openvpn ovpn_getclient CLIENT

Compared to the with the debug environment set:

    docker run --rm -it -v $OVPN_DATA:/etc/openvpn  --env DEBUG=1 kylemanna/openvpn ovpn_getclient CLIENT

**Comment by nazar-pc** [comment]
`DEBUG` was the reason of this issue, thanks!

**Comment by kylemanna** [comment]
Glad you got it fixed!
