### ISSUE TITLE
systemd Unit not found

### ISSUE THREAD

**Issue by aes-grave** [kylemanna/docker-openvpn#279]
Trying to use the systemd script but I keep getting 

```
[root@clouddocker system]# systemctl enable --now docker-openvpn@jas.service       
Created symlink from /etc/systemd/system/multi-user.target.wants/docker-openvpn@jas.service to /etc/systemd/system/docker-openvpn@.service.
Failed to start docker-openvpn@jas.service: Unit not found.
```

Running the container with 
```
docker run -v $OVPN_DATA:/etc/openvpn -d -p 1194:1194/udp --cap-add=NET_ADMIN kylemanna/openvpn
```

Works fine.

**Comment by kylemanna** [comment]
Everything seems right.  You copied `docker-openvpn@.service` to `/etc/systemd/system` right? Did you r `sudo systemctl daemon-reload` after so that systemd finds the new service?

**Comment by aes-grave** [comment]
Yes and I just tried the daemon-reload.

Here is the systemctl status.
 
`[root@clouddocker multi-user.target.wants]# systemctl status docker-openvpn\@jas.service  
â— docker-openvpn@jas.service - OpenVPN Docker Container
   Loaded: loaded (/etc/systemd/system/docker-openvpn@.service; enabled; vendor preset: disabled)
   Active: inactive (dead)
     Docs: https://github.com/kylemanna/docker-openvpn`

I'm not too familiar with systemd so maybe I have some bad entries there or something that needs to be cleared out.

**Comment by aes-grave** [comment]
Just to add some info. I can run the command the template attempts to execute without issue, example, 
`/usr/bin/docker run --rm --privileged -v ovpn-data-jas:/etc/openvpn --name ovpn-jas -p 1194:1194/udp kylemanna/openvpn:latest ovpn_run `

`[root@clouddocker ~]# docker ps
CONTAINER ID        IMAGE                      COMMAND             CREATED             STATUS              PORTS                    NAMES
d3a1a6fc0f8b        kylemanna/openvpn:latest   "ovpn_run"          53 seconds ago      Up 10 seconds       0.0.0.0:1194->1194/udp   ovpn-jas
[root@clouddocker ~]# `

I suspect something strange with my system's systemd. I don't think this is an actual issue with the template so I am going to go ahead and close this.

**Comment by lgh06** [comment]
same issue on centos 7
