### ISSUE TITLE
UDP port to open

### ISSUE THREAD

**Issue by ImLemni** [kylemanna/docker-openvpn#285]
Hello,
I have set up the basic configuration (using the docker-compose file that you provided). 
I am wondering which UDP port should I open in my firewall. To be precise I use the OVH network firewall for vps. 
The question may look stupid but here is the problem : 
When I authorize udp packets with destination 1194 on the firewall and no other udp packets, I can connect to the firewall and ping any ip address but I can not resolve any name. 
The problem is resolved by authorizing any udp packet on the firewall. (The problem is not resolved however by authorizing udp port 53)
*Note : the firewall only filter incoming packets*
I have looked for sources implying other useful port to open but found none. 
Udp port used on the host (*showing only docker related open ports*)
```
netstat -nupl
udp6       0      0 :::1194                 :::*                                27857/docker-proxy
```

**Comment by buchdag** [comment]
Any luck with both UDP and TCP port 53 ?

**Comment by ImLemni** [comment]
Not with TCP port 53 but I figured it out.
So it is working by adding a rule for udp packet incoming **from** port 53(source port = 53). Previously the rule was about udp packet incoming to port 53.
It makes sense in a way. However I don't really understand how the container handles those packets.
