### ISSUE TITLE
Times out on OS X

### ISSUE THREAD

**Issue by ciudilo** [kylemanna/docker-openvpn#29]
Using Tunnelblick on OS X Yosemite and connection consistently times out after half a minute or so.
jpetazzo/dockvpn is working fine under same conditions.

**Comment by kylemanna** [comment]
Can you tell me more about your configuration and network?

This VPN uses UDP instead of TCP and I'm betting that a router (worse
yet... overloaded NAT router) is dropping your UDP "session".

Have you tried running the docker container with a TCP port?

**Comment by kylemanna** [comment]
No response, closing issue.
