### ISSUE TITLE
Stronger encryption

### ISSUE THREAD

**Issue by tengu8890** [kylemanna/docker-openvpn#290]
I'm trying to strengthen the cipher to AES-256-CBC (and possibly create paranoid-security-config).
Should I hard-code those in ovpn_genconfig:

OVPN_TLS_CIPHER=''
OVPN_CIPHER=''
OVPN_AUTH=''

or there's a possibility to do it by Docker options during image initialization?

**Comment by buchdag** [comment]
The openvpn 2.4 version of this project will default to AES-256-CBC

[You can also pass arguments to ovpn_genconfig.](https://github.com/kylemanna/docker-openvpn/blob/master/docs/paranoid.md#crypto-hardening)
