### ISSUE TITLE
WARNING: INSECURE cipher with block size less than 128 bit (64 bit).

### ISSUE THREAD

**Issue by max-lobur** [kylemanna/docker-openvpn#291]
I Noticed that tunnelblick posts this warning:
```
WARNING: INSECURE cipher with block size less than 128 bit (64 bit). This allows attacks like SWEET32.  Mitigate by using a --cipher with a larger block size (e.g. AES-256-CBC).
```
I followed the README to set up, I guess it should be mentioned there how to increase cipher size, or better to change default to 256 or so

There are even docs for this already https://github.com/kylemanna/docker-openvpn/blob/master/docs/paranoid.md#crypto-hardening
I think this should be a default

**Comment by buchdag** [comment]
See #163 and #290

**Comment by max-lobur** [comment]
Cool! Can we include `--cipher AES-256-CBC` directly to the Dockerfile?
I can do a PR

**Comment by pieterlange** [comment]
@max-lobur you need to update your client.

**Comment by max-lobur** [comment]
@pieterlange indeed! I just switched to 2.4.3 and it worked
