### ISSUE TITLE
systemd

### ISSUE THREAD

**Issue by lodgnewt** [kylemanna/docker-openvpn#296]
how to fix this error?

> Process: 12238 ExecStartPre=/usr/bin/docker rm -f $NAME (code=exited, status=1/FAILURE)

 

> * docker-openvpn@x.service - OpenVPN Docker Container
   Loaded: loaded (/etc/systemd/system/docker-openvpn@.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2017-07-12 04:33:43 UTC; 21s ago
     Docs: https://github.com/kylemanna/docker-openvpn
  Process: 12261 ExecStartPost=/bin/sh -c test -z "${IP6_PREFIX}" && exit 0; sleep 1; ip route replace ${IP6_PREFIX} via $(docker inspect -f "{{ .NetworkSettings.GlobalIPv6Address
  Process: 12256 ExecStartPre=/bin/sh -c test -z "$IP6_PREFIX" && exit 0; sysctl net.ipv6.conf.all.forwarding=1 (code=exited, status=0/SUCCESS)
  Process: 12244 ExecStartPre=/usr/bin/docker pull $IMG (code=exited, status=0/SUCCESS)
  Process: 12238 ExecStartPre=/usr/bin/docker rm -f $NAME (code=exited, status=1/FAILURE)
 Main PID: 12260 (docker)
   CGroup: /system.slice/system-docker\x2dopenvpn.slice/docker-openvpn@x.service
           `-12260 /usr/bin/docker run --rm --cap-add=NET_ADMIN -v ovpn-data-x:/etc/openvpn --name ovpn-x -p 1194:1194/udp kylemanna/openvpn:latest ovpn_run

**Comment by derks** [comment]
Can you paste your systemd unit file?  I'd suspect that it is because the container `$NAME` doesn't exist, and so the `ExecStartPre=/usr/bin/docker rm -f $NAME` line is failing.  I'd set this to `ExecStartPre=/usr/bin/docker rm -f $NAME ||:` so that the command exits `0` even if it fails.

**Comment by lodgnewt** [comment]
https://pastebin.com/CEZz7NP7

**Comment by kylemanna** [comment]
> Process: 12238 ExecStartPre=/usr/bin/docker rm -f $NAME (code=exited, status=1/FAILURE)

This is not a *real* error.  The command failed to remove the container which is expected if the container wasn't already running. It's meant as a clean-up in the event that `systemd` didn't properly terminate the service the last time, it will force the container to be shut down before starting it again.
