### ISSUE TITLE
Remote not picked up by import of .ovpn

### ISSUE THREAD

**Issue by boombatower** [kylemanna/docker-openvpn#30]
Running on Linux using NetworkManger, when I import the `.ovpn` file it complains about no remote being specified. If I move the remote line near the top of file it works properly.

Not sure if this is due to improper generation of `.ovpn` file by `bin/ovpn_getclient` or a broken parser on my platform (if not handled directly by openvpn). I'll probably investigate further, but I figured I'd report in case others have issue or have more details.

Lines in question:
```
</tls-auth>
key-direction 1
remote $OVPN_CN $OVPN_PORT $OVPN_PROTO
EOF

if [ "$OVPN_DEFROUTE" != "0" ];then
    echo "redirect-gateway def1"
```

Seems like nothing after `</tls-auth>` is picked up as the `key-direction` was ignored and has to be manually set as well.

**Comment by kylemanna** [comment]
If you delete the remote line, how does NetworkManager succeed in connecting to anything if it doesn't know where the remote server is?

Can you share your client .ovpn config?  Be sure to obfuscate/anonmize your client's private key and server's IP.

I wonder if this is related to commit f2148d99ae1ec82aa464bacc67c4474d18bbf4b4 which was pulled in by PR #21

If the config looks ok, can you try adding the connection blocks back and report back to us the result?  Also include the version of NetworkManager and host distro.

**Comment by boombatower** [comment]
I did not _delete_ the remote line, as I stated I _moved_ it to the top.

```
client
nobind
dev tun
remote-cert-tls server
remote [[redacted]] 1194 udp

<key>
-----BEGIN PRIVATE KEY-----
[[redacted]]
-----END PRIVATE KEY-----
</key>
<cert>
[[redacted]]
</cert>
<ca>
[[redacted]]
</ca>
<dh>
[[redacted]]
</dh>
<tls-auth>
#
# 2048 bit OpenVPN static key
#
-----BEGIN OpenVPN Static key V1-----
[[redacted]]
-----END OpenVPN Static key V1-----
</tls-auth>
key-direction 1

[[old location of remote line]]
redirect-gateway def1
```

**Comment by boombatower** [comment]
After adding `<connection>` tags around `remote` line I get the same error as before when importing.

```
Importing VPN connection [[redacted]].ovpn failed
File [[redacted]].ovpn is not a valid OpenVPN configuration (no remote).
```

**Comment by boombatower** [comment]
Only thing I see is that the remote line is above certs in samples, but I wouldn't expect that to be required as I don't see mention or explicit ordering.

https://github.com/OpenVPN/openvpn/blob/master/sample/sample-config-files/client.conf

**Comment by kylemanna** [comment]
What Linux distro are you running?  What version are your OpenVPN and NetworkManager (and plugins) packages?

**Comment by boombatower** [comment]
openSUSE 13.2 (Harlequin) (x86_64)
NetworkManger 0.9.10.0-3.4.1
NetworkManager-openvpn 0.9.10.0-2.1.4

rpm package info after dash

**Comment by kylemanna** [comment]
Explicit ordering issue sounds like an issue with the Network Manager client.  Re-open this issue if you can reproduce on vanilla OpenVPN client.
