### ISSUE TITLE
question: how do you control client-to-client connections?

### ISSUE THREAD

**Issue by AleksMeshkov** [kylemanna/docker-openvpn#311]
Hello!

What I need is to deny client-to-client by default (set in server config) but allow **some** clients to make client-to-client connections.

What I found is [this old how-to (year 2010)](http://backreference.org/2010/05/02/controlling-client-to-client-connections-in-openvpn/). I put the container in host network mode, experimented for a while and did't manage.

May be there's more simplified solution?

**Comment by pieterlange** [comment]
Hand out static IP addresses via the client config dir and set up a couple custom iptables rules.

But this gets kind of wasteful/slow at larger scale as all traffic would have to route through the VPN server and you'd probably be better off either using a proper routing protocol (think bird and IPSEC) or direct openvpn tunnels between the clients that need to reach each other.

**Comment by AleksMeshkov** [comment]
thanks, @pieterlange

**Comment by AleksMeshkov** [comment]
@pieterlange, Just gave it a try and again no luck :-( 

I'm new to iptables. Can you please have a look at my configuration?

Docker container is run in **host** network mode

I'm using Centos7 with `firewalld` disabled and `iptables` installed and enabled.

ip_forward is enabled.
```
# sysctl net.ipv4.ip_forward
net.ipv4.ip_forward = 1
```

Here are initial iptables rules.

```
[root]# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
DOCKER-USER  all  --  anywhere             anywhere
DOCKER-ISOLATION  all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain DOCKER (2 references)
target     prot opt source               destination

Chain DOCKER-ISOLATION (1 references)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere
DROP       all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain DOCKER-USER (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere
```

Every client have a configuration file in `ccd` directory with a static IP. 
Here's how I do it for one of clients `ifconfig-push 10.8.0.102 10.8.0.1` 

In my `openvpn.conf` I have `client-to-client` directive disabled.

I have `tun0` iface and `10.8.0.0/24` network.

First off, I allow already established connections:
`iptables -A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT`

Then I set forward rules for 2 clients can reach each other:
```
iptables -A FORWARD -s 10.8.0.10 -d 10.8.0.102 -j ACCEPT
iptables -A FORWARD -s 10.8.0.102 -d 10.8.0.10 -j ACCEPT
```

After all it doesn't work. When I perform `ping 10.8.0.102` from my MAC (which has ip 10.8.0.10) I get:
```
➜  ~ ping 10.8.0.102
PING 10.8.0.102 (10.8.0.102): 56 data bytes
36 bytes from gwr-vl-201.**** (***.**.**.133): Communication prohibited by filter
Vr HL TOS  Len   ID Flg  off TTL Pro  cks      Src      Dst
 4  5  00 5400 29e3   0 0000  3d  01 8749 192.168.1.103  10.8.0.102
```
192.168.1.103 - is my LAN address

What am I missing?

Thanks in advance!

**Comment by AleksMeshkov** [comment]
Aaah! I finally got it to work! All I needed is to add push "route 10.8.0.0 255.255.255.0" to the server config!
