### ISSUE TITLE
Feature request: Port Sharing

### ISSUE THREAD

**Issue by flexbrane** [kylemanna/docker-openvpn#316]
Hello,

Do you thing that it is possible to add the port sharing option?
There is another openvpn docker project that is implementing this option, but it didn't work when I tried.

This option can be very usefull when there is web server on port 80 and 443, and when a local network only allow these 2 ports.

**Comment by buchdag** [comment]
@flexbrane > in fact it's already there, you can pass pretty much any option to the OpenVPN config with the `-e` argument of `ovpn_genconfig`.

That's explained in that doc update : https://github.com/kylemanna/docker-openvpn/pull/331/files

**Comment by flexbrane** [comment]
Thank you for the link!
