### ISSUE TITLE
Can kylemanna/openvpn run as OpenVPN client?

### ISSUE THREAD

**Issue by comphilip** [kylemanna/docker-openvpn#317]
I have a machine running CoreOS, it is a container OS, all application ran as docker containers.

I generate inline OpenVPN client configuration file with `kylemanna/openvp`'s `ovpn_getclient`.  I copy the configuration file to the machine running CoreOS and try to run `kylemanna/openvp`'s `openvpn` as client:

`docker run -v $PWD:/etc/openvpn -w /etc/openvpn --rm -it --net host --cap-add=NET_ADMIN kylemanna/openvpn openvpn --config victor.wong-hko.ovpn --verb 11`

And got TLS error:

> Tue Sep 26 05:32:36 2017 us=285081 TLS: control channel, op=P_CONTROL_V1, IP=[AF_INET]59.148.208.151:1194
Tue Sep 26 05:32:36 2017 us=285209 TLS: initial packet test, i=0 state=S_SENT_KEY, mysid=735e7cf6 65f36b6a, rec-sid=89a1c4ac 27739f32, rec-ip=[AF_INET]59.148.208.151:1194, stored-sid=89a1c4ac 27739f32, stored-ip=[AF_INET]59.148.208.151:1194
Tue Sep 26 05:32:36 2017 us=285291 TLS: found match, session[0], sid=89a1c4ac 27739f32
Tue Sep 26 05:32:36 2017 us=286553 DECRYPT FROM: 2a7251d3 5d1d2ecc 4c0c2dd9 32d0516a f3bcfff7 00000002 59ca8f3a 2089a1c[more...]
Tue Sep 26 05:32:36 2017 us=286685 PID_TEST [0] [TLS_WRAP-0] [0] 1506447162:1 1506447162:2 t=1506403956[0] r=[0,64,15,0,1] sl=[63,1,64,528]
Tue Sep 26 05:32:36 2017 us=286775 TLS: received control channel packet s#=0 sid=89a1c4ac 27739f32
Tue Sep 26 05:32:36 2017 us=286936 ACK received for pid 1, deleting from send buffer
Tue Sep 26 05:32:36 2017 us=287023 ACK read ID 1 (buf->len=1118)
Tue Sep 26 05:32:36 2017 us=287095 ACK RWBS rel->size=8 rel->packet_id=00000001 id=00000001 ret=1
Tue Sep 26 05:32:36 2017 us=287210 ACK mark active incoming ID 1
Tue Sep 26 05:32:36 2017 us=287277 ACK acknowledge ID 1 (ack->len=1)
Tue Sep 26 05:32:36 2017 us=287384 TLS: tls_multi_process: i=0 state=S_SENT_KEY, mysid=735e7cf6 65f36b6a, stored-sid=89a1c4ac 27739f32, stored-ip=[AF_INET]59.148.208.151:1194
Tue Sep 26 05:32:36 2017 us=287458 TLS: tls_process: chg=0 ks=S_SENT_KEY lame=S_UNDEF to_link->len=0 wakeup=604800
Tue Sep 26 05:32:36 2017 us=287528 ACK reliable_can_send active=0 current=0 : [2]
Tue Sep 26 05:32:36 2017 us=287620 BIO write tls_write_ciphertext 1118 bytes
Tue Sep 26 05:32:36 2017 us=287694 Incoming Ciphertext -> TLS
Tue Sep 26 05:32:36 2017 us=287826 SSL state (connect): SSLv3 read server hello A
Tue Sep 26 05:32:36 2017 us=288305 VERIFY ERROR: depth=0, error=self signed certificate: CN=59.148.208.151
Tue Sep 26 05:32:36 2017 us=288419 SSL alert (write): fatal: unknown CA
Tue Sep 26 05:32:36 2017 us=288534 OpenSSL: error:14007086:SSL routines:CONNECT_CR_CERT:certificate verify failed

The same configuration file works well with OpenVPN client in windows and CentOS 6.

Since CA is inline in client configuration file, I have no idea why there is `unknown CA` error.

**Comment by comphilip** [comment]
After research, it is openvpn package issue. 

I create another docker image from alpine with openvpn package installed. It has the same issue. While it works well with image of debian with openvpn package installed.

**Comment by pieterlange** [comment]
Alpine is pretty ahead of the curve - you may also be experiencing version or encryption suite mismatches. What do the server logs say?
