### ISSUE TITLE
How to set DNS in docker openvpn?

### ISSUE THREAD

**Issue by IvanPain** [kylemanna/docker-openvpn#320]
Hello!
I installed openvpn in docker, i read those documentation but i don't understand how to set my dns for openvpn clients, for example (push 192.168.1.1) instead google? Anybody can help me?

**Comment by pieterlange** [comment]
https://github.com/kylemanna/docker-openvpn/blob/83d61c7c18f2f5b1bf6dc995d2bb1e90d794bc57/bin/ovpn_genconfig#L88

**Comment by IvanPain** [comment]
Thanks! It works for me!

**Comment by josjaf** [comment]
How would I do this with docker compose?
