### ISSUE TITLE
Backup text displays, but openvpn.conf backup does not happen

### ISSUE THREAD

**Issue by ventz** [kylemanna/docker-openvpn#33]
This is a very small issue:

When you re-issue ovpn_genconfig for a data container that already exists/has been pre-provisioned with ovpn_genconfig before, you get this:

Backing up /etc/openvpn/ovpn_env.sh -> /etc/openvpn/ovpn_env.sh.1425705327.bak
Backing up /etc/openvpn/openvpn.conf -> /etc/openvpn/openvpn.conf.1425705328.bak
Files /etc/openvpn/ovpn_env.sh.1425705327.bak and /etc/openvpn/ovpn_env.sh differ
Successfully generated config

As it turns out, the "openvpn.conf.1425705328.bak" (in this case '1425705328') does not actually get created.

The "ovpn_env.sh.1425705327.bak" (in this case '1425705327') gets created correctly.

**Comment by kylemanna** [comment]
This is actually expected (yet understandably misleading) behavior.  When I was first developing the script I had a ton backups, so I a diff that removed identical duplicates.

What you are seeing here is that `openvpn.conf.1425705328.bak` is being created and then deleted https://github.com/kylemanna/docker-openvpn/blob/43ae3eb61dd92fccc9c6d971883551823628ddd5/bin/ovpn_genconfig#L198

Perhaps we need to be more verbose
