### ISSUE TITLE
i can't see the remote clients

### ISSUE THREAD

**Issue by rene-gomez** [kylemanna/docker-openvpn#333]
i can't see the remote clients

Hi!

I'm using this container and works fine for clients, but not for servers, because i can't see the remote pcs.

For example, the vpn client can connect to local network, ping to servers and more, but the server can't see the remote client.

i know, this issue is for the routing table, in the container i can see the remote clients, but in the docker server not.

in the Docker server I added this route:

`sudo route add -net 192.168.255.0/24 dev docker0`

but not working.

Thanks in advanced.

Best regards.

**Comment by hydra1983** [comment]
Treat the docker server as one of the openvpn clients. 
Remember,```client-to-client```  communication should be enabled. :D

**Comment by zerpex** [comment]
+1 for the solution.

I tried to connect the server to the vpn container as any other client, but I lost all connections (had to hard-reboot). I guess that there should be a loop somewhere, but how can I have it working ?
z.

**Comment by zerpex** [comment]
Ok, after reading this : https://github.com/kylemanna/docker-openvpn/issues/288
I better understand my problem :D 

So, is there a way for the server to connect to the vpn and set only traffic to other vpn peers to go through the vpn ?
