### ISSUE TITLE
Remove VOLUME ["/etc/openvpn"] from Dockerfile

### ISSUE THREAD

**Issue by fpalinf** [kylemanna/docker-openvpn#334]
Shouldn't be better to remove the directive VOLUME from Dockerfile ?

It would make it easier to extends from this image.

**Comment by kylemanna** [comment]
The volume is there primarily for people who forget / skip setting up volume containers and is overridden by the volume mounts at run time.

Can you give me an example of why it would be better if it was omitted?

**Comment by fpalinf** [comment]
I am not sure it is a common case though:
I extends your image to add tools (like tcptraceroute, dig ...) and to import part of my own /etc/openvpn/* configuration using ADD.
By declaring volume /etc/openvpn/ in your Dockerfile modifying the /etc/openvpn has no more effect after the first time.
In the meantime I resolved this by using my own image alpine + openvpn but I miss the nice tools include in yours.

**Comment by aaomidi** [comment]
Just FYI this would break it with stuff like kitematic or whatever that thirdparty application is called.

**Comment by kylemanna** [comment]
I think the best way to achieve what you want is to override the `$OPENVPN` and `$EASYRSA` variables to point to the new directory added to the extended image.
