### ISSUE TITLE
WARNING: INSECURE cipher with block size less than 128 bit (64 bit).  This allows attacks like SWEET32.  Mitigate by using a --cipher with a larger block size (e.g. AES-256-CBC).

### ISSUE THREAD

**Issue by ops0824** [kylemanna/docker-openvpn#349]
WARNING: INSECURE cipher with block size less than 128 bit (64 bit).  This allows attacks like SWEET32.  Mitigate by using a --cipher with a larger block size (e.g. AES-256-CBC).
...
WARNING: cipher with small block size in use, reducing reneg-bytes to 64MB to mitigate SWEET32 attacks.

**Comment by kylemanna** [comment]
Duplicate of #163 #290 and #291 

Please update your client.
