### ISSUE TITLE
Install fails on coreos - Docker newbie

### ISSUE THREAD

**Issue by jagan-veeraraghavan** [kylemanna/docker-openvpn#35]
Install on  digitalocean coreos droplet threw the following 2 errors.

`docker run --volumes-from ovpn-data --rm kylemanna/openvpn ovpn_genconfig -u udp://vpn.mydomain.com`
Unable to find image 'kylemanna/openvpn:latest' locally
Pulling repository kylemanna/openvpn
5335f54a9b67: Download complete 
511136ea3c5a: Download complete 
8771fbfe935c: Download complete 
0e30e84e9513: Download complete 
e9d888655af1: Download complete 
35914aad6581: Download complete 
546d28527b4d: Download complete 
db8e28720e6c: Download complete 
53458232f293: Download complete 
bc2bcf56442d: Download complete 
1b133a0c8c56: Download complete 
b9bff047adb5: Download complete 
99459ba620ab: Download complete 
4d879bae23f6: Download complete 
34d72f73d9b4: Download complete 
026e12061de8: Download complete 
Status: Downloaded newer image for kylemanna/openvpn:latest
**diff: : No such file or directory**
**diff: : No such file or directory**

------
subsequent command throws another error
`docker run --volumes-from ovpn-data --rm -it kylemanna/openvpn ovpn_initpki`
**/usr/local/bin/ovpn_initpki: line 13: /etc/openvpn/ovpn_env.sh: No such file or directory**

------
is the docker container ubuntu specific or should it work on coreos host too?

**Comment by kylemanna** [comment]
This is my fault from 8d8f19d951b83d241885a323ef846500ce588b72. :-1:  I just committed a fix that should make the `ovpn_genconfig` script work properly.  Regardless of that bug, `ovpn_env.sh` should have been created.

Do a `docker pull kylemanna/openvpn` and try again.

> is the docker container ubuntu specific or should it work on coreos host too?

I haven't tested it on CoreOS, but since everything happens in the docker container I don't see why it shouldn't work.

**Comment by kylemanna** [comment]
If you continue to have problems, add `-e DEBUG=1` to `docker run` commands and post your logs.

**Comment by suamikim** [comment]
I also get `/usr/local/bin/ovpn_initpki: line 13: /etc/openvpn/ovpn_env.sh: No such file or directory` if I run the commands from the quick start.

Here's my complete "anonymised" console output:

```
user@machine:~$ OVPN_DATA="ovpn-data-nuc"
user@machine:~$
user@machine:~$
user@machine:~$ docker volume create --name $OVPN_DATA
ovpn-data-nuc
user@machine:~$
user@machine:~$
user@machine:~$ docker run -v $OVPN_DATA:/etc/openvpn --rm kylemanna/openvpn ovpn_genconfig -u udp://vpn.mydomain.com
Processing PUSH Config: 'block-outside-dns'
Processing Route Config: '192.168.254.0/24'
Processing PUSH Config: 'dhcp-option DNS 8.8.8.8'
Processing PUSH Config: 'dhcp-option DNS 8.8.4.4'
Successfully generated config
Cleaning up before Exit ...
user@machine:~$
user@machine:~$
user@machine:~$ docker run -v $OVPN_DATA:/etc/openvpn --rm -it kylemanna/openvpn ovpn_initpki
/usr/local/bin/ovpn_initpki: line 13: /etc/openvpn/ovpn_env.sh: No such file or directory
user@machine:~$
```

Am I doing anything wrong or is this still a bug?
I'm pretty fresh to docker, so please be exact when asking questions or giving instructions ;)

Thanks

**Comment by suamikim** [comment]
One thing I just realized: After executing the 2nd command to generate the config, the formerly created volume is not listed anymore in `docker volume ls`:

```
user@machine:~$ docker volume create --name $OVPN_DATA
ovpn-data-nuc
user@machine:~$
user@machine:~$
user@machine:~$ docker volume ls
DRIVER              VOLUME NAME
local               ovpn-data-nuc
user@machine:~$
user@machine:~$
user@machine:~$ docker run -v $OVPN_DATA:/etc/openvpn --rm kylemanna/openvpn ovpn_genconfig -u udp://vpn.mydomain.com
Processing PUSH Config: 'block-outside-dns'
Processing Route Config: '192.168.254.0/24'
Processing PUSH Config: 'dhcp-option DNS 8.8.8.8'
Processing PUSH Config: 'dhcp-option DNS 8.8.4.4'
Successfully generated config
Cleaning up before Exit ...
user@machine:~$
user@machine:~$
user@machine:~$ docker volume ls
DRIVER              VOLUME NAME
user@machine:~$
```

Is this correct behaviour?

**Comment by mvilain** [comment]
I'm getting this problem as well, but from within the expect module in ansible. The only way I can think of fixing this is to add to the docker-compose.yml to create an empty version of ovpn_env.sh and copy it to ./openvpn-data/conf/. The expect script running the container still returns 1, but I can get around that.
