### ISSUE TITLE
Error When Running ovpn_genconfig

### ISSUE THREAD

**Issue by wilbertliu** [kylemanna/docker-openvpn#354]
Hello 👋🏻,

I was trying to run this command :
```
sudo docker run -v $OVPN_DATA:/etc/openvpn --rm kylemanna/openvpn ovpn_genconfig -u udp://0.0.0.0
```

But got this error :
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 0 caused \\\"fork/exec /usr/bin/dockerd (deleted): no such file or directory\\\"\"": unknown.
ERRO[0000] error waiting for container: context canceled
```

Do you have any idea why was this happening? I can't continue to further steps, the error is always there.

P.S : I've checked whether `/usr/bin/dockerd` doesn't exist, but it exists.

**Comment by Josholith** [comment]
Something similar happened to me on a totally different docker image. Seems it may have been caused by me doing updates on my workstation, which may have updated docker.  I didn't have to reboot to fix, I just had to restart my docker service (systemctl restart docker) and then I was able to run the container without the above error.

**Comment by marvin-w** [comment]
Hi,

can you provide information on your environment.

OS
Docker version

**Comment by wilbertliu** [comment]
Hello @marvin-w, I’m on Arch Linux. Is there anything else you want to know?

**Comment by marvin-w** [comment]
Hi @wilbertliu, thanks for the information, can you also provide your docker version please?

**Comment by wilbertliu** [comment]
For sure @marvin-w! Here it is :
`Docker version 18.05.0-ce, build f150324782`
