### ISSUE TITLE
add new client key&cert to retrieve config

### ISSUE THREAD

**Issue by ascheucher** [kylemanna/docker-openvpn#357]
Hi,
sorry for being ignorant. I managed to set up the OpenVPN with this images, but don't see how to add additional client keys&certs.
Calling ovpn_initpki seems to generate them for the first client (if I remember correctly). Actually I am able to get the config for it with `... ovpn_getclient client-name`  and can connect with it.
When I try to get another config for a second client with `... ovpn_getclient client-name`, it complains there are no keys & certs for it. Sounds logical to me, but I do not find a way to create them.

Can you please give me a little nudge in the right direction?

Thanks in advance!
Andreas

**Comment by ascheucher** [comment]
As it has not been answered, I found it in meantime. Somehow I must have been blind.
It is following command:
  
    docker run -v $OVPN_DATA:/etc/openvpn --rm -it kylemanna/openvpn easyrsa build-client-full CLIENTNAME nopass

**Comment by pieterlange** [comment]
Yeah i missed this issue but this is covered in the quick start https://github.com/kylemanna/docker-openvpn#quick-start
