### ISSUE TITLE
IPv6 didn't work

### ISSUE THREAD

**Issue by m0nhawk** [kylemanna/docker-openvpn#364]
I have a server from Hetzner on which I've installed the OpenVPN with this documentation: [ipv6](https://github.com/kylemanna/docker-openvpn/blob/master/docs/ipv6.md).

I have ipv6 subnet from Hetzner, e.g. `2000:dead:beaf:c0d3::/64`.

I have configured Docker with IPv6:

```
# /etc/docker/daemon.json
{
  "ipv6": true,
  "fixed-cidr-v6": "2001:db8:1::/64"
}
```

I've replaced `IP6_PREFIX` with my ipv6 subnet:

```
Environment="IP6_PREFIX=2000:dead:beaf:c0d3::/64"
```

There is no error, but, it didn't work.

Am I missing something?

**Comment by christianbur** [comment]
The solution https://github.com/kylemanna/docker-openvpn/issues/366
