### ISSUE TITLE
GCP cannot complete connection to servers on VPC

### ISSUE THREAD

**Issue by stepps** [kylemanna/docker-openvpn#365]
I have installed and configured docker-openvpn in a GCP compute instance. I can connect to the openvpn server and authenticate.
When I try to ping any of the servers on the VPC, it silently fails. Tracepath shows that the packets reach the server, and I can confirm this with tcpdump. 

Thing is I am not sure how to configure a route for the replies to go back to the client. I have a firewall rule that routes back all traffic to the docker-host, but then I am at loss on how to proceed.

Thanks in advance

**Comment by pieterlange** [comment]
Your servers in the VPC will also need to know how to route back to the client. A cheap & easy way to fix that is to simply NAT all traffic at the openvpn instance so the servers only need to know how to send their packets back to the openvpn instance.

See ovpn_genconfig options `-N` and `-r`

**Comment by stepps** [comment]
Yes, I figured that out and found the -N and -r options. All is good now.
A reference to the flags documentation on the main page would be nice to have
