### ISSUE TITLE
WARNING: this cipher's block size is less than 128 bit (64 bit)

### ISSUE THREAD

**Issue by mvasin** [kylemanna/docker-openvpn#375]
`openvpn --config client.ovpn` produces
```
WARNING: this cipher's block size is less than 128 bit (64 bit).  Consider using a --cipher with a larger block size.
```
Let's fix that.

**Comment by vazhnov** [comment]
Is it possible with OpenVPN < 2.4? See https://forums.openvpn.net/viewtopic.php?t=22418

**Comment by voldedore** [comment]
Go inside your container (e.g `docker-compose run --rm openvpn bash` or `docker run --rm -it kylemanna/openvpn bash`)

Then check for the list of supported ciphers

    openvpn --show-ciphers

You can also check it in the official documentation.

Pick the one that would affect secure improvement.

Then generate configuration by option `-C`

    docker run -v $OVPN_DATA:/etc/openvpn --rm kylemanna/openvpn ovpn_genconfig -u udp://vpn.example.com -C $CIPHER

**Comment by Perflyst** [comment]
This is an advanced settings listed in the docs: https://github.com/kylemanna/docker-openvpn/blob/master/docs/paranoid.md
