### ISSUE TITLE
Revoking certificate

### ISSUE THREAD

**Issue by brainv** [kylemanna/docker-openvpn#38]
@kylemanna  Is this possible?

**Comment by kylemanna** [comment]
Definitely possible, not high on the priority list just yet.  Pull requests welcome. :smile:

**Comment by kylemanna** [comment]
Resolved with commit 5021bad5974eab013dd18db5d79ff2dea75c1680.

Please test and let me know if there are issues.

**Comment by kylemanna** [comment]
By the way, you'll need to run `ovpn_genconfig` again to generate an updated `/etc/openvpn/openvpn.conf` with the `crl-verify` option.
