### ISSUE TITLE
Private network routing

### ISSUE THREAD

**Issue by nickpoorman** [kylemanna/docker-openvpn#40]
I'm trying to set up a configuration where I have:

Client (my laptop) => Google Compute Engine (GCE) server

The GCE server has addresses:

+ external: `aaa.aaa.aaa.aaa`
+ internal: `bbb.bbb.bbb.bbb`

I need to be able to access all the internal servers on the GCE by their "Internal IP". My laptop is on a `192.168.100.0/24` network and the internal GCE network is a `10.0.0.0/16` network.

I thought the following would work, but I still can't connect to the internal servers. The VPN connection establishes fine. Note: I don't want all my traffic routed through the VPN, just the traffic destined for the internal servers.

```
docker run --name ovpn-data -v /etc/openvpn busybox
docker run --volumes-from ovpn-data --rm kylemanna/openvpn ovpn_genconfig -u udp://aaa.aaa.aaa.aaa:1194 -d -c -p "route 10.0.0.0 255.255.0.0"
docker run --volumes-from ovpn-data --rm -it kylemanna/openvpn ovpn_initpki
docker run --volumes-from ovpn-data -d -p 1194:1194/udp --cap-add=NET_ADMIN kylemanna/openvpn
docker run --volumes-from ovpn-data --rm -it kylemanna/openvpn easyrsa build-client-full cluster-00 nopass
docker run --volumes-from ovpn-data --rm kylemanna/openvpn ovpn_getclient cluster-00 > cluster-00.ovpn
```

Am I configuring this wrong?

**Comment by kylemanna** [comment]
I don't see a reason this shouldn't work with the right configuration.  I personally haven't setup anything exactly like this however.

First questions that come to mind:

1. Do you have `net.ipv4.ip_forward` enabled on your host?  Also might check the containers too, but not sure that will matter.
2. Have you verified your firewall policies?  In particular iptable's `FORWARD` chain on the host and the container (aka namespace)?

Advanced troubleshooting with `tcpdump` starting on client, moving to container (via `docker exec`), and then on host should lead you to whatever isn't cooperating.

**Comment by nickpoorman** [comment]
This is what I'm seeing on the host:

```
# sysctl net.ipv4.ip_forward
net.ipv4.ip_forward = 1
# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain DOCKER (1 references)
target     prot opt source               destination         
ACCEPT     udp  --  anywhere             172.17.0.5           udp dpt:openvpn
```

And on the container:

```
# docker run --volumes-from ovpn-data -it --rm --cap-add=NET_ADMIN kylemanna/openvpn bash -l
root@9d131986a5d6:/etc/openvpn# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination 
```

**Comment by kylemanna** [comment]
I bet the problem is routing.  Using tcpdump would probably confirm that packets are going form 192.168.100.0/24 -> 10.0.0.0/16 but never coming back as GCE doesn't know how to route back to 192.168.100.0/24 and is send them out the default gateway which Google is promptly dropping.

You'd have to do NAT on the VPN and then the VPN clients could access GCE or some black magic on all your cloud hosts.

**Comment by dw33z1lP** [comment]
I had the same problem, but I ran the container with --net option, then with a `tcpdump -i tun0`  I saw that  the packets forwarded to eth1 (my private network) does not have correct source ip address of the host within the network. With a :

```
iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE
```

I now can ping all the private host ip from my host.

**Comment by nickpoorman** [comment]
Awesome thanks. I also switched to a TCP connection. The MTU was causing problems with UDP.

**Comment by kylemanna** [comment]
Glad to hear you got it straightened out!
