### ISSUE TITLE
/etc/openvpn/ovpn_env.sh: No such file or directory

### ISSUE THREAD

**Issue by mlequeux** [kylemanna/docker-openvpn#41]
I updated all my system (Ubuntu 14.04.2 LTS) and docker (1.6.0) and my openvpn server won't start anymore, with the debug enabled I get this output :

```
$ docker run --volumes-from $OVPN_DATA -p 1194:1194/udp --privileged -e DEBUG=1 kylemanna/openvpn
+ set -e
+ source /etc/openvpn/ovpn_env.sh
/usr/local/bin/ovpn_run: line 13: /etc/openvpn/ovpn_env.sh: No such file or directory
```

It looks like that a path changed in the update process.

Thanks !

**Comment by kylemanna** [comment]
The `ovpn_env.sh` file is generated by the `ovpn_genconfig` script.  So either you never generated the config (probably not true if it worked before) or you deleted/changed the volume container.

Look at the `$OVPN_DATA` container.

**Comment by moi90** [comment]
I have the same issue and I ran the `ovpn_genconfig` before.

**Comment by rutvik2611** [comment]
openvpn:
    image: kylemanna/openvpn
    container_name: "openvpn"
    cap_add:
      - NET_ADMIN
    environment:
      - OVPN_SERVER=udp://vpn.rutvik2611.com
    volumes:
      - "./persist/openvpn:/etc/openvpn"
    restart: always
    networks:
      - backboneNetwork
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.openvpn.entrypoints=openvpn"
      - "traefik.tcp.routers.openvpn.rule=HostSNI(`vpn.rDOMAIN.com`)"
      - "traefik.tcp.services.openvpn.loadbalancer.server.port=1194"
      - "traefik.tcp.routers.openvpn.tls=true"
      - "traefik.tcp.routers.openvpn.tls.certresolver=myresolver"


root@SOME:~# docker logs openvpn
/usr/local/bin/ovpn_run: line 55: /etc/openvpn/ovpn_env.sh: No such file or directory
/usr/local/bin/ovpn_run: line 55: /etc/openvpn/ovpn_env.sh: No such file or directory
