### ISSUE TITLE
enable multi connection per client

### ISSUE THREAD

**Issue by DJafari** [kylemanna/docker-openvpn#419]
is possible each client.ovpn can connect same time with multiple device ?
currently new device connection when old connection enable, no internet access,

thanks

**Comment by Amaelh** [comment]
This is not the spirit : each device should have it's own profile so you can revoke each profile indepentently in case you loose the device.

**Comment by kylemanna** [comment]
As @Amaelh said.  We're not trying to create the wild west here.
