### ISSUE TITLE
duplicate-cn option

### ISSUE THREAD

**Issue by JeanMertz** [kylemanna/docker-openvpn#42]
I noticed the default config having a commented out `duplicate-cn` option. It would be nice if this was configurable. We use a single key for some test setups (less secure, but these environments are more about convenience than security), but without `duplicate-cn` this won't work.

Also, it would be nice if `ovpn_run` would pass all arguments to `openvpn` so we can do things like this:

```
/usr/bin/docker run kylemanna/openvpn ovpn_run --duplicate-cn
```

**Comment by kylemanna** [comment]
Personally I think the duplicate-cn option a a Bad Idea (tm) and don't want to make it easy to enable.

That said, you make an excellent point about passing command line parameters.  When I get time I'll take a look.

In the mean time, the expectation is that you could (not as easy as cmd line arg) trivially append your Docker config file assuming you never run ovpn_genconfig again:

    echo duplicate-cn | docker run --rm -i --volumes-from $OVPN_DATA kylemanna/openvpn tee -a openvpn.conf

Verify:

    docker run --rm --volumes-from $OVPN_DATA kylemanna/openvpn cat openvpn.conf
