### ISSUE TITLE
More liberal license?

### ISSUE THREAD

**Issue by tristanz** [kylemanna/docker-openvpn#43]
jpetazzo's repository is licensed under Apache 2.0.  AGPL makes it difficult to use this repository within some corporate environments.  I know this is sort of ridiculous, but it's the reality. It would be great if your changes could be released under a more liberal license so more of us could benefit.

**Comment by ypid** [comment]
It would be interesting to know those corporate cirumstances a bit better. AGPL should not restrict the use of this container, except if you provied a VPN service and need to change the source code (or Dockerfile) and are unable to release the changes. Is there a reason why those changes can not be released?

**Comment by tristanz** [comment]
First, the changes are often small things like changing DNS servers. We are happy to upstream changes but releasing code requires legal ok, so it's not worth the hassle for small things. We'd need to make sure our fork was available forever. 

Second, clients require us to disclose all GPL licensed software used. We then have to indemnify clients against possible infringement by accidental linking. And even then it creates legal risk. 

Anyway, your call. I do think the evidence is that more liberal licenses get more users and contributors.

**Comment by ypid** [comment]
You don’t need to hard code the DNS server in the docker image. Have a look at the [ovpn_genconfig script](https://github.com/kylemanna/docker-openvpn/blob/master/bin/ovpn_genconfig). There is even a switch for that. Also note that even when you want to run a completly different openvpn configuration you do so by bind mounting the configuration to `/etc/openvpn` in the container. This is what I do in my setup.

To your second point. I guess thats what AGPL means …

Lets see how @kylemanna things about this …

**Comment by kylemanna** [comment]
Typically I prefer MIT or BSD licenses and would consider changing it.  @tristanz, would this work for you?

@ypid is the only one to ever include a license and copyright on one of his contributions.

**Comment by tristanz** [comment]
+1 MIT/BSD.  I just submitted this because I can't use this repo for due to AGPL and it seemed unnecessary.

**Comment by kylemanna** [comment]
@ypid would you be willing to update your ovpn_getclient_all from https://github.com/kylemanna/docker-openvpn/commit/bf34f341fc24e14eab09aa5b744f36b875d7cc69 to an MIT license?

**Comment by ypid** [comment]
I am not fully confidented but ok. I changed the license to MIT.
