### ISSUE TITLE
Change cipher to 128bit.

### ISSUE THREAD

**Issue by kasinjsh** [kylemanna/docker-openvpn#438]
Hi.

I'm using this docker as VPN for My phone and battery drain is very noticeable (around 30%) so I'm willing to test weaker cipher to compare results, but I can't seem to change cipher to AES-128-CBC. I'm using docker composer version. I tried manually change in openvpn.conf and ovpn_env.sh whit config regeneration command in terminal whit no luck.

What am I doing wrong?

**Comment by zelbeinstein** [comment]
Hi!
Select any of the specific additional options you want to use
`-C    A list of allowable TLS ciphers delimited by a colon (cipher).`

**Comment by kasinjsh** [comment]
I tried adding command to  "--cipher AES-128-CBC" to composer, but still log show that  AES-256-GCM cipher is in use.  AES-128-CBC shows up in all config files, but log still shows AES-256-GCM.

`openvpn    | Thu Mar 28 10:42:46 2019 baaluciitis/89.254.143.97:55972 SENT CONTROL [baaluciitis]: 'PUSH_REPLY,block-outside-dns,dhcp-option DNS 1.1.1.1,dhcp-option DNS 1.0.0.1,comp-lzo no,route 192.168.255.0 255.255.255.0,topology net30,ping 30,ping-restart 60,ifconfig 192.168.254.5 192.168.254.6,peer-id 2,cipher AES-256-GCM' (status=1)
openvpn    | Thu Mar 28 10:42:46 2019 baaluciitis/89.254.143.97:55972 Data Channel: using negotiated cipher 'AES-256-GCM'`

**Comment by kasinjsh** [comment]
Got it working by adding "--ncp-ciphers AES-128-CBC" to docker-compose.yml.

**Comment by domi-a** [comment]
hi - got the same problem, 

what do you mean by adding "--ncp-ciphers AES-128-CBC" to docker-compose.yml.
that is no .yml content.
i expect something like : 
    environment:
    - ncp-ciphers AES-128-CBC

which does not do the job.
can you please show how its done

**Comment by domi-a** [comment]
> Got it working by adding "--ncp-ciphers AES-128-CBC" to docker-compose.yml.

hi - got the same problem,

what do you mean by adding "--ncp-ciphers AES-128-CBC" to docker-compose.yml.
that is no .yml content.
i expect something like :
environment:
- ncp-ciphers AES-128-CBC

which does not do the job.
can you please show how its done
