### ISSUE TITLE
Speed up bandwidth

### ISSUE THREAD

**Issue by mario26** [kylemanna/docker-openvpn#447]
**Hi!**

I just installed your VPN with Docker, it works!

I can now use the VPN of my server from a client but the bandwidth is limited to 10Mega.

**Here are the tests:**
---
[VPN Enable]
![capture d ecran du 2019-01-20 00-49-30](https://user-images.githubusercontent.com/1866325/51433557-4956de00-1c4d-11e9-9bff-c0408c33a00b.png)
---
[VPN Disable]
![capture d ecran du 2019-01-18 11-39-55](https://user-images.githubusercontent.com/1866325/51433548-2298a780-1c4d-11e9-95f9-0772faa6410b.png)
---

Can you explain to me how can I change that?

**Thank you !**

**Comment by Amaelh** [comment]
What application are you using for these screenshots ? It could be your device being slow to encrypt/devrypt, I would like to give it a try on my own connection.

**Comment by mario26** [comment]
Hi, you can find the ADSL test here: https://www.sfr.fr/mire-test-debit/

No idea for my problem?

I opened another issue here for other problem:
- https://github.com/kylemanna/docker-openvpn/issues/452
- https://github.com/kylemanna/docker-openvpn/issues/451

**Comment by Amaelh** [comment]
Thanks for the ressource. You need to keep in mind that a VPN needs encryption for each tiny packet on one end, and decryption on the other end. Your speed will slow down for sure, and the final speed is directly related to the capacity of both devices in processing these cryptographic computings.

In my configuration I also have HUGE speed drops (> 10 ratio), and I already improved them drastically just by switching from a PI ZERO VPN server to a PI 3B VPN server. I guess I could improve much more by installing this on a powerful desktop server...  

**VPN enabled :** 
![image](https://user-images.githubusercontent.com/18306558/51854792-eb508780-232b-11e9-8547-b19db3652cb1.png)

**VPN disabled :**
![tester le debit de votre connexion internet - google chrome](https://user-images.githubusercontent.com/18306558/51854847-133feb00-232c-11e9-881c-a84f7a332954.jpg)

In all cases this seems not related to this docker image but more to the original OpenVPN project and globally to the concept of having encryption. I guess we should close this topic.

**Comment by mario26** [comment]
Hi!

Absolutely, now, i encounter another problem: https://github.com/kylemanna/docker-openvpn/issues/462

I will be able to retest the bandwidth once this resolves...

Bye!
