### ISSUE TITLE
VPN + router Huawei 4G

### ISSUE THREAD

**Issue by mario26** [kylemanna/docker-openvpn#448]
**Hi!**

I would like to use my router as a VPN client, i use the Huawei B525s-23a router with a 4G connection.

I have this in the VPN settings of my router:
![capture d ecran du 2019-01-20 01-03-25](https://user-images.githubusercontent.com/1866325/51433696-a86a2200-1c50-11e9-82d8-9ae555b1aabc.png)

I am new to this field, can you explain to me how can i use your Docker with my 4G router?

**Thank you !**

**Comment by buchdag** [comment]
Your router can only connect to an L2TP VPN. That's a different protocol than OpenVPN and not compatible with it.

**Comment by mario26** [comment]
ok, i understood, thank you for this answer!

I found this Docker: https://github.com/hwdsl2/docker-ipsec-vpn-server

It should work with my 4G router!

Thanks again !

**Comment by mario26** [comment]
ok, i understood, thank you for this answer!

I found this Docker: https://github.com/hwdsl2/docker-ipsec-vpn-server

It should work with my 4G router!

Thanks again !
