### ISSUE TITLE
RTNETLINK answers: Operation not permitted

### ISSUE THREAD

**Issue by mario26** [kylemanna/docker-openvpn#451]
Hello,

I would like to understand and correct this error:
```
openvpn         | Tue Jan 22 21:22:16 2019 /sbin/ip route del 192.168.254.0/24
openvpn         | RTNETLINK answers: Operation not permitted
openvpn         | Tue Jan 22 21:22:16 2019 ERROR: Linux route delete command failed: external program exited with error status: 2
```
Can you help me ?

Thank you !

**Comment by mathieu-aubin** [comment]
According to 'ip' exit codes from the manpages , "If an error was reported by the kernel exit status is 2" - if that can help troubleshoot

are you running this with high privileges?

**Comment by mkozjak** [comment]
Same issue. Running with `spec.template.spec.containers.securityContext.capabilities.add.NET_ADMIN` set under Kubernetes.

**Comment by mathieu-aubin** [comment]
check this out
https://kubernetes.io/docs/tasks/configure-pod-container/security-context/

**Comment by mathieu-aubin** [comment]
if it fails, try with sudo for a command instead

**Comment by mkozjak** [comment]
Yeah, privileged mode is needed in docker for it to work.

**Comment by mathieu-aubin** [comment]
running the container with ` --cap-add NET_ADMIN ` ?

i must say. I'm going on close to nothing here

no commands run, no debug log, no environments, not much from what really it is that has been done to actually get this error (that will happen to non provileged users, SELinux context.., docker running 'ip route ..' without having proper authority)

I can keep looking like an idiot trying to debug speech but i believe you had enough

I strongly suggest you show your conf, cmd line, add debug data to "ovpn_run" script, inspect container and volume for changes in network settings versus what the container tries to do...

run the damn container with ` -it bash -il ` and check which user you are .. dump the env, try ` ip route ` then try deleting one with and without sudo...

more infos means you cared enough to open a issue and ask for help

**Comment by mkozjak** [comment]
Hahaahah just close the issue. @mario26 your solution is to run the container as privileged.

**Comment by mario26** [comment]
@mkozjak it's correct ! Thank you :+1:

**Comment by AndnixSH** [comment]
For QNAP, i installed `openresolv` and it solved the problem :)
