### ISSUE TITLE
Unable to retrieve client configuration - permission denied

### ISSUE THREAD

**Issue by Wheresitat** [kylemanna/docker-openvpn#456]
Hello,

When trying to retrieve the client configuration file i get the following error:

sudo docker run -v $OVPN_DATA:/etc/openvpn --rm kylemanna/openvpn ovpn_getclient USER > USER.ovpn
-bash: USER.ovpn: Permission denied

Any ideas what i'm doing wrong here?

**Comment by buchdag** [comment]
Looks like you don't have permission to write the `USER.ovpn` file in your current working dir.

**Comment by Wheresitat** [comment]
> Looks like you don't have permission to write the `USER.ovpn` file in your current working dir.

Yes, but i've just created the file?

writing new private key to '/etc/openvpn/pki/private/user.key.XXXXDaeKkk'
-----
Using configuration from /usr/share/easy-rsa/safessl-easyrsa.cnf
Enter pass phrase for /etc/openvpn/pki/private/ca.key:
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'user'
Certificate is to be certified until Jan 28 09:06:06 2022 GMT (1080 days)
Write out database with 1 new entries
Data Base Updated

**Comment by buchdag** [comment]
> writing new private key to '/etc/openvpn/pki/private/user.key.XXXXDaeKkk'

This is inside your container.

> -bash: USER.ovpn: Permission denied

This is on your host current working dir.

They're not the same.

**Comment by Wheresitat** [comment]
I see, stupid me, it was because i was manually executing sudo.
Disabling that, i get a new error 


docker: Error response from daemon: invalid volume spec ":/etc/openvpn": invalid volume specification: ':/etc/openvpn'.
