### ISSUE TITLE
raspberry pi 3 problem

### ISSUE THREAD

**Issue by lucaszanella** [kylemanna/docker-openvpn#458]
```
Unable to find image 'kylemanna/openvpn:latest' locally
latest: Pulling from kylemanna/openvpn
6c40cc604d8e: Pull complete 
c900ad601fe1: Pull complete 
74f285904ffc: Pull complete 
e8964c63e289: Pull complete 
2887d2908dae: Pull complete 
Digest: sha256:7de85b4611f0e205f3249ef999a6361b2437a5d39e614787d53733d8b5dc6454
Status: Downloaded newer image for kylemanna/openvpn:latest
standard_init_linux.go:207: exec user process caused "exec format error"

```

**Comment by mr-bolle** [comment]
The `latest` tag not support amr CPU architecure.
Download the Dockerfile and replace the `FROM alpine:latest` Tag with `FROM alpine:3.8` or use follow commands (test with Raspberry Pi 2)

```
git clone https://github.com/kylemanna/docker-openvpn.git && cd docker-openvpn
sed -i "/FROM/s/latest/3.8/g" Dockerfile
docker build --no-cache -t kylemanna/openvpn .
```

**Comment by Darathor17** [comment]
Hello,

if you do not want to rebuild the image, I have made a ARM-Compatible [image] here(https://hub.docker.com/r/darathor/openvpn) . 

Cheers

**Comment by Darathor17** [comment]
Hello,

if you do not want to rebuild the image, I have made a ARM-Compatible [image](https://hub.docker.com/r/darathor/openvpn).

Cheers

**Comment by Tvde1** [comment]
Perhaps add a second image to this repository which supports raspberry pi?

**Comment by JulianTiller** [comment]
> 
> 
> Hello,
> 
> if you do not want to rebuild the image, I have made a ARM-Compatible [image](https://hub.docker.com/r/darathor/openvpn).
> 
> Cheers

Would you upload your changes to github so we can take a look at it?

**Comment by Jafalex** [comment]
Hello,

Up. Are people using ```alpine:3.8``` or @JulianTiller 's fork?

Cheers

**Comment by ozelot379** [comment]
```
standard_init_linux.go:211: exec user process caused "exec format error"
```
Same error with RaspberryPi 4 and the `latest` version on DockerHub

No matter with RaspberryPiOs `armv7` (32bit) or `aarch64` (64bit) version

I fixed it by clone this repo and build it self local
```
docker build . -t docker-openvpn --pull --no-cache
```

And I create the empty `vars` file manuelly to fix
```
The file '/etc/openvpn/vars' was not found.
```
like in https://github.com/kylemanna/docker-openvpn/issues/605#issuecomment-694836874

**Comment by kylemanna** [comment]
Sorry, the images hosted on Docker Hub are only for x86_64 platforms.  Building it locally on the desired platform is a good way to work around this.

The vars file is a different problem that affects everyone.
