### ISSUE TITLE
Use web gui OpenVPN

### ISSUE THREAD

**Issue by mario26** [kylemanna/docker-openvpn#463]
Hi!

Is it possible to use the OpenVPN web interface in a Nginx proxy?

Here is the OpenVPN web interface according to the official documentation: https://openvpn.net/vpn-server-resources/how-to-configure-openvpn-as-with-admin-web-ui/

It should be pretty easy to set up a proxy in Nginx to listen to the OpenVPN container...

Is it possible with your docker OpenVPN?

**Comment by mario26** [comment]
Hi!

I'm stupid to ask you this, we do not need a Webui, i'm very happy with your image docker!

Bye

**Comment by davydov-vyacheslav** [comment]
I'd like to reopen this issue.

the web-ui is pretty interesting thing for monitoring. 
I tried to use adamwalach/openvpn-web-ui , but looks like it doesn't work with current docker vpn for some reasons :(

The official [docs](https://openvpn.net/quick-start-guide/) shows that there can be used port 943 for administration.

Is there a way to implement it?

**Comment by debmaiia** [comment]
Hey! I developed a front to monitor the vpn logs and status, based on this image. We already have more than 1k pulls!
Check it out if you would like to: https://hub.docker.com/r/debmaiia/vpnonline
