### ISSUE TITLE
What is the correct format to change the DNS servers?

### ISSUE THREAD

**Issue by stefanfrede** [kylemanna/docker-openvpn#470]
I know that I can change the DNS servers with `-n` but I can't figure out the correct format.

Is it comma seperated like so:
`… ovpn_genconfig -u udp://VPN.SERVERNAME.COM -n 1.1.1.1,1.0.0.1 …`

**Comment by wassup-** [comment]
The DNS server argument gets parsed with [`mapfile`](https://github.com/kylemanna/docker-openvpn/blob/79717903fa3164035412d1ec91d8fcea6b516fb8/bin/ovpn_genconfig#L226)

```
n)
    mapfile -t TMP_DNS_SERVERS <<< "$OPTARG"
    for i in "${TMP_DNS_SERVERS[@]}"; do
      OVPN_DNS_SERVERS+=("$i")
    done
    ;;
```
A quick google search indicates that mapfile by default uses `newline` as its delimiter.

**Comment by Asuforce** [comment]
you can use `-n` option twice. like this
```sh
ovpn_genconfig -u udp://VPN.SERVERNAME.COM -n 1.1.1.1 -n 1.0.0.1
```

**Comment by stefanfrede** [comment]
Thanks!
