### ISSUE TITLE
When reaching the openVPN's gui, I am getting: "Your connection is not private"

### ISSUE THREAD

**Issue by tal47** [kylemanna/docker-openvpn#476]
Hi,
I have exported my OpenVPN docker and it works well (thank you for that)
The issue is when reaching that ip+port (https://< ip >:943/) where my VPN server is, I am getting:
![image](https://user-images.githubusercontent.com/16876322/56500375-31744c00-6513-11e9-8e06-59329a8aca2d.png)

I am suspecting SSL server configs in the container, by now I can see a difference in the timezone - The logfiles time is 4 hours difference  - although I have set the right config:
```
    - TZ=IL 
```
How can I solve that issue?
Thanks!

**Comment by trashcluster** [comment]
you seem to use Access Server, the official ovpn AS github page would be more appropriate. As for your secure connection issue you should look into ssl certs for your ovpn instance. You could also use a reverse proxy like traefik which works REALLY well with docker containers (traefik is has well integrated Let's Encrypt SSL certs with automatic renewal), or a caddy+Let's Encrypt reverse proxy which works on non dockerized services.

**Comment by tal47** [comment]
Thank you very much!
