### ISSUE TITLE
google-authenticator prompting to validate OTP after secret generation

### ISSUE THREAD

**Issue by Canuteson** [kylemanna/docker-openvpn#499]
ovpn_otp_user currently hangs if used in automation while google-authenticator waits on input from the user. It appears google-authenticator is now prompting to validate OTP codes by default, and the --force flag currently used in ovpn_otp_user does not prevent the validation prompt.

**Comment by NaveenNeti** [comment]
A work-around I found was to SSH into the container directly and run the google-authenticator command that `ovpn_otp_user` command runs directly. The code for that can be seen by running this command
`cat /usr/local/bin/ovpn_otp_user`

e.g.
`google-authenticator --time-based --disallow-reuse --force --rate-limit=3 --rate-time=30 --window-size=3 -l "$user@company" -s /etc/openvpn/otp/user.google_authenticator`

**Comment by Canuteson** [comment]
I'm running this as automation in CI. SSH into a container is not an option. Headless mode should be headless.

**Comment by NaveenNeti** [comment]
Try running
`  docker exec -v $OVPN_DATA:/etc/openvpn --rm -t kylemanna/openvpn ovpn_otp_user <user>` instead of `docker run ..`

That seemed to fix the issue for us.

**Comment by slikk66** [comment]
Just going through this now, seems the docs (otp.md) simply forgot to add the -i flag

docs have:
````
docker run -v $OVPN_DATA:/etc/openvpn --rm -t kylemanna/openvpn ovpn_otp_user <user>
````

should be:
````
docker run -v $OVPN_DATA:/etc/openvpn --rm -it kylemanna/openvpn ovpn_otp_user <user>
````

**Comment by Canuteson** [comment]
> Just going through this now, seems the docs (otp.md) simply forgot to add the -i flag
> 
> docs have:
> 
> ```
> docker run -v $OVPN_DATA:/etc/openvpn --rm -t kylemanna/openvpn ovpn_otp_user <user>
> ```
> 
> should be:
> 
> ```
> docker run -v $OVPN_DATA:/etc/openvpn --rm -it kylemanna/openvpn ovpn_otp_user <user>
> ```

This does not resolve the issue I reported. I specifically was complaining about the ability to run this without having to interact, while this "fix" is to allow interaction...

That's a completely different issue.

The correct fix to this issue is in my open PR, adding the `--no-confim` flag to the `google-authenticator` command when run in "interactive" is NOT requested.
https://github.com/kylemanna/docker-openvpn/pull/500/files
