### ISSUE TITLE
Client to client connections without forwarding all traffic through the vpn

### ISSUE THREAD

**Issue by lifepillar** [kylemanna/docker-openvpn#5]
I need to configure OpenVPN to do the following:
1. clients must reach each other;
2. clients must be assigned static IPs;
3. clients must **not** forward all traffic through the vpn.

I may be wrong, but the container does not support all three out of the box. For (2) I have followed [Static IP Addresses](https://github.com/kylemanna/docker-openvpn/blob/master/docs/static-ips.md). For (3), I think you just need to pass `-d` to `ovpn_genconfig` (I'm not sure because I edited an existing configuration). But to also obtain (1), I needed to add this line to the server's config file:

```
push "route 192.168.254.0 255.255.255.0"
```

Can this be added by default or through some option?

**Comment by phlegx** [comment]
@kylemanna having the same use case as @lifepillar but I wanted to user a differnt ip range/subnet i.e. `50.1.0.0/24` in the client config therefore I set: `server 10.50.0.0 255.255.255.0` 

what is the route in my case I have to push to make this working? is this even working with this image when I use a different ip range? What else I need to change to make this work eventually?
