### ISSUE TITLE
suggestion about data-only containers

### ISSUE THREAD

**Issue by n00dl3** [kylemanna/docker-openvpn#50]
Hi,
Just a remark about your `README.md`. I've seen that you suggest to use a busybox image as data-only container. I suppose it is to save disk space, but actually you are wrong. as docker uses AUFS, if you use the same image as your app you actually save space. Maybe you could take a look at this [blog post](http://container42.com/2014/11/18/data-only-container-madness/).
Thank you for your work, Bye.

**Comment by kylemanna** [comment]
The Docker OpenVPN image will continuously update indefinitely.  If I were to create a data volume container from today's docker-openvpn image create a new one tomorrow, ,y system would now need to hold at least two versions of the docker-openvpn image: the original one as the data volume has a refcount on it and current image running.  You would be right if you assumed images were never updated and cleaned-up; however this isn't the case in the long run.
