### ISSUE TITLE
Split tunnel configuration

### ISSUE THREAD

**Issue by sfescape** [kylemanna/docker-openvpn#51]
I'm implementing a split tunnel configuration and can't quite figure out the right options. Currently I configure the server with the "-p" option to push the route out to the client but the configs that I generate contain "redirect-gateway def1" which I think is incorrect. However, if I specify "-d" it turns off NAT which breaks the ability to communicate with the subnet.

Stripping off the "redirect-gateway def1" from the client config does the trick to get it working, but I'm wondering if there is a correct combination of options I should be using to implement split tunneling.

Regards

**Comment by kylemanna** [comment]
If you're trying to remove the `redirect-gateway def1` option then the `-d` option for `ovpn_genconfig` is correct.  Try adding the `-N` option to keep [NAT](https://github.com/kylemanna/docker-openvpn/blob/e53492850faffd78ad3c217a6562d8add8538217/bin/ovpn_genconfig#L45) [enabled](https://github.com/kylemanna/docker-openvpn/blob/e53492850faffd78ad3c217a6562d8add8538217/bin/ovpn_genconfig#L45).

    ovpn_genconfig -N -d ...

If not, then you may have to settle for just stripping the `redirect-gateway def` option out of the client config when you extract them.

**Comment by sfescape** [comment]
Great, I'll try that!
