### ISSUE TITLE
Can not Ping VPN Client from Local Network

### ISSUE THREAD

**Issue by ABrauser** [kylemanna/docker-openvpn#510]
Hello together,
i have the Docker openvpn setup without problem. I can connect to the docker vpn from outside and ping for example a client 192.168.0.15. What i dont understand is why i cant ping the VPN Client with the IP 192.168.255.5. The Docker runs on a synology with the IP 192.168.0.100. Do i have to set some settings to be able to ping / reach the VPN Client 192.168.255.5? I have set a static route on my fritzbox -> 192.168.255.0/24 with the gw 192.168.0.100 but actually that doesn't helped.

**Comment by ABrauser** [comment]
I fixed the problem by my self! just had to add a static route from the destination network 192.168.255.0 the docker Host gateway. 192.168.0.100, aswell a forward iptables and route on the gateway ip where the container is running.

**Comment by echtelerp** [comment]
do you have any more details, what you did?
