### ISSUE TITLE
get client file

### ISSUE THREAD

**Issue by beroliv** [kylemanna/docker-openvpn#519]
where can i find the file after this command?
docker run -v $OVPN_DATA:/etc/openvpn --log-driver=none --rm kylemanna/openvpn ovpn_getclient CLIENTNAME > CLIENTNAME.ovpn

**Comment by LeonDragon** [comment]
How you get the client file CLIENTNAME.ovpn. I can not find it in any directory in docker bash.
I got this results:

bash-5.0# cd /etc/openvpn/
bash-5.0# ls
ccd           crl.pem       down.sh       openvpn.conf  ovpn_env.sh   pki           up.sh
