### ISSUE TITLE
Don't rely on Google DNS ?

### ISSUE THREAD

**Issue by jbleuzen** [kylemanna/docker-openvpn#53]
I wanna use my own DNS server, is it possible that I change DHCP configuration ?

**Comment by kylemanna** [comment]
Few options:

1. Generate a server config (`ovpn_genconfig`) that doesn't push the DNS records to clients.  See the [-D options](https://github.com/kylemanna/docker-openvpn/blob/e53492850faffd78ad3c217a6562d8add8538217/bin/ovpn_genconfig#L44) and set them manually on the clients.
2. Manually edit `openvpn.conf`.  Go about this by running an Ubuntu Docker image (or whatever), connect to the data volume and use something like vim.  This can change the DNS push record to whatever you like.

**Comment by jbleuzen** [comment]
Thanks for your help.

Not ideal but I'll choose the first option. :)
Thanks !
