### ISSUE TITLE
How can I allow clients to reach other machines in the openvpn server subnet

### ISSUE THREAD

**Issue by scmanjarrez** [kylemanna/docker-openvpn#535]
I have 3 subnets in docker:
- Subnet A: 10.10.0.0/24
  - Machine 1: 10.10.0.3
  - VPN Server: 10.10.0.2
- Subnet B: 10.10.1.0/24
  - VPN Server: 10.10.1.2
  - VPN Client: 10.10.1.3
  > Server and client tunnel uses 192.168.255.0/24
- Subnet C: 10.10.2.0/24
  - VPN Client: 10.10.2.2

I would like to be able to ping (I mean, reach) from VPN Client to Machine 1.

[openvpn.conf](https://pastebin.com/3L6XsDPb)
[ovpn_env.sh](https://pastebin.com/zc5Z4euQ)
[vpn.log](https://pastebin.com/T1GjXyWzt)
[docker-compose.yml](https://pastebin.com/0WeLwsr5)

I have mixed several configs looking for the correct one, sorry if I have something wrong.

**Comment by scmanjarrez** [comment]
Finally, I achieved it. Post the answer if someone is in the same situation.
Write this line in you openvpn.conf file, where 10.10.0.0/24 is the LAN subnet you want to be accessible from openvpn subnet
>  \# route traffic to 10.10.0.0/24 through vpn
> push "route 10.10.0.0 255.255.255.0"

Then, set OVPN_NAT to 1 and OVPN_NATDEVICE to the subnet interface (get it with ifconfig or ip addr) that you want to be accessible.
` eth1      Link encap:Ethernet  HWaddr 00:00:00:00:00:00`
`          inet addr:10.10.0.2  Bcast:10.10.0.255  Mask:255.255.255.0`

> declare -x OVPN_NAT=1
> declare -x OVPN_NATDEVICE=eth1

**Comment by Xplouder** [comment]
@scmanjarrez I guess I have the same problem, however, the subnets I want to restrict/allow to VPN clients exist at server host (where the VPN server container is installed). The problem is that I always can ping those subnet hosts via VPN client... you have an idea how prevent this?

**Comment by scmanjarrez** [comment]
> @scmanjarrez I guess I have the same problem, however, the subnets I want to restrict/allow to VPN clients exist at server host (where the VPN server container is installed). The problem is that I always can ping those subnet hosts via VPN client... you have an idea how prevent this?


I don't get you, what exactly would you like to do? Prevent VPN client subnet machines to reach VPN server subnets? The solution I posted was precisely to allow that, if you don't want to do that, just don't set that options.

**Comment by Xplouder** [comment]
@scmanjarrez added a proper question [here](https://github.com/kylemanna/docker-openvpn/issues/540). If possible take a look, thank you!
