### ISSUE TITLE
read UDP: Unknown error (code=10054)

### ISSUE THREAD

**Issue by adisakshya** [kylemanna/docker-openvpn#537]
I'm a newbie in using OpenVPN, I followed [README](https://github.com/kylemanna/docker-openvpn/blob/909744dd7899870df764c2cc0a33ef01e9189849/docs/docker-compose.md).

I did the following steps
```
docker-compose run --rm openvpn ovpn_genconfig -u udp://my-ip-address:8000
docker-compose run --rm openvpn ovpn_initpki
# Everything OK

docker-compose up -d openvpn
export CLIENTNAME="your_client_name"
# without a passphrase
docker-compose run --rm openvpn easyrsa build-client-full $CLIENTNAME nopass

# Successfully created ovpn config file
docker-compose run --rm openvpn ovpn_getclient $CLIENTNAME > $CLIENTNAME.ovpn
```

Now when I tried connecting to the OpenVPN server in the container using the generated configuration file, it showed the following logs
```
Tue Nov 19 19:18:20 2019 OpenVPN 2.4.7 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on Apr 25 2019
Tue Nov 19 19:18:20 2019 Windows version 6.2 (Windows 8 or greater) 64bit
Tue Nov 19 19:18:20 2019 library versions: OpenSSL 1.1.0j  20 Nov 2018, LZO 2.10
Enter Management Password:
Tue Nov 19 19:18:21 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]my-ip-address:8000
Tue Nov 19 19:18:21 2019 UDP link local: (not bound)
Tue Nov 19 19:18:21 2019 UDP link remote: [AF_INET]my-ip-address:8000
Tue Nov 19 19:18:21 2019 read UDP: Unknown error (code=10054)
Tue Nov 19 19:18:23 2019 read UDP: Unknown error (code=10054)
Tue Nov 19 19:18:27 2019 read UDP: Unknown error (code=10054)
Tue Nov 19 19:18:28 2019 SIGTERM[hard,] received, process exiting
```

Any advice? What is causing this issue and how to resolve this?
Should I replace ```my-ip-address:8000``` with ```docker-machine-ip```? Or is it something else that needs to be done?

**Comment by adisakshya** [comment]
> I'm a newbie in using OpenVPN, I followed [README](https://github.com/kylemanna/docker-openvpn/blob/909744dd7899870df764c2cc0a33ef01e9189849/docs/docker-compose.md).
> 
> I did the following steps
> 
> ```
> docker-compose run --rm openvpn ovpn_genconfig -u udp://my-ip-address:8000
> docker-compose run --rm openvpn ovpn_initpki
> # Everything OK
> 
> docker-compose up -d openvpn
> export CLIENTNAME="your_client_name"
> # without a passphrase
> docker-compose run --rm openvpn easyrsa build-client-full $CLIENTNAME nopass
> 
> # Successfully created ovpn config file
> docker-compose run --rm openvpn ovpn_getclient $CLIENTNAME > $CLIENTNAME.ovpn
> ```
> 
> Now when I tried connecting to the OpenVPN server in the container using the generated configuration file, it showed the following logs
> 
> ```
> Tue Nov 19 19:18:20 2019 OpenVPN 2.4.7 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on Apr 25 2019
> Tue Nov 19 19:18:20 2019 Windows version 6.2 (Windows 8 or greater) 64bit
> Tue Nov 19 19:18:20 2019 library versions: OpenSSL 1.1.0j  20 Nov 2018, LZO 2.10
> Enter Management Password:
> Tue Nov 19 19:18:21 2019 TCP/UDP: Preserving recently used remote address: [AF_INET]my-ip-address:8000
> Tue Nov 19 19:18:21 2019 UDP link local: (not bound)
> Tue Nov 19 19:18:21 2019 UDP link remote: [AF_INET]my-ip-address:8000
> Tue Nov 19 19:18:21 2019 read UDP: Unknown error (code=10054)
> Tue Nov 19 19:18:23 2019 read UDP: Unknown error (code=10054)
> Tue Nov 19 19:18:27 2019 read UDP: Unknown error (code=10054)
> Tue Nov 19 19:18:28 2019 SIGTERM[hard,] received, process exiting
> ```
> 
> Any advice? What is causing this issue and how to resolve this?
> Should I replace `my-ip-address:8000` with `docker-machine-ip`? Or is it something else that needs to be done?

I replaced ```my-ip-address:8000``` with ```docker-machine-ip:1194``` and it worked.
Now I got connected to the created OpenVPN server using the config file, but NO INTERNET ?

**Comment by adisakshya** [comment]
I replaced ```my-ip-address:8000``` with ```docker-machine-ip:1194``` and it worked.
Now I got connected to the created OpenVPN server using the config file, but NO INTERNET?

**Comment by rae89** [comment]
@adisakshya How do you get the docker-machine-ip?

**Comment by adisakshya** [comment]
Use the command, once you have your docker-machine active

$docker-machine ip
