### ISSUE TITLE
Container to Client Connection

### ISSUE THREAD

**Issue by klosekkentix** [kylemanna/docker-openvpn#539]
Hello,

I've set up an OpenVPN Server and can connect my clients without problems.
The Clients have access to my Container. The OVPN-Server has the IP 172.17.0.2, the Container 172.17.0.3.

The Clients have the IP 192.168.254.1 or 192.168.253.1.
Server has the IP 192.168.255.0 255.255.255.0

Container is able to Ping the OVPN Server, but pinging a connected Client is not possible.
How do I access as a Container the connected Clients?

Is there an routing issue? 
Why is it possible to access with a client the container, but not with the container the client?

I want to curl Request from Container to Client, but its even with the standard configuration not possible.

Thanks

**Comment by klosekkentix** [comment]
Solved it,

the Host also needs tun0 in the routing table, otherwise the containers on the host cannot reach the connected Clients.

I used this on the host:

sudo ip tuntap add dev tun0 mode tun user USERNAME
sudo ip link set tun0 up
sudo ip addr add xx.xx.xx.xx/24 dev tun0

Hope it helps sm1 with the same problem.

**Comment by klosekkentix** [comment]
Seems like ping is working but nothing else. Still have the problem. A container cannot curl the Client.

**Comment by klosekkentix** [comment]
Now I understand how Networkrouting works... If you know how, its so simple!

What I did:

docker exec ovpn_server_container ifconfig:

It shows you, that eth0, lo and tun0 are used as network interfaces.
So the OVPN-Server Container uses tun0 as configured to communicate with the clients.

On the server or container, ifconfig shows:

eth0 as the only one interface.

Now its clear, you dont have a tun0 to connect with the clients, but your containers are (normaly) bridged with eth0. Therefore this simple routing command is required with the network address of the ovpn_server_container as the gateway:

sudo route add -net 192.168.253.0/24 gw 172.17.0.2

192.168.253.1 is the VPN-Client address i wanted to connect, 172.17.0.2 is the ovpn-server-container.

Thats it

**Comment by LonguCodes** [comment]
@klosekkentix I see you managed to solve the problem. Would you be so kind to explain what you did? I did all the step described, but i can't even ping. I'm also no sure what to set xx.xx.xx.xx to
