### ISSUE TITLE
Docker Healthcheck support

### ISSUE THREAD

**Issue by ElleshaHackett** [kylemanna/docker-openvpn#554]
**Describe the feature**
Being able to see a "health status" of the openvpn Docker container.

**Describe the solution you'd like**
I would like support for the Docker Healthcheck (that is also shown in Portainer.io and probably other Docker management software).

**Describe alternatives you've considered**
Alternative is setting up something similarly without the use of the already existing tools within Docker.

**Additional context**
Usually for HTTP services I add something in the `Dockerfile` like this:

`HEALTHCHECK --interval=60s --timeout=10s --retries=3 CMD (curl -sS http://localhost:80 && curl -sS http://localhost:443) || exit 1`. 

Obviously in this case `curl` probably won't suffice. But there should be a command to check if the UDP or TCP port 1194 is open and otherwise results in an error. That should be sufficient to create simple HEALTHCHECK support for Docker.

For debugging and testing purposses you can use:

`docker inspect --format "{{json .State.Health}}" containername`

![image](https://user-images.githubusercontent.com/5116641/75119611-c3456c00-5684-11ea-8ebb-96371b3def74.png)

**Comment by larssb** [comment]
To expand on the idea [in](https://github.com/kylemanna/docker-openvpn/pull/577) .... just use pgrep in your dockerfile or docker-compose file

**Comment by larssb** [comment]
So @ElleshaHackett,

Give the now closed [PR](https://github.com/kylemanna/docker-openvpn/pull/577) a look. In there is tour recipe on getting a HEALTHCHECK for the *openvpn* container.

And then maybe close this thank you. Have a great 1.

**Comment by ElleshaHackett** [comment]
@larssb great! Thanks a lot :)
