### ISSUE TITLE
rebuild the docker image?

### ISSUE THREAD

**Issue by pschiffe** [kylemanna/docker-openvpn#560]
Hi @kylemanna ,

looking at the docker hub I can see that the latest tag of your image is now 8 months old, based on the alpine 3.10 version. Would you mind to trigger the rebuild of the image to pick up the latest alpine version and package updates? Thanks!

Cheers,

peter

**Comment by kimsyversen** [comment]
+1

**Comment by kalsan** [comment]
+1

**Comment by kylemanna** [comment]
Updated, give it a shot.

Old:
```
OpenVPN 2.4.7 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on May  5 2019
library versions: OpenSSL 1.1.1c  28 May 2019, LZO 2.10
```

New:
```
OpenVPN 2.4.8 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Feb  7 2020
library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
```
