### ISSUE TITLE
How to get it to work in 10.x netwoks?

### ISSUE THREAD

**Issue by kalsan** [kylemanna/docker-openvpn#565]
Hi! Thanks for this great software package, it's super convenient and very stable.

I'd like to use it at a site with a subnet 10.9.1.0/24 and I'm having trouble with that. I did everything exactly as with a 192.168.9.0/24 network (replacing 192.168.9 by 10.9.1 in the openvpn config file) but I can't reach any computer outside the house (ping 8.8.8.8 fails for instance). The router config is identical except for the subnet.

I'm highly unexperienced with openvpn. What can I do to debug the problem further?

**Comment by barajas-victor** [comment]
Have you tried `NAT` config ?

**Comment by kalsan** [comment]
I'm not sure what you mean by that but while trying to find out, I came across the file `[docker-volume]/conf/ovpn_env.sh` in which I found two lines to be configured wrongly:

`declare -x OVPN_ROUTES=([0]="192.168.254.0/24")`
`declare -x OVPN_SERVER=192.168.255.0/24`

I changed `192.168` in each to `10.9` and now the VPN is working fine.

So in the end your answer was helpful, thanks @barajas-victor  :-)
