### ISSUE TITLE
VERIFY ERROR & empty clientlist

### ISSUE THREAD

**Issue by Bond246** [kylemanna/docker-openvpn#567]
Hello,

first of all a big thanks for this docker-package.

I think i'm doing something wrong. I did the quick start guide now 2 times but i always get a 
`VERIFY ERROR: depth=0, error=unsupported certificate purpose: CN=<hostname>`
`OpenSSL: error:1417C086:SSL routines:tls_process_client_certificate:certificate verify failed`

What i've done:
`docker run -v $OVPN_DATA:/etc/openvpn --log-driver=none --rm kylemanna/openvpn ovpn_genconfig -u udp://<my hostname>`

Then i generated the key and cert with
`docker run -v $OVPN_DATA:/etc/openvpn --log-driver=none --rm -it kylemanna/openvpn ovpn_initpki`
cert-name is also the <hostname>
and i used a 20-char passphrase generated by my KeePass client.

After that i started the server with
`docker run -v $OVPN_DATA:/etc/openvpn -d -p 1194:1194/udp --cap-add=NET_ADMIN kylemanna/openvpn`
To check my certificate-gen i also used 
`docker run --rm -it -v $OVPN_DATA:/etc/openvpn kylemanna/openvpn ovpn_listclients` 
but this list is empty.

Nevertheless i exported my config with
`docker run -v $OVPN_DATA:/etc/openvpn --log-driver=none --rm kylemanna/openvpn ovpn_getclient <hostname> > <hostname>.ovpn`

And the result while connecting with this config is the server error on top of this post.

So what is my problem?

Thanks a lot for your support!

**Comment by Bond246** [comment]
i found my issue.

**Comment by qhuy199** [comment]
how to fix this issue? I got same error

**Comment by Bond246** [comment]
Hello

i thought some of the "quick start" steps where optional or instead of other ones. 
But you have to walk through all steps.:

1. initialize the $OVPN_DATA container
1. Start OpenVPN server process
1. Generate a client certificate
1. Retrieve the client configuration with embedded certificates

I just made step 1-2 because i thought i is enough to have an initpki.
