### ISSUE TITLE
List of connected clients

### ISSUE THREAD

**Issue by Sugarv** [kylemanna/docker-openvpn#570]
Is there a way to obtain a list of connected clients (external IP, client certificate used, internal IP, connection time etc)?

**Comment by andreydruz** [comment]
You can install openvpn-monitor container.
https://github.com/ruimarinho/docker-openvpn-monitor

**Comment by AvnerCohen** [comment]
Can also do:

```
docker exec -it $CONTAINER_ID cat /tmp/openvpn-status.log
```

In theory:
```
docker run --rm -it -v $OVPN_DATA::/etc/openvpn kylemanna/openvpn ovpn_status
```
Should too have worked, but /tmp is incorrectly set in the data volume.

**Comment by Pezhvak** [comment]
@AvnerCohen what i get is this `tail: can't open '/tmp/openvpn-status.log': No such file or directory`, i can see you said `/tmp` is not set correctly, how should it get fixed?

**Comment by AvnerCohen** [comment]
@Pezhvak see here - https://github.com/AvnerCohen/docker-openvpn/commit/ec5c62affbe3425b8696ea39ddfcecb73af41ba5
