### ISSUE TITLE
dns forward

### ISSUE THREAD

**Issue by chenglu** [kylemanna/docker-openvpn#58]
Hi

Based on the article http://parabing.com/2014/06/openvpn-on-ubuntu/ in Step 07 -- A DNS service for OpenVPN clients.

I want to have this feature, how could I, thank you very much!

**Comment by ypid** [comment]
Hi

Something like
```
declare -ax OVPN_PUSH='([0]="dhcp-option DNS 192.168.1.1")'
```
in ovpn_env.sh
and
```
push "dhcp-option DNS 192.168.1.1"
```
in the openvpn.conf of the server works for me.

**Comment by kylemanna** [comment]
I'd say jut add it to the client configs are they are extracted to keep the core image simple.  Perhaps users might want a client cert post processing script.
