### ISSUE TITLE
help setting up

### ISSUE THREAD

**Issue by rae89** [kylemanna/docker-openvpn#582]
Right now openvpn is working when setting setting the port forwarding on my router to my host machine running docker. I would like to know if I can port forward to the docker IP address. Is this possible?

**Comment by Paraidomat** [comment]
You mean the IP of the container itself?

**Comment by rae89** [comment]
Yup

**Comment by Paraidomat** [comment]
IIRC this is not possible as long as you're using the default `bridge` type of network with docker. You could try to get this running using [https://docs.docker.com/network/network-tutorial-macvlan/](macvlan) but i doubt that it would work.
