### ISSUE TITLE
How to create a second client

### ISSUE THREAD

**Issue by mechrekt** [kylemanna/docker-openvpn#585]
Hi, I've installed the docker in my open media vault server. It works great, but if I opena again a cli to create a second client for another device, following this command `docker run -v $OVPN_DATA:/etc/openvpn --log-driver=none --rm -it kylemanna/openvpn easyrsa build-client-full CLIENTNAME nopass`
I get this error:
```
Easy-RSA error:

EASYRSA_PKI does not exist (perhaps you need to run init-pki)?
Expected to find the EASYRSA_PKI at: /etc/openvpn/pki
```

Thank you

**Comment by carlneuhaus** [comment]
Check you have the environment variable set to your original value. This will need to be done each time you open a new terminal window.
OVPN_DATA="ovpn-data-example "
The environment variable sets which docker volume to use.

**Comment by mechrekt** [comment]
That's right, the problem was just that. This solved my problem. I'm really newbie with docker. Thank you!
