### ISSUE TITLE
Request to rebuild the image for docker hub

### ISSUE THREAD

**Issue by ratijas** [kylemanna/docker-openvpn#586]
Please, consider rebuilding the image and pushing latest version to Docker Hub.

Latest Alpine Linux 3.12 includes `easy-rsa` version `3.0.7-r0` which fixes some annoying bugs, while Alpine `3.11` sticks to easy-rsa `3.0.6-r0`.

That would be most appreciated. Thanks!

Fixes: #528 
Caused by: https://github.com/OpenVPN/easy-rsa/issues/261#issuecomment-599529357

**Comment by ratijas** [comment]
However, when I tried to rebuild manually from Alpine Linux `3.12` / easy-rsa `3.0.7-r0` on my server, I got new problems.

`$ docker-compose run --rm openvpn ovpn_initpki` produces:
```
Easy-RSA error:

The file '/etc/openvpn/vars' was not found.
```

I am highly uncertain about the cause of it, as well as I am not sure my building environment is compatible with that of Travis CI.

Tests from `tests/run.sh` mostly fail too:
```
testing kylemanna/openvpn:latest
        'paranoid' [1/8]...failed
        'conf_options' [2/8]...passed
        'client' [3/8]...
Easy-RSA error:

The file '/etc/openvpn/vars' was not found.
Unable to find "test1", please try again or generate the key first
==> Config match not found: ^tun-mtu\s\+1337
failed
        'basic' [4/8]...failed
        'dual-proto' [5/8]...failed
        'otp' [6/8]...failed
        'iptables' [7/8]...failed
        'revocation' [8/8]...failed
```

**Comment by neofob** [comment]
@ratijas : I have updated `Dockerfile` on my fork, `tp-ng` branch, that use easy-rsa 3.0.7 and based on alpine:3.12.0 image. Give it a spin and let me know if it works for you.

https://github.com/neofob/docker-openvpn/blob/tp-ng/Dockerfile

TODO: Make a separate branch for PR.

**Comment by ratijas** [comment]
@neofob I am confused by all this checkout and cleanup about easyrsa. They have normal GitHub releases page, and there is 3.0.7 tag with tgz archive — is there a reason not use that one?

https://github.com/OpenVPN/easy-rsa/releases/tag/v3.0.7
https://github.com/neofob/docker-openvpn/blob/16beaf939de00309047573a36dd458cac999eb54/Dockerfile#L14-L20

For now I turned back to using openvpn-install script. But for the same of docker experiments I'll spin up a new server to try it out, but probably not before the next week.

**Comment by neofob** [comment]
@ratijas : iirc, at the time I was working to get it working, there were 2 reasons for that:
1. There was not `easy-rsa` version 3.0.7 in alpine image 3.12.0. I think that the rc0 didn't work.
2. I resorted to use git route and it worked.

Yeah, I'll check out the package on releases github page and give it a spin.

Thanks for pointing that out...

**Comment by ratijas** [comment]
As I pointed out in the first post here, newer Alpine image already has easyrsa 3.0.7, so might just take that for base. Maybe things have changed again since, who knows...

**Comment by ratijas** [comment]
Also, what's the deal with that lonely `cd &&`?

https://github.com/neofob/docker-openvpn/blob/16beaf939de00309047573a36dd458cac999eb54/Dockerfile#L15

**Comment by neofob** [comment]
Haha, it must have been copy & paste or something...

**Comment by neofob** [comment]
@ratijas : I just tested with custom built docker image. So removing this line `ENV EASYRSA_VARS_FILE $OPENVPN/vars` and updating these [2 variables][0] work now with alpine:3.12.0 and alpine easy-rsa package.

Feel free to make a PR if your change(s) work.

[0]: https://github.com/neofob/docker-openvpn/blob/tp-ng/Dockerfile#L30-L35
