### ISSUE TITLE
An OpenVPN 2.4.9 version would make my security people happy

### ISSUE THREAD

**Issue by mleo999** [kylemanna/docker-openvpn#591]
I will send GrubHub $$$ if someone could update the latest docker to 2.4.9 ... ;-) There's a DoS CVE that is fixed and my security audit folks would leave me alone.

**Comment by Y0UZ45** [comment]
No need to do any changes to the code, You can just rebuild the docker image and it will install the latest OpenVPN version.

I just tried it myself like so:

```
docker build --pull -t docker-openvpn .
```
