### ISSUE TITLE
Enable client-to-client

### ISSUE THREAD

**Issue by evanp** [kylemanna/docker-openvpn#61]
I'm using the image for connecting a bunch of Digital Ocean servers. It'd be nice to have the client-to-client option enabled by default.

**Comment by ypid** [comment]
[`ovpn_genconfig -c`](https://github.com/kylemanna/docker-openvpn/blob/15ac3c89b0fe9bc37aa03bd311ed34140dbc5c47/bin/ovpn_genconfig#L43)?

**Comment by kylemanna** [comment]
Assuming the `-c` parameter resolves the issue.  Please clarify if it does not.  Thanks @ypid
