### ISSUE TITLE
How do I delete the created .ovpn?

### ISSUE THREAD

**Issue by namthz** [kylemanna/docker-openvpn#619]
How do I delete the created .ovpn?
Thank you..

**Comment by SashaRyder** [comment]
`rm *.ovpn`

**Comment by namths** [comment]
No no, How to delete after Generate a client certificate ??

"Generate a client certificate without a passphrase
docker run -v $OVPN_DATA:/etc/openvpn --rm -it kylemanna/openvpn easyrsa build-client-full CLIENTNAME nopass"

**Comment by erhan-** [comment]
https://github.com/kylemanna/docker-openvpn/blob/master/docs/clients.md#revoking-client-certificates

**Comment by namths** [comment]
@erhan- Thank you.

**Comment by erhan-** [comment]
No problem my friend!
