### ISSUE TITLE
Docker with a different UDP port

### ISSUE THREAD

**Issue by ayton** [kylemanna/docker-openvpn#632]
Hello...
How can I use your docker with a different UDP port, for example UDP port number 950.
Our ISP is blocking port 1194.

**Comment by kerokim** [comment]
When you launch OpenVPN server process with 950/UDP port,

```
docker run -v $OVPN_DATA:/etc/openvpn -d -p 950:1194/udp --cap-add=NET_ADMIN kylemanna/openvpn
```

After creating the client configuration file(.ovpn), open it with an editor.
Then change the value of the port 1194 to 950 on the 6th and 7th lines.

Before
```
client
nobind
dev tun
remote-cert-tls server

remote SERVER_ADDR 1194 udp

<key>
```

After
```
client
nobind
dev tun
remote-cert-tls server

remote SERVER_ADDR 950 udp

<key>
```

**Comment by ayton** [comment]
Thanks I will try.

**Comment by zpol** [comment]
Some tips on how to start a server with (non-default) port XXXX and retrieve the client config with that port number?  It's generating the cfg always with the default port num.

Could this be done automatically? I mean maybe by passing some argument / additional env VAR to the script that generates the config? -> https://github.com/kylemanna/docker-openvpn/blob/master/bin/ovpn_genconfig

I tried many different things like setting env vars,  
It seems to be somehow hardcoded the port number, also tried to overwrite OVPN_PORT variable but didn't work. 


Any ideas?
Thanks!

**Comment by ayton** [comment]
As for me, I also tried like you, but it didn't work, that's why I wrote here asking for help to set up to a different port, and it works well.
I recently began to study docker configurations, I still have little experience to configure it for myself.

**Comment by billysutomo** [comment]
> When you launch OpenVPN server process with 950/UDP port,
> 
> ```
> docker run -v $OVPN_DATA:/etc/openvpn -d -p 950:1194/udp --cap-add=NET_ADMIN kylemanna/openvpn
> ```
> 
> After creating the client configuration file(.ovpn), open it with an editor.
> Then change the value of the port 1194 to 950 on the 6th and 7th lines.
> 
> Before
> 
> ```
> client
> nobind
> dev tun
> remote-cert-tls server
> 
> remote SERVER_ADDR 1194 udp
> 
> <key>
> ```
> 
> After
> 
> ```
> client
> nobind
> dev tun
> remote-cert-tls server
> 
> remote SERVER_ADDR 950 udp
> 
> <key>
> ```

Hi, I also try to map different port on the host.
I already try this method by changing the port value inside client.
But It's still fail.

**Comment by billysutomo** [comment]
> > When you launch OpenVPN server process with 950/UDP port,
> > ```
> > docker run -v $OVPN_DATA:/etc/openvpn -d -p 950:1194/udp --cap-add=NET_ADMIN kylemanna/openvpn
> > ```
> > 
> > 
> > After creating the client configuration file(.ovpn), open it with an editor.
> > Then change the value of the port 1194 to 950 on the 6th and 7th lines.
> > Before
> > ```
> > client
> > nobind
> > dev tun
> > remote-cert-tls server
> > 
> > remote SERVER_ADDR 1194 udp
> > 
> > <key>
> > ```
> > 
> > 
> > After
> > ```
> > client
> > nobind
> > dev tun
> > remote-cert-tls server
> > 
> > remote SERVER_ADDR 950 udp
> > 
> > <key>
> > ```
> 
> Hi, I also try to map different port on the host.
> I already try this method by changing the port value inside client.
> But It's still fail.

my bad.
turns out i forgot to allow port at firewall.
