### ISSUE TITLE
What is 192.168.254.0/24

### ISSUE THREAD

**Issue by francescobianco** [kylemanna/docker-openvpn#636]
I do not understand why in this line

```
[ "${#OVPN_ROUTES[@]}" == "0" ] && [ "$OVPN_DEFROUTE" == "1" ] && OVPN_ROUTES+=("192.168.254.0/24")
```
at <https://github.com/kylemanna/docker-openvpn/blob/1228577d4598762285958ad98724ab37e7b11354/bin/ovpn_genconfig#L292>

have 192.168.254.0/24 over 192.168.255.0/24 

Is this structural for the VPN?
or it is "one useless route is better than nothing"

**Comment by RafayAK** [comment]
That route is for static IPs I believe. 
https://github.com/kylemanna/docker-openvpn/blob/master/docs/static-ips.md

**Comment by lisenet** [comment]
That route only makes sense if your private subnet is `192.168.254.0/24` and you want to allow clients to access it. I'd make an educated guess that this is the subnet that the person who wrote the code uses.
