### ISSUE TITLE
Automatic answer for "Enter pass phrase for"

### ISSUE THREAD

**Issue by Whisper40** [kylemanna/docker-openvpn#646]
Hello, i don't understand why we are forced to put something, i would like to let this empty..
Because i would like to automate this, but i don't arrive to delete a cert automatically.
```
echo "yes\npassword\n" docker-compose run --rm openvpn ovpn_revokeclient "ovpn-"$1 remove
```
is not working :(

Does someone have an idea for that ?
Thanks

**Comment by kimsyversen** [comment]
I tried to use except to automate creating new certificates. I know I got it working, but it's a while since i used this code. This should give you an idea of what to do.

```
expect <<END
	spawn docker exec -it openvpn easyrsa build-client-full ${USERNAME} 
	expect "Enter PEM pass phrase:"
	send ${USERPASS}\r
	expect "Verifying - Enter PEM pass phrase:"
	send ${USERPASS}\r
	expect "Enter pass phrase for /etc/openvpn/pki/private/ca.key:"
	send ${CAPASS}\r
	expect "Data Base Updated"	
END
```

**Comment by Whisper40** [comment]
Thanks for your purpose but i changed of project to another one based on this but without any interaction that are not at all useful.. We should not set passphrase ourself..
