### ISSUE TITLE
request update openvpn 2.5.3(edge)/2.5.2(stable)

### ISSUE THREAD

**Issue by haohetao** [kylemanna/docker-openvpn#660]
https://pkgs.alpinelinux.org/packages?name=openvpn&branch=edge&repo=main

**Comment by we6607** [comment]
楼主可以发下2.5.3版本软件下地址吗谢谢了半天没找不到！！

**Comment by haohetao** [comment]
@we6607 openvpn官网就有呀

**Comment by kimsyversen** [comment]
What I did to install 2.5.3 was to clone this repo and change the Dockerfile as shown below. 

```
RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing/" >> /etc/apk/repositories && \
    echo "http://dl-cdn.alpinelinux.org/alpine/edge/main/" >> /etc/apk/repositories && \
    apk add --update openvpn iptables bash easy-rsa openvpn-auth-pam google-authenticator pamtester libqrencode && \
```

**Comment by uncaught** [comment]
The current `alpine:latest` already comes with openvpn 2.5.5, so this issue is outdated.

**Comment by lisenet** [comment]
This is the repo that I maintain: https://hub.docker.com/repository/docker/lisenet/openvpn/general

It gets the latest version short after one has been published.
