### ISSUE TITLE
How i can skip tls auth in the config?

### ISSUE THREAD

**Issue by sdlAnti** [kylemanna/docker-openvpn#691]
I'm trying to set up a vpn connection on a mikrotik router, but it doesn't support TLS authentication.
https://wiki.mikrotik.com/wiki/Manual:Interface/OVPN

**Comment by martinius007** [comment]
> I'm trying to set up a vpn connection on a mikrotik router, but it doesn't support TLS authentication. https://wiki.mikrotik.com/wiki/Manual:Interface/OVPN

How did you resolve it?

**Comment by sdlAnti** [comment]
> > I'm trying to set up a vpn connection on a mikrotik router, but it doesn't support TLS authentication. https://wiki.mikrotik.com/wiki/Manual:Interface/OVPN
> 
> How did you resolve it?

I created a docker based vpn wireguard container, updated mikrotik to firmware version 7, successfully connected to the VPN and did not use the solution on openvpn xD
