### ISSUE TITLE
allow client-to-client ?

### ISSUE THREAD

**Issue by racsnet** [kylemanna/docker-openvpn#696]
Hi there,

I want to use this Image to have my LoraWAN Gateways accessible. Thanks for the great work it was really easy to have my GWs connect to the VPN.

But I am unable to communicate to them. Sadly I was unable to find some information in the docs.
So is there a way to have client-to-client traffic allowed?

I could then simply connect to my openvpn and access the Gateways through this tunnel.

**Comment by racsnet** [comment]
client-to-client in config is right. seems like my gateway is blocking

**Comment by Linyuxujun** [comment]
Can you tell me how the gateway is blocked?
