### ISSUE TITLE
Renewing client certificate

### ISSUE THREAD

**Issue by BachirBelkhiri** [kylemanna/docker-openvpn#729]
Hi,

Can anyone show me how to renew the client certificate, without having to remove and add the client again ?

**Comment by BachirBelkhiri** [comment]
I found it, in case someone need it, all what you have to do is `easyrsa renew <client>` and to automate it maybe something like `echo yes | easyrsa renew <client>`

**Comment by aquanxxx** [comment]
when I try it doesn't show an invalid date error.. certificate expires in more than 30 days. Renewal not allowed
