### ISSUE TITLE
Server Certificate Expired - How to Renew?

### ISSUE THREAD

**Issue by batesenergy** [kylemanna/docker-openvpn#731]
Our server certificate has expired and clients are unable to connect! How do we renew the server certificates? or extend its expiration? 

This is for a production VPN so any quick help would be greatly appreciated!

**Comment by nrukavkov** [comment]
the same problem

**Comment by nrukavkov** [comment]
@batesenergy I removed previous certificate and create a new one with the same name. Here is a example https://github.com/angristan/openvpn-install/issues/1002#issuecomment-1229525488

**Comment by batesenergy** [comment]
Did this work for you?

Patrick Bates
Open IoT Group
207.242.6313

**Comment by nrukavkov** [comment]
@batesenergy yes

**Comment by batesenergy** [comment]
For those who run into the same issue. Here are the changes we made to fix this issue:

`server_cn= "Server Common Name"`
`mv /etc/openvpn/pki/reqs/$server_cn.req /etc/openvpn/pki/reqs/$server_cn.req.backup`
`mv /etc/openvpn/pki/private/$server_cn.key /etc/openvpn/pki/private/$server_cn.key.backup`
`mv /etc/openvpn/pki/issued/$server_cn.crt /etc/openvpn/pki/issued/$server_cn.crt.backup`
`cd /etc/openvpn`
`easyrsa build-server-full $server_cn nopass`

Then reboot the container to take effect.

**Comment by proambb** [comment]
Thanks, @batesenergy ! I can confirm that clients are able to connect to the server without updating the clients certificates. That was my main concern, that we would have to update all the client certificates after updating the server certificate
