### ISSUE TITLE
Error response from daemon: no such id: ovpn-data

### ISSUE THREAD

**Issue by a1exus** [kylemanna/docker-openvpn#74]
What am I doing wrong?

```
root@alexus:~# OVPN_DATA="ovpn-data"
root@alexus:~# docker run --volumes-from $OVPN_DATA -d -p 1194:1194/udp --cap-add=NET_ADMIN kylemanna/openvpn
Error response from daemon: no such id: ovpn-data
root@alexus:~# 
```

**Comment by kevinejohn** [comment]
You skipped the first step

* Create the `$OVPN_DATA` volume container, i.e. `OVPN_DATA="ovpn-data"`

        docker run --name $OVPN_DATA -v /etc/openvpn busybox

https://github.com/kylemanna/docker-openvpn/blob/master/README.md#quick-start

**Comment by a1exus** [comment]
hmm, that's weird... I actually already did those steps, if I did not do them I wouldn't be able to VPN in... something weird happened to my docker-machine just now, I logged in and I noticed docker service wasn't running, so I start it, however I wasn't able to start docker-openvpn container due to missing volume container..

I just tried to re-initialize volume container, but still getting an error:

```
root@alexus:~# OVPN_DATA="ovpn-data"
root@alexus:~# docker run --volumes-from $OVPN_DATA --rm kylemanna/openvpn ovpn_genconfig -u udp://X
Error response from daemon: no such id: ovpn-data
root@alexus:~# 
```

**Comment by AntouanK** [comment]
How will that command 
```
docker run --name $OVPN_DATA -v /etc/openvpn busybox
```
give you a volume container?

When I run it, all I get is a dead busybox container
```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                     PORTS               NAMES
73f7595e954b        busybox             "sh"                     5 minutes ago       Exited (0) 5 minutes ago                       ovpn-data
```
There's nothing written to /etc/openvpn.

**Comment by TheNomad11** [comment]
I have the same issue. When i run 

`docker run --volumes-from $OVPN_DATA --rm -p 443:1194/tcp --privileged kylemanna/openvpn ovpn_run --proto tcp`

I get the error message:

`docker: Error response from daemon: No such container: --rm.`

although I had created the container

**Comment by kylemanna** [comment]
Read the answer from @kevinejohn.  Your same issue as the same solution, set the environmental variable in your shell.

**Comment by TheNomad11** [comment]
as a1exus I had done that step before 
`OVPN_DATA="ovpn-data"`
`docker run --name $OVPN_DATA -v /etc/openvpn busybox` 
and was able to run openvpn and use it. it's now when I need to change port or over to TCP that I run into this issue. Sorry, I am a newbie and in the learning phase, thanks for your patience
