### ISSUE TITLE
do not want client redirects all internet traffic over the VPN (OVPN_DEFROUTE=0)

### ISSUE THREAD

**Issue by adilroot** [kylemanna/docker-openvpn#75]
I have disabled  `push "redirect-gateway"` by  `OVPN_DEFROUTE=0`, I do not want client redirects all internet traffic over the VPN.

But I cannot anymore ping the openvpn server ip.

**Comment by kylemanna** [comment]
I'd double check the setting in your client aren't adding the default route.  Also manually verify client config.  If the server isn't pushing routes, those are the only ways that could happen.

**Comment by MihaMarkic** [comment]
I'm using docker run  OVPN_DEFROUTE=0 ... but the Internet traffic is still going through VPN (I need VPN only to access it through IP).
Am I missing something obvious?

**Comment by MihaMarkic** [comment]
Ah, probably I didn't issue the client certificate using OVPN_DEFROUTE=0
