### ISSUE TITLE
Non interactive mode.

### ISSUE THREAD

**Issue by hourliert** [kylemanna/docker-openvpn#77]
Hi,

First thank you very much for this wonderful image. It works like a charm!

Therefore, I would know if there are any way to do the quickstart in non interactive mode? I am trying to deploy an openvpn server with ansible.

Thanks in advance.

**Comment by ypid** [comment]
Good question. Depending on your needs you might want to use an the Ansible role [debops.pki](https://github.com/debops/ansible-pki) to setup a self signed PKI and use that for OpenVPN. Only thing left would be to setup a Docker container using a configuration templated using Ansible.

But that is just one (untested) way to do it. I would also be interested in other ways. I did it kind of manually using a little role (just uploaded) https://github.com/ypid/ansible-docker-openvpn

**Comment by kylemanna** [comment]
> Therefore, I would know if there are any way to do the quickstart in non interactive mode? I am trying to deploy an openvpn server with ansible.

Yeah, look at the test scripts.  They configure, state and issue certs to test the code:

https://github.com/kylemanna/docker-openvpn/blob/master/tests/basic.sh

**Comment by hourliert** [comment]
Thanks for your answers.

I will try to use the role debops.pki.
After looking at the test files, you use nopass as an option and it seems not very secure. I don't think I could use that for a 'semi-production' environnement.

**Comment by kylemanna** [comment]
You can always generate the certificates outside of the container and insert them later. Look at the backup docks for an example of how you might do that.

**Comment by hd-deman** [comment]
@hourliert I have the same issue. have you solved the problem. I'm looking for complete example of combining this container and ansible.

**Comment by hourliert** [comment]
Hi,

I am very busy at the moment and I haven't find a good solution. I think the @kylemanna solution is the easiest.

**Comment by hd-deman** [comment]
After some research I notice that I can't set password
```
(echo openvpn_pem_pass; echo openvpn_pem_pass; echo openvpn_pem_pass) | \
docker run -i -e "DEBUG=1" -e "EASYRSA_BATCH=1" -e "EASYRSA_REQ_CN=Test CA" \
kylemanna/openvpn ovpn_initpki
``` 

Because of this http://stackoverflow.com/questions/22415601/using-easy-rsa-how-to-automate-client-server-creation-process#comment34120279_22422834

**Comment by jedwards1211** [comment]
It's possible to set the password now with `EASYRSA_PASSIN=pass:<password>` and `EASYRSA_PASSOUT=pass:<password>`, see https://github.com/OpenVPN/easy-rsa/issues/435
