### ISSUE TITLE
How should we handle client

### ISSUE THREAD

**Issue by kopax** [kylemanna/docker-openvpn#79]
I want to set up a VPN between 3 servers, I want to create a LAN between all of them.
I test it with the server and me as a client, very easy.
However, I want to use it from server to server, should I use a docker image of openvpn on the client for that ? If yes, is your image ready for that ?
Using the default config, I understand that the http traffic is rerouted, I want to configure a private LAN. I can start service listening only on the vpn interface as a security feature
Is the configuration ready for that ? Should I turn off something ?

Thanks again for your work

**Comment by ypid** [comment]
Not sure if OpenVPN is the best solution here. You might want to check: Tinc https://github.com/debops/ansible-tinc

**Comment by kopax** [comment]
I am checking your link now it look nice. 
Do you know if Tinc fit well with consul ?

**Comment by ypid** [comment]
Never tried it.

**Comment by kopax** [comment]
Then how did you heard of it ? it's only 4 contributors, 25 commits and 6 month old.

**Comment by ypid** [comment]
:smile: Check my contributions to the DebOps project https://www.openhub.net/accounts/ypid/positions

**Comment by kopax** [comment]
Well, I have installed and tested tinc with the docker image of JensErat/tinc.
I'll close this post, but If I may ask a last question, maybe you can help.

tun0 seems not to have a broadcast address, I want to launch a server that listen to tun0 interface, I want to bind it to something like "10.0.0.0", do you know how to do that ? 

    tun0      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          inet addr:10.0.0.1  P-t-P:10.0.0.1  Mask:255.255.255.0
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1500  Metric:1
          RX packets:10 errors:0 dropped:0 overruns:0 frame:0
          TX packets:10 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:500 
          RX bytes:840 (840.0 B)  TX bytes:840 (840.0 B)

**Comment by ypid** [comment]
It says that in the `ifconfig` output `P-t-P`. That stands for [Point-to-point](https://en.wikipedia.org/wiki/Point-to-point_%28telecommunications%29) :smile: 

Try `ip a` which actually says POINTOPOINT: 

```
20: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 100
```

**Comment by kylemanna** [comment]
> I want to set up a VPN between 3 servers, I want to create a LAN between all of them.
> I test it with the server and me as a client, very easy.
> However, I want to use it from server to server, should I use a docker image of openvpn on the client for that ? If yes, is your image ready for that ?

Yes, I already use the image for this.  Hence the name "virtual private network".  I have a collection of machines all privately connected to each other over the Internet.  All of the data must go through the server.  You have to decide if this is a problem for your use case and find something different if it is.

I'd run the docker-openvpn image on the server to manage everything and then run a regular process on the clients. This will keep networking simple for the clients.  But, realistically you could do any imaginable combination with the right OpenVPN configuration and wrestling with Docker networking.

> Using the default config, I understand that the http traffic is rerouted, I want to configure a private LAN.  I can start service listening only on the vpn interface as a security feature
> Is the configuration ready for that ? Should I turn off something ?

Yes, set the following `ovpn_genconfig` options:
1. [Turn off NAT routing to the Internet with `-d`](https://github.com/kylemanna/docker-openvpn/blob/ded4414ef47a3ada632478ad16cad06d9c302c3d/bin/ovpn_genconfig#L43)
2. [Enable client to client routing through the OpenVPN server with `-c`](https://github.com/kylemanna/docker-openvpn/blob/ded4414ef47a3ada632478ad16cad06d9c302c3d/bin/ovpn_genconfig#L44)

**Comment by kopax** [comment]
@kylemanna Thanks for your recommendation.
I am hosting some mesos server, I really to have all the connection going through a main server.

 @ypid show me another solution which is __tinc__, I am currently trying to configure tinc with mesos, I'll tell you if it does the trick if you want

**Comment by ypid** [comment]
@kopax I would be interested :smile:

**Comment by kopax** [comment]
@ypid , it work really well with mesos.

All you have to do is add all hosts from the private network in `/etc/hosts`, bind mesos slave and master to the private ip.

I am not sure if all the traffic goes through a server or from any host to any host.

**Comment by ypid** [comment]
All right, thanks for the info. Sounds good. Traffic should flow directly between peers when I got the concept of Tinc right.

**Comment by kopax** [comment]
What do you mean the concept of tic right ?
I was following the digital ocean [guide](https://www.digitalocean.com/community/tutorials/how-to-install-tinc-and-set-up-a-basic-vpn-on-ubuntu-14-04)

But it was for 3 hosts, one in a private network, 2 accessible from the outside.

I didn't understand why only externalNync as the "Address" attribute in is host config file and the other not.

Finally I ended with 3 files by host, 2 files with just the local ip, 1 files with local ip + internet ip, I guess all my traffic goes through this server, do you know ?

**Comment by ypid** [comment]
Unfortunately now :wink:

**Comment by kopax** [comment]
Excuse me :D ?

**Comment by ypid** [comment]
I don’t know. (Fixed typo)
