### ISSUE TITLE
Understanding configuration updates for split tunnel to a dynamic list of hosts

### ISSUE THREAD

**Issue by vielmetti** [kylemanna/docker-openvpn#83]
The situation: I'm setting up a split tunnel to allow access to a bunch of individual hosts via a VPN. There's a longish list of them, all on different /32s, and from time to time that list will change.

What I want to avoid is having the client's OpenVPN configuration have to change when this list changes. I know I'll have to bump something on the server container to get this to work, but I'd hate to have to pull down new OVPN files every time.

Suggestions welcome to help me puzzle this out - I promise to write up whatever I find.

**Comment by vielmetti** [comment]
I think I can do this with a series of 

```
[-p PUSH ...]
```

commands, but I didn't see an example in the docs of how this is used in any detail.

**Comment by kylemanna** [comment]
If it's a split tunnel, then I assume you're avoiding routing on to the Internet, correct?

Could you use a VPN with a private subnet and send the /24 (or whatever) on to the VPN for private routing?  Use `ovpn_genconfig -d` to make the subnet private.

Then you'll have a collection of /32s that are connected to larger subnet (i.e. /24) and routed by the openvpn daemon once the packets get there.

I use this for private networks that don't need to route to the Internet over the VPN.

**Comment by vielmetti** [comment]
Thanks for all the help. We decided to back off on the split tunnel config and just run this as a full tunnel - hope to revisit this when the VPN/VPC configuration is less complex.

This got written in the process:

http://vielmetti.github.io/post/2015/2015-12-04-split-tunnels-considered-harmful/

for what it's worth. I'll close the issue.
