### ISSUE TITLE
Access host machine

### ISSUE THREAD

**Issue by jeremysells** [kylemanna/docker-openvpn#84]
Hi,
Thanks for building this docker image, it looks awesome.

I am trying to replace my local install of openvpn server (on the host machine) with this docker instance. Is it possible to access the host machine through the openvpn server? i.e. ssh to the host machine through the docker openvpn server. I guess adding an openvpn client to the host machine is a bad idea? (as then the docker openvpn server would have two routes to the same network)

I have other docker containers running on the same host machine (such as redmine and gitlab) which currently bind ports to the local openvpn servers interface's ip address 
```sh
docker run --name gitlab -d \
    --publish 192.168.255.110:8383:80 \
...
```

Thanks

**Comment by kylemanna** [comment]
I don't know that I have a good solution for your described problem.

With similar issues I've run an openvpn client within each docker container, see my [docker-tahoe-lafs](https://github.com/kylemanna/docker-tahoe-lafs/blob/938fa423fbd0a68838e7cd671484df29670f92de/bin/tahoe_node#L15-L56) example.  But, I don't really like the way this works, it feels hacky and heavy for services on the same machine.  It does work though, there are no routing issue as you suggested concerned you (docker routes to /30 subnets, one for each client).

Another, possibly better, approach would be to the `docker run --net=container` option and tell your redmine and gitlab containers to use the openvpn container's networking stack.  This seems better, but I haven't tried it yet.   I'd give this a shot and share with us what you find.

**Comment by jeremysells** [comment]
Thanks for the suggestions.
I decided to use the configuration the docker machine created but use the locally installed openvpn server (on the host machine) for now. I can still use the scripts in docker machine (to generate clients etc) which is nice. I will close this ticket and re-open if I get time to try some more things and have something to share

**Comment by kylemanna** [comment]
Thanks for the update!
