### ISSUE TITLE
docker attach to the vpn container?

### ISSUE THREAD

**Issue by Xixiao007** [kylemanna/docker-openvpn#87]
Rookie question:
I try `docker attach [running-openvpn-container-name]` to connect into the container. However, the terminal does not return the container, it hangs and allows my input without response.
Why is this?

**Comment by Xixiao007** [comment]
It seems here is the answer already: https://github.com/kylemanna/docker-openvpn/blob/master/docs/debug.md

**Comment by kylemanna** [comment]
The `docker exec` command will also let you connect to an already running container.  Checkout details in the [Docker docs](https://docs.docker.com/engine/reference/commandline/exec/).
