### ISSUE TITLE
Using with LDAP?

### ISSUE THREAD

**Issue by jsdevel** [kylemanna/docker-openvpn#88]
I found this tutorial, but wasn't sure if there was a known / better way when using this image:  https://www.howtoforge.com/setting-up-an-openvpn-server-with-authentication-against-openldap-on-ubuntu-10.04-lts

**Comment by kylemanna** [comment]
LDAP is far outside the scope of this repo.  You can probably add support to the docker image one way or another, but it's an extremely special case.

**Comment by ypid** [comment]
@kylemanna is right. LDAP is outside of the scope. May I suggest you to use some configuration management like Ansible and [debops-slapd](https://github.com/debops/ansible-slapd), [debops.openvpn](https://github.com/debops-contrib/ansible-openvpn). DebOps does not currently support this but patches are welcome.

**Comment by jsdevel** [comment]
Sounds good.  Sounds like maybe a different docker image would be ideal.  Thanks guys!

**Comment by LeoLiuYan** [comment]
@jsdevel  @kylemanna  
Seems alpine has a issue about  openvpn-auth-ldap
https://bugs.alpinelinux.org/issues/6726

**Comment by maurerle** [comment]
Issue is still persistent. More information on this bug and a workaround which worked for me:
https://github.com/threerings/openvpn-auth-ldap/issues/60#issuecomment-446289680
I made a `Dockerfile` like [this](https://github.com/ivanovUA/docker-openVPN/blob/master/Dockerfile) (which is referenced in the link above) but `FROM kylemanna/openvpn`.
added following line in openvpn.conf:
`plugin /usr/local/lib/openvpn-auth-ldap.so /path/to/auth-ldap.conf`
