### ISSUE TITLE
Merge efforts with jpetazzo's origional Dockvpn

### ISSUE THREAD

**Issue by ClashTheBunny** [kylemanna/docker-openvpn#9]
I opened a pull request (jpetazzo/dockvpn#8) for some work that I was working on from the original jpetazzo/dockvpn some time ago.  After I did that I went and researched other dockvpn branches and found your's and found your changes to be mostly the same as what I was working on.  "Docker openvpn" still results in jpetazzo's repo first, and your's second.

Somebody has now urged jpetazzo to accept my pull request and he is willing to make it his new master, but I think that we could do better to combine our efforts.  He has offered to either name one repo as a successor repo, or give commit access to his.  Would you be interested in joining efforts towards making one canonical openvpn solution for docker?  Or would you prefer to continue working on your changes alone?  From reading through your changes vs my changes, I think that we are both headed in very similar directions.

**Comment by kylemanna** [comment]
No word back.  This repository was just converted to standalone.

**Comment by kylemanna** [comment]
I think these have diverged too much to merge back.
