### ISSUE TITLE
Using public IPv4 for the clients

### ISSUE THREAD

**Issue by Bastien-** [kylemanna/docker-openvpn#91]
I have a few public IPv4 routed to the server I'm using for this VPN and I would like to distribute them to the clients instead of the default private IPs.

How would you recommend doing this?

**Comment by kylemanna** [comment]
Off the top of my head I'm not sure of an easy to way to do that for a few IPs.  If you had an entire subnet you could do traditional static routing.

One option might be to do some iptables magic to map the external IPs to internal IPs, but it sounds like quite a headache and hacky.

Perhaps someone else who follows this repo might know?

**Comment by Bastien-** [comment]
Thanks. Yes indeed that would be easier with an entire subnet.  
It would be so sweet to specify the IP, v4 or v6 /64, to be assigned to a given client when creating / retrieving the client config.  
I'll keep looking for a solution but right now I'm in the dark. If anyone has a clue I'll gladly take it!

**Comment by karimelm** [comment]
Perhaps its possible to start up multiple openvpn containers with the environment variable OVPN_NATDEVICE and using net=host. Assign each of those public ips to their own virtual interface and use that as OVPN_NATDEVICE.
