### ISSUE TITLE
set up a openvpn client on the same host

### ISSUE THREAD

**Issue by hs3180** [kylemanna/docker-openvpn#93]
if you bind 1194 port to 0.0.0.0 on a host with several IPs.
if your server domain is bind on secondary IP(in most cases, `docker0`'s IP will be the primary IP),
openvpn will reject :
    Incoming packet rejected from xx.xx.xx.xx:1194[2], expected peer address: xx.xx.xx.xx:1194 (allow this incoming source address/port by removing --remote or adding --float)

**Comment by kylemanna** [comment]
It is possible.

Checkout the [`basic.sh`](https://github.com/kylemanna/docker-openvpn/blob/b298eb16bc22ed48ce492dd62c5bda1d564bffca/tests/basic.sh) test which runs a server and client.

**Comment by hs3180** [comment]
@kylemanna I solved it by bind `1194` to a specific IP (other clients connect to) rather than `0.0.0.0`. It doesn't need bind client by `--net=host` which allows it to access all local services in the docker host.
