### ISSUE TITLE
Use cloudflare cfssl to manage certificates 

### ISSUE THREAD

**Issue by adilroot** [kylemanna/docker-openvpn#94]
Is it possible to replace easy-rsa with the cfssl (a powerful tool and api from cloudflare) tool to manage certificates.

Inspired from this blog post:
https://ghu.io/openvpn/

cfssl docs:
https://blog.cloudflare.com/introducing-cfssl/
https://coreos.com/os/docs/latest/generate-self-signed-certificates.html#download-cfssl

**Comment by kylemanna** [comment]
Initial glance doesn't show any advantages.  The interface to EasyRSA is already pretty minimal.  What would be the benefit?

**Comment by adilroot** [comment]
I think one of the benefit is to take advantage of cfssl (or vault from hashicorp) as an HTTP API server for signing, verifying, and bundling TLS certificates

**Comment by adilroot** [comment]
I think this can be closed, EasyRSA can do the job for now
