### ISSUE TITLE
VPN to private network

### ISSUE THREAD

**Issue by streamnsight** [kylemanna/docker-openvpn#95]
I am a bit confused about what this image does... 

Correct me if I am wrong but I get the impression this container basically proxies connection to the outside, so that one's IP looks like it is the server's IP.

How would I use this to VPN into a private network?
I am trying to run this on Kubernetes. My goal is to access the services running inside the cluster without exposing them to the outside, using VPN connection into the cluster.

I managed to run this image in my cluster, but when I'm connected, I don't seem to have access to anything: trying to ping or DNS resolve any of my services just gets nowhere. 
I can't ping the IPs of other pods running there, so somehow I guess the `iptables` rules are blocking all this traffic. Is that right?

I would like to understand how this image actually works, and how I would go about doing what I'm trying to achieve.

Thanks for help.

**Comment by kylemanna** [comment]
It can operate as a NAT router as you described or a proper *private* network as you are looking to build, or both.  I use a network that operates as both daily.

* To prevent the server from routing out on to the Internet see the [`ovpn_genconfig -d`](https://github.com/kylemanna/docker-openvpn/blob/2fa3abe064d95fa415c86a10cb10e11592ec4f10/bin/ovpn_genconfig#L43) option.
* To enable the client to talk to each other, see the [`ovpn_genconfig -c`](https://github.com/kylemanna/docker-openvpn/blob/2fa3abe064d95fa415c86a10cb10e11592ec4f10/bin/ovpn_genconfig#L44) option.

Together, those should get you going.  Let me know how it works!

**Comment by streamnsight** [comment]
sorry, can't get this to work:

the IP of the node where the VPN container runs is 192.168.10.152, it is bound to host.
my cluster subnet is 10.2.0.0/16
the DNS is 10.3.0.10

if I use 
`docker run -v /etc/openvpn:/etc/openvpn --rm kylemanna/openvpn ovpn_genconfig -u udp://192.168.10.152:1194 -n 10.3.0.10 -c -d`

I cant' even ping the other nodes I could ping before.
I can't ping DNS.

what's the best way to debug this?
Thanks

**Comment by streamnsight** [comment]
I managed to setup routes to be able to ping the Pods and the Services by IP, but still can't get DNS to work.

**Comment by streamnsight** [comment]
@kylemanna 
How does the DNS directive work exactly? What does it do that DNS needs to be specified? 
I managed to be able to reach my services by IP in the cluster, but the nslookup returns SERVFAIL from the cluster DNS server. 
Now sure how to troubleshoot that.

Thanks for help

**Comment by streamnsight** [comment]
finally got this working by pushing the DNS search domain to the client

```
docker run -v /etc/openvpn:/etc/openvpn --rm kylemanna/openvpn ovpn_genconfig \
-u udp://192.168.10.152:1194 \
-n 10.3.0.10 \
-n 192.168.10.1 \
-n 8.8.8.8 \
-n 75.75.75.75 \
-n 75.75.75.76 \
-s 10.8.0.0/24 \
-d \
-p "route 10.2.0.0 255.255.0.0" \
-p "route 10.3.0.0 255.255.0.0" \
-p "dhcp-option DOMAIN localhost" \
-p "dhcp-option DOMAIN-SEARCH cluster.local" \
-p "dhcp-option DOMAIN-SEARCH svc.cluster.local" \
-p "dhcp-option DOMAIN-SEARCH default.svc.cluster.local" \
```

**Comment by kylemanna** [comment]
Cool, thanks for the update!  That's the longest genconfig I've seen!

**Comment by dbachorz** [comment]
You can add routing configuration to your openvpn.conf file inside docker container (kylemanna/openvpn).

**Comment by prueg3l** [comment]
Hi, I tried to set the port with 
docker-compose run --rm $VPNServerName ovpn_genconfig -u udp://$VPNServerName.ix-tech.com:$VPNServerPort 
but it seem that the port declaration will be ignored.
