### ISSUE TITLE
2-Step Verification  using Google Authenticator with OpenVPN 

### ISSUE THREAD

**Issue by adilroot** [kylemanna/docker-openvpn#99]
Is it possible to add Google Authenticator (https://github.com/google/google-authenticator) for two step verification.

**Comment by fabn** [comment]
I was looking for the same thing. I was able to install and compile that project in other distros.

However in alpine linux it would require a lot of dependencies to build it (gcc, automake, possibly git, etc) so I think that install it using commands in Dockerfile would increase the image size a lot?

Do you know if there is a package for alpine linux already built?

**Comment by fabn** [comment]
@adilroot see #102 and provide feedback. Thanks.

**Comment by jlm** [comment]
Any progress on this?  It would be so useful.

**Comment by ClashTheBunny** [comment]
This doesn't make a whole ton of sense.  The factors are not very different for TFA and key based authentication.  They are both based on what you have.  If somebody gets your phone, will they also have your cert?  Probably for me, given that I use my VPN on my phone.

What is the use case for this?  The case when you lose your tablet, but not your phone?  You lose your computer, don't have disk encryption, but not your phone?

If you want better security, add something that you know or are to the factors before you add another thing you have.  Maybe just encrypt your cert, so it's like 1.5 factor authentication?

**Comment by fabn** [comment]
@jlm #102 is working. It's also present on [docker hub](https://hub.docker.com/r/fabn/openvpn/) if you want to try it. I don't know if @kylemanna is interested in merging that PR.

@ClashTheBunny The use case for this is when you're accessing VPN from your computer and you're using your mobile device as second factor. If you're using your phone for VPN you're right, there's no point in enabling this (optional) feature.

**Comment by kylemanna** [comment]
Just merged #102, please continue discussion over there if any issues are encountered.  Thanks to @fabn

**Comment by jlm** [comment]
Many thanks.

        -- John

**Comment by adilroot** [comment]
It works like a charm.

Many thanks @fabn for the hard work, @kylemanna for the merge

**Comment by kylemanna** [comment]
Hey @fabn, The google-authenticator package for Alpine Linux seems to have disappeared and breaks the build. Know anything about this?

**Comment by kylemanna** [comment]
Looks like it was deleted on August 25th due to being unmaintained and not updated:

> testing/[multiple]: move unmaintained packages
> This moves all packages from testing to unmaintained which have not been
> updated for atleast 6 months. If you are affected by this commit please follow
> this proceddure:
> 
> * make sure your packages build on all architectures
> * move your pacakge(s) back to testing
> * if you want to keep this package and can maintain it (or find somebody to
>   maintain it for you) for a minimum of 6 months ask it to be moved to community


Github: https://github.com/alpinelinux/aports/commit/b6af1e02efe594039707cd882517663d5370f375
[AlpineLinux cgit](http://git.alpinelinux.org/cgit/aports/commit/?id=b6af1e02efe594039707cd882517663d5370f375)

Any interest in maintaining that package to keep google-authenticator included in this docker image?

**Comment by fabn** [comment]
I'll take a look to this later.

I'll keep you posted.

**Comment by kylemanna** [comment]
Continue discussion of google authenticator in issue #153

**Comment by amit-k-yadav** [comment]
Is google-authenticator working again?
